### ISSUE TITLE
Could not read "phpunit.xml"

### ISSUE THREAD

**Issue by Thinkscape** [paratestphp/paratest#100]
Paratest refuses to see my phpunit.xml file and then refuses to read it when I use `-c` param. Tried 0.7.1 and dev-master.

`tests/phpunit.xml` file:

``` xml
<phpunit bootstrap="./bootstrap.php" colors="true">
    <testsuites>
        <testsuite name="Unit Tests">
            <directory>./AppTest</directory>
        </testsuite>
    </testsuites>
</phpunit>
```

Reproduce:

```
$ composer require brianium/paratest:dev-master
$ cd tests
$ ../vendor/bin/paratest



  [RuntimeException]
  No path or configuration provided (tests must end with Test.php)



paratest [-p|--processes="..."] [-f|--functional] [--no-test-tokens] [-h|--help] [--coverage-clover="..."] [--coverage-html="..."] [--coverage-php="..."] [--phpunit="..."] [--runner="..."] [--bootstrap="..."] [-c|--configuration="..."] [-g|--group="..."] [--exclude-group="..."] [--stop-on-failure] [--log-junit="..."] [--colors] [--path="..."] [path]

$ ../vendor/bin/paratest -c phpunit.xml
Could not read "phpunit.xml".
```

**Comment by wojciechmorawski** [comment]
Same problem here - but fortunately I've got solution :) 

So: 

phpunit tests -c ./tests/phpunit.xml
Could not read "./tests/phpunit.xml".

It took me 30 minutes to realize that I've got white space at the end of config file.
It was : "phpunit.xml "
It should be : "phpunit.xml"

After this small change everything works like a charm 👍

**Comment by Slamdunk** [comment]
Hi, https://github.com/paratestphp/paratest/pull/498 reverts https://github.com/paratestphp/paratest/commit/e7e9494022190a03aa37ae7e5a2946b17c31686c because we no longer rely on `getcwd()` function anymore
