### ISSUE TITLE
ENV variables not passed to phpunit tests using standard runner (linux)

### ISSUE THREAD

**Issue by jvanbouchaute** [paratestphp/paratest#103]
We use Jenkins to set a number of ENV variables to convey configuration into our (Selenium) PHPunit testcases.

We use paratest (0.7.2) to parallelize our testcases.

For some strange reason, we don't get our ENV variables in our testcase when using the default Paratest runner. It causes our Selenium PHPUnit testcases to fail since we miss config.

However, when using --runner WrapperRunner , the env variables are passing to our testcases, but that WrapperRunner implementation is not stable for our testsuite ("Worker has crashed" error when test failure occurs)

PHP 5.4.18
PHPUNIT 3.7.37
Linux SLES 11SP2  x64
Jenkins on JDK8
Symfony 2.3

Paratest invoked with : 

--configuration phpunit-selenium.xml.dist
--processes 8
--colors
--bootstrap '/mywebapp/src/app/bootstrap.php.cache'
--log-junit '/data/phpunit-selenium-testresults.xml'

Any thoughts ? 
We have had this working before, but for some reasons it no longer is ...

**Comment by andrejguran** [comment]
ping, still not working properly. ENV set in phpunit.xml are not being transferred to the tests

**Comment by hugochinchilla** [comment]
I'm also affected by this
