### ISSUE TITLE
Add support for direct output (including Incomplete/Skipped)

### ISSUE THREAD

**Issue by chbiel** [paratestphp/paratest#153]
currently the ResultPrinter only gives feedback when a whole testclass is done.
when you have testclass with 100 of tests, this can take a long time and you don't know if something is happening.

to solve this, we could use the $callback parameter of Process::start method from symfony/process.
this callback takes every output from the underlying test execution and can do whatevery you want with it.
in our case we could parse the output to redirect the correct output to the users console.

another PRO for the use off that callback is a possible fix for https://github.com/brianium/paratest/issues/60. when adding the "--verbose" option to phpunit, S and I tests are also written to the callback, so we can track these.

what have to be done:
- rewrite/overwrite ResultPrinter, or add a new class, that handles the direct output of the executing processes and aggregates/combines the returned data. this class should be passed to start() method as a callable
- add a new option to paratest, e.g. "--fast-feedback" that causes 1. "--verbose" is passed to phpunit 2. uses the new output handling from above as a callback for the processes

Pitfalls:
- use the same class as callback for several processes can cause problems when syncing, needs to be tested
- the classes have to be reorganized to support this.

what do you think?

**Comment by julianseeger** [comment]
>currently the ResultPrinter only gives feedback when a whole testclass is done.
when you have testclass with 100 of tests, this can take a long time and you don't know if something is happening.

Is this true when using the ```-f``` parameter? And du you run paratest without ```-f``` ? When you always use -f, you should get instant feedback per method and it fit's the usecase when it "can take a long time". But if the implementation is reliable, the fast feedback option doesn't hurt at least.


>another PRO for the use off that callback is a possible fix for #60. when adding the "--verbose" option to phpunit, S and I tests are also written to the callback, so we can track these.

Thats probably more interesting. Do you think it can be parsed in a reliable way? In a way that a test printing out "." doesn't interfere?


>add a new option to paratest, e.g. "--fast-feedback" that causes 1. "--verbose" is passed to phpunit 2. uses the new output handling from above as a callback for the processes

Given it can be implemented reliably. Is there a need to have a separate option? "--verbose" shouldn't have any (negative) influence on the tests so the "--fast-feedback" could replace the junit parsing.

=> Sounds definitely interesing ;)

**Comment by chbiel** [comment]
The -f option is not an option for us because we have many legency tests that have stupid dependencies -.-

> Thats probably more interesting. Do you think it can be parsed in a reliable way? In a way that a > test printing out "." doesn't interfere?

I'm not sure if this is possible. Have to be tested. E, F, S, I can be seperated through --colors flag from test output. I am not sure If "." has also a color attached.
This could be established (when not possible with --colors), with a intelegient parser that looks at the previous and following output. If both are valid, the "." is valid. But this is a very compicated way.
I would implement it anyway so everyone can choose. When the test outputs something (what I think the test should not do) he can choose the junit parsing method instead.

> Given it can be implemented reliably. Is there a need to have a separate option? "--verbose" > > shouldn't have any (negative) influence on the tests so the "--fast-feedback" could replace the junit parsing.

I would add an option to allow "old" junit logging and "new" parsing logging because of the possible parsing problem with "."

**Comment by julianseeger** [comment]
> When the test outputs something (what I think the test should not do) he can choose the junit parsing method instead.

Just like tests should be independent etc. ^^
But as long as omitting the `--fast-feedback` flag means junit parsing and thus, junit stays the default, this is a nice and backwards compatible enhancement. Looking forward to that patch.
