### ISSUE TITLE
paratest is not working anymore (configuration not found)

### ISSUE THREAD

**Issue by cbergau** [paratestphp/paratest#159]
Hey guys, i've been using paratest for a while, and i upgraded the version from whatever to dev-master.

https://github.com/cbergau/php-webdriver-examples

Those tests ran fine all the time, now since i upgraded it does not. I get an error message saying:

```
[RuntimeException]                                                
  No path or configuration provided (tests must end with Test.php)
```

When i run

```
./vendor/bin/paratest -c tests/phpunit.xml -p 15
```

**Comment by cbergau** [comment]
This error is only on dev-master, tag v0.7.0 works fine.

**Comment by danielbachhuber** [comment]
I think paratest requires test files to end in `-Test.php` as of #116

**Comment by andreasschroth** [comment]
Imo, this is expected behaviour, as the error message already clearly states.
