### ISSUE TITLE
phar package

### ISSUE THREAD

**Issue by justechn** [paratestphp/paratest#176]
It would be great to see this packaged in a phar file like phpunit so it can run without composer. I am setting this up on a build server and need to call it stand alone.

Thanks

**Comment by julianseeger** [comment]
Do you know an easy way to automate this?
Checking in the phar sounds redundant ant contains the risk that code and phar get out of sync (with merges etc).

I could attach a phar for each release manually ... but I would prefer some automated way ;)

**Comment by justechn** [comment]
It looks like it could be automated
http://code.runnable.com/Umu3fTe6SJxIAAAS/how-to-create-and-use-a-phar-archive-for-php
http://www.sitepoint.com/packaging-your-apps-with-phar/

Although I have not tried any of them out personally.

**Comment by brianium** [comment]
I have had some success with [box](https://github.com/box-project/box2) and [Robo](https://github.com/Codegyre/Robo) as a build tool. Create a build task in Robo for generating the phar, and a separate one to upload that phar to a location.

**Comment by Gasol** [comment]
@brianium Could you please upload the phar to github when release?

The Phar file is very useful when root project has some dependency conflict with paratest, for example 'symfony/console'.

**Comment by michaelbutler** [comment]
Yes we can look into this again. Note brianium doesn't work on the project any longer.
