### ISSUE TITLE
Feature request: support PHPUnit's repeat option

### ISSUE THREAD

**Issue by PieterDC** [paratestphp/paratest#187]
When I try to use the repeat option with ParaTest version 0.9.6, I get:

```
[RuntimeException]
  The "--repeat" option does not exist.
```

What's needed to support this option?

**Comment by PieterDC** [comment]
Months later, we developed code for this feature request ourselves. See https://github.com/brianium/paratest/pull/217

**Comment by julianseeger** [comment]
Contributions are always welcome :)

**Comment by stephandesouza** [comment]
Hey guys, bumping this with #594 

We're in need to find a false-positive and without `--repeat` is a horror story to find out =(
