### ISSUE TITLE
Paratest emits notice in flattenTests if a test case throws in setUpBeforeClass()

### ISSUE THREAD

**Issue by TysonAndre** [paratestphp/paratest#251]
If a test throws an Error in setUpBeforeClass, then caseFromNode(\SimpleXMLElement $node) is passed a SimpleXMLElement with "name", "time", and a string "error", but missing values for other fields, such as "assertions" (should be int, but I get the empty string)

- The output of phpunit when setUpBeforeClass throws differs from the typical PHPUnit XML output. "assertions" is not a field of the XML.

<s>Also, the below code seems wrong, and may be incorrect</s>

<s>`TestCase` documents that assertions, failures, errors, and skipped are integers, but `count` expects arrays. I assume this code may throw if `declare(strict_types=1)` is added in src/Logging/LogInterpreter.php</s>

A better alternative may be `             $dict[$case->file]->assertions += $case->assertions ?: 0`, `             $dict[$case->file]->failures += $case->failures ?: 0`, etc.

```php
             $dict[$case->file]->cases[] = $case;
             $dict[$case->file]->tests += 1;
             $dict[$case->file]->assertions += $case->assertions;
             $dict[$case->file]->failures += count($case->failures);
             $dict[$case->file]->errors += count($case->errors);
             $dict[$case->file]->skipped += count($case->skipped);
```

**Comment by julianseeger** [comment]
> TestCase documents that assertions, failures, errors, and skipped are integers, but count expects arrays

in https://github.com/brianium/paratest/blob/master/src/Logging/JUnit/TestCase.php :
```PHP
    public $failures = [];
```
And it's used as an array in `addDefect` so definition, documentation and usage with `count` look consistent. What am I missing?

**Comment by TysonAndre** [comment]
> And it's used as an array in addDefect so definition, documentation and usage with count look consistent. What am I missing?

Sorry, was looking at `TestSuite` (where those are integers) when I said *TestCase documents that assertions, failures, errors, and skipped are integers*, and got confused. You're correct about that.
