### ISSUE TITLE
Time to move repo to a separate organization?

### ISSUE THREAD

**Issue by brianium** [paratestphp/paratest#254]
I'm going to open this issue here both as a question and a todo.

**Is it time to move ParaTest to a separate organization? Maybe something like `paratest/paratest` or something else if that organization is not available?**

**Rationale for moving:**

My last contribution to ParaTest was back in 2015. @julianseeger has really stepped up to maintain this project and keep it moving forward - fielding PRs, ensuring quality, etc.. Some recent contributions from @TysonAndre, @jdufresne, and others have brought ParaTest into the present. I'm thrilled that something I started back in 2012 is still being used and developed today. I mean ParaTest just hit `1.0.0`!

This is the biggest reason I would like to move this repo to an organization. This project is kept alive by a community. I would like the location of this repository to reflect that. Being at `brianium/paratest` gives me too much credit.

**Potential pain points:**

I could use some guidance/input here. Considerations seem to be ease of migration. There might be a lot of projects out there depending on `brianium/paratest` in their `composer.json` files. Is there anything to look out for in making this process simpler?

I know a lot of people have been exposed to ParaTest by the great people at [Sauce Labs](https://saucelabs.com/) - and it looks like their documentation still references ParaTest as a tool for running functional tests in parallel. @jlipps if you're out there - is there anything we can/should do to make things painless for Sauce Labs users if we move things?

Again - I am pumped that so many people are using and contributing to ParaTest. I hope this project can continue to exist for a long time with the help of all the people who have worked to keep it alive and well.

**Comment by jlipps** [comment]
@brianium thanks for the ping. Moving to its own org makes sense. Just let me know what you decide and when you make the change and we can update any docs on our end!

**Comment by julianseeger** [comment]
Just FTR:
## :tada: 500 Stars Party :tada: :balloon: :birthday: *yay*

and regarding the topic: looks like composer has no feature like renaming a package. One can only abandon the old one (and mark it abandoned) and create a new package with the new name for the new repo location. Stars are more important than download stats aren't they?

**Comment by brianium** [comment]
I think so! Cool - I'll make a task for myself to do this sometime this week.

**Comment by alexhouse** [comment]
@brianium Did you ever get around to doing this, out of interest? I know you can "abandon" packages on packagist.org and enter a new package to pick up instead which should alert any existing users when they go to update composer - should be all you need to do to support existing users!

**Comment by brianium** [comment]
@alexhouse I created an organization and then never did anything with it O_o. I still intend to do this. Thank you for the reminder and the tip :)

**Comment by andreasschroth** [comment]
I close this issue now, as @brianium moved the repo now into the new organization: https://github.com/paratestphp
