### ISSUE TITLE
Teamcity error reporting

### ISSUE THREAD

**Issue by Strate** [paratestphp/paratest#265]
Hi!

I would use this utility on teamcity server, but I can't force `--teamcity` flag to the `phpunit` runner. Is it possible?

**Comment by julianseeger** [comment]
It's a little bit Note complicated.
The subprocesses of paratest report back to the main process of paratest and it is that process who needs to bei able to print teamcity result printer style. It shouldn't be complicated to add that printer to paratest. I'm just not sure if phpstorm would handle it correctly because it might not expect to see multiple Tests running at the same time.

**Comment by Strate** [comment]
@julianseeger 
> I'm just not sure if phpstorm would handle it correctly because it might not expect to see multiple Tests running at the same time.

I don;t know about phpStorm, but Teamcity itself do it well with parallel tests. Nowadays I make parallel tests with GNU Parallel, and everything ok.

**Comment by xakzona** [comment]
@Strate Can you give us example?

**Comment by Strate** [comment]
@xakzona basically it is simple run `phpunit --teamcity $file` with help of `parallel` command

**Comment by xakzona** [comment]
Paratest is better i think, the only think i need is teamcity option

**Comment by andreasschroth** [comment]
Closing this now as this should be possible by using the (pretty) new `--passthru` command.

**Comment by pakhomchik** [comment]
Adding `--passthru="'--teamcity'"` doesn't work as expected.

For example, `phpunit --teamcity` produces the following:
```
PHPUnit 8.4.3 by Sebastian Bergmann and contributors.
##teamcity[testCount count='42' flowId='5064']

##teamcity[testSuiteStarted name='/tests' flowId='5064']

##teamcity[testSuiteStarted name='Tests\FirstTest' locationHint='php_qn:///tests/FirstTest.php::\Tests\FirstTest' flowId='5064']

##teamcity[testStarted name='first_test' locationHint='php_qn:///tests/FirstTest.php::\Tests\FirstTest::first_test' flowId='5064']

[...]
```
But `paratest -p 3 /tests --passthru="'--teamcity'"` ignores `'--teamcity'` parameter:
```
Running phpunit in 3 processes with /vendor/phpunit/phpunit/phpunit

Configuration read from /app/phpunit.xml

E.........................................

Time: 22.12 seconds, Memory: 8.00 MB
```
`paratest -p 3 /tests --passthru="--teamcity"` returns the same result.
