### ISSUE TITLE
testdox-text file is messed up

### ISSUE THREAD

**Issue by G3z** [paratestphp/paratest#273]
i'm using paratest 1.0.1 & phpunit 6.2.3 with laravel 5.4
this is my phpunit.xml

```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit backupGlobals="false"
         backupStaticAttributes="false"
         bootstrap="bootstrap/autoload.php"
         colors="true"
         convertErrorsToExceptions="true"
         convertNoticesToExceptions="true"
         convertWarningsToExceptions="true"
         processIsolation="false"
         stopOnFailure="false">
    <testsuites>
        <testsuite name="Feature Tests">
            <directory suffix="Test.php">./tests/Feature</directory>
        </testsuite>

        <testsuite name="Unit Tests">
            <directory suffix="Test.php">./tests/Unit</directory>
        </testsuite>
    </testsuites>
    <filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
    <php>
        <env name="DB_CONNECTION" value="pgsql_testing"/>
        <env name="APP_ENV" value="testing"/>
        <env name="CACHE_DRIVER" value="array"/>
        <env name="SESSION_DRIVER" value="array"/>
        <env name="QUEUE_DRIVER" value="sync"/>
    </php>
    <logging>
        <log type="coverage-html" target="./public/coverage" lowUpperBound="35" highLowerBound="70"/>
        <log type="testdox-text" target="./storage/logs/testdox.log"/>
    </logging>
</phpunit>
```

with `$ phpunit` this is my `testdox.log`

```
s\Feature\Counter
 [x] Foreign counters
 [x] Italian counter
 [x] Italian decrese counter with order equal to general
 [x] Italian decrese counter with order grater than general and counter 1 is bigger
 [x] Italian decrese counter with order grater than general and counter 2 is bigger

s\Feature\Customer
 [x] Can be created
 [x] Can be associated

s\Feature\Order
 [x] Customers can have orders
 [x] Customer commissions
```

this is the same after `$ paratest`
```
s\Feature\Counte [ [x] Foreign counters
 [x] Italian counter
 [x] Italian decrese counter with order equal to general
 [x] Italian decrese counter with order grater than general and counter 1 is bigger
 [x] Italian decrese counter with order grater than general and counter 2 is bigger
```

**Comment by andreasschroth** [comment]
I'm closing this now. Please feel free to reopen if this still happens with the latest Paratest version 2 and PHPUnit 7. Thank you for your understanding.

**Comment by Goahnary** [comment]
This issue still exists for me using Paratest version 2. I am also running PHP 7 and phpunit 7. It only seems to leave the report from the last performed test.

**Comment by Goahnary** [comment]
Could we set a flag to enable no truncating of the log file? Or maybe create a new log file with a datestring as the name?

**Comment by Goahnary** [comment]
Just as an update: I created a fix for phpunit to fix this issue. But I got some feedback from Sebastian Bergmann and he believes this should be solved at the paratest level by reading the standard out from the `--coverage-xml` flag. Then we should aggregate that until the end to print a logfile. I haven't had time to do this but eventually I will get around to it.

**Comment by Slamdunk** [comment]
First things first: as of yet each PHPUnit sub-process creates its own log file and eventually overwrites the same one created by another sub-process. We need to wait https://github.com/sebastianbergmann/phpunit/issues/4401 in order to avoid this behavior.

Second: we can collect each testdox-text and then merge them back together,
