### ISSUE TITLE
Create a 1.1.0/2.0.0 release or alpha?

### ISSUE THREAD

**Issue by TysonAndre** [paratestphp/paratest#276]
E.g. want an official release including https://github.com/brianium/paratest/commit/0c48af96fd9a5fe36dd5f14282ac5dc5939f109c to avoid the E_USER_DEPRECATED warning

I'm suggesting 1.1.0 (or 2.0.0?) as a version because support for older phpunit versions was dropped after 1.0.1, in https://github.com/brianium/paratest/commit/fe0ed85bc392392c8a46de81923a639e63708355

**Comment by julianseeger** [comment]
1.1.0 sounds good. 2.0.0 would be kind of extreme ^^ we don't even have an api break or something like that

**Comment by michaelgv** [comment]
I believe this has been included in the latest 1.1.0 release, but I’ll double check
