### ISSUE TITLE
defaultTestSuite attribute is ignored

### ISSUE THREAD

**Issue by okdewit** [paratestphp/paratest#283]
PHPUnit 6.1 and up supports `defaultTestSuite` like this:

```XML
<phpunit defaultTestSuite="FastUnitTests">
<testsuites>
  <testsuite name="FastUnitTests">...</testsuite>
  <testsuite name="SlowFunctionalTests">...</testsuite>
</testsuites>
```

This is honored by phpunit (currently using 6.4.3), but seems to be ignored by Paratest (1.0.1).

No big deal, but might be a useful addition.

**Comment by 4n70w4** [comment]
The same issue! Any news?

brianium/paratest 4.0.0
phpunit/phpunit 8.5.0

**Comment by verfriemelt-dot-org** [comment]
this is still the case :(

**Comment by Mike-Benoit** [comment]
Yes, this would be a handy addition for us.

**Comment by Slamdunk** [comment]
I think this might be fixed in ParaTest 7, please give it a try and tell me
