### ISSUE TITLE
new option: --stop-on-error

### ISSUE THREAD

**Issue by marcelopm** [paratestphp/paratest#284]
Same as https://github.com/brianium/paratest/pull/50 but for --stop-on-error

The reason why is that while using paratest with:
- docker
- laravel 5.5
- orchestral/testbench
- and others

We get some random false failures from time to time as reported in here:

https://github.com/orchestral/testbench/issues/202#event-1327024630

However, instead of giving up test parallelisation due to those, we opted to implement a test re-run script for those false failures, which seems to work well for our build process.

So it could get even better in case we had a option like --stop-on-error, so our script don't have to wait for lengthy tests to finish to be able reschedule them for a retry in case of those known false failures.

Update: this is no longer relevant to our testing solutions

**Comment by andreasschroth** [comment]
I'm going to close this now, as I can't see a good use-case for this. As you said, there was another problem with your tests randomly failing.

If someone has a good use-case for this, please feel free to re-open and / or submit a PR.
