### ISSUE TITLE
Make --colors option compatible with PHPUnit's version

### ISSUE THREAD

**Issue by Gert-dev** [paratestphp/paratest#293]
Some scripts and IDE tools written for PHPUnit set the `--colors` parameter to an actual value, such as `--colors=always`. Unfortunately this is incompatible with the version that paratest offers, as it throws the following error, making a simple replace of `phpunit` with `paratest` impossible:

```The "--colors" option does not accept a value```

I'm not sure if the `--colors` option in paratest is the same as the one from PHPUnit or if they control different, unrelated behaviors.

In any case, in PHPUnit the allowed values are `never`, `auto` and `always`. If they are the same switch, perhaps the easiest solution would be to map the former to the same behavior as omitting the `--colors` option and the latter two to the same behavior as `--colors` does now. The current version can perhaps even be maintained by setting it to `auto` by default.

If they do not share the same behavior... well, either tools will have to support paratest seperately or paratest would have to perform a BC break, which is unfortunate 😐.

In any case, thanks for your efforts!

**Comment by willemstuursma** [comment]
This would be great, then we can finally have pretty colors in Bitbucket pipelines.

**Comment by MatejTopolovec** [comment]
Hi,

I'm not sure if this is related to this issue, but it seems that I cannot get paratest to work on Symfony project.

It throws:

In ArgvInput.php line 209:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--colors" option does not accept a value. 

Paratest version: ParaTest 3.1.2
PHPUnit version: PHPUnit 8.5.2 by Sebastian Bergmann and contributors.

I'm running paratest in docker container as is:

vendor/bin/paratest --testsuite --verbose=1 functional

Thanks and BR!

**Comment by simonmaass** [comment]
still not working...

**Comment by Slamdunk** [comment]
A PR would be very welcome :+1:
