### ISSUE TITLE
Call for maintainers

### ISSUE THREAD

**Issue by brianium** [paratestphp/paratest#297]
Figured I would start a thread to discuss things with parties interested in maintaining.

**Comment by brianium** [comment]
Going to update the README as well. I have not used ParaTest in quite some time, and I don't really use that much PHP any more either. It sounds like that is the case for @julianseeger as well. ParaTest seems to help a lot of people, so it would be great if the project kept going. Maybe a maintainer or maintainers could step up and keep this thing going. If not, I fear this project will continue to language and grow stale.

**Comment by paragonie-scott** [comment]
I know a lot of people who use this internally. I've passed it onto some of them in case they want to step up, since they have a stronger incentive than myself to keep it running strong.

If they do not contact you by February 1, I'll be happy to get involved with maintaining this project.

**Comment by brianium** [comment]
@paragonie-scott many thanks 😄

**Comment by geggleto** [comment]
Will bring up with other Slim Maintainers

**Comment by brianium** [comment]
@geggleto awesome! thank you for looking into it

**Comment by michaelgv** [comment]
@brianium I’m willing to take on maintaining, my business which focuses on PHP entirely, we use this on a daily basis. We’d be happy to take it over and dedicate myself to actively maintaining it full time. Let me know :)

**Comment by michaelbutler** [comment]
My thoughts, if I had a choice I'd prefer to give rights & responsibilities to someone/those who have contributed to paratest and know a bit about the internals and clean code.

**Comment by brianium** [comment]
Agreed :) - Mainly I want to keep this project healthy for the people that benefit from it. If someone has experience contributing to ParaTest, that would be a definite plus, but someone with time and energy is valuable too :) Maybe we leave the issue open for another week or so and have a conversation then?

**Comment by andreasschroth** [comment]
I agree with @michaelbutler , usually that's a good choice for an OS project.

But if none of the current maintainers is interested in spending more time on it, it might also be good to pass the project on to someone else.

I'm CTO myself and on the backend, we focus mainly on PHP. If you might be interested in passing the project over to us, please let me know, we could dedicate some time from our paid devs to it.

**Comment by brianium** [comment]
Just a heads up to anyone interested here - I have an internal note to check back here on Feb 1. Just so no one thinks this is getting lost or forgotten 😄

**Comment by bradhanebury** [comment]
@brianium I'm the CTO that @geggleto mentioned earlier. We really like this project and when @geggleto mentioned to me that it was looking for a new maintainer, it seemed like a good fit. We'd be happy to bring it into the Mobials organization and offer it the dedicated resources that it deserves.

**Comment by brianium** [comment]
@bradhanebury that is great news! I'd like to wait until the end of the day tomorrow to see if anyone else has input/hopes/concerns for the project. Thanks again!

**Comment by michaelbutler** [comment]
@bradhanebury Could you provide a list of public repos where you use paratest (e.g. in the composer.json file)?

**Comment by bradhanebury** [comment]
@michaelbutler unfortunately, all of our repositories are private. We are not allowed to open any of them up to the public.

**Comment by brianium** [comment]
Just checking in to see what we are all thinking. I am pretty drawn to the notion of dedicated support from an organization, but I understand reservations about lack of contributions or open source examples.

At this point - I think an expressed desire/commitment to maintain ParaTest is preferable to the open source pedigree if no one with said pedigree is able.

@paragonie-scott I don't think I heard from anyone, do you have thoughts/input on this? You had mentioned you may be willing to help with maintenance. Do you have any input/thoughts on moving forward?

Couple business owners/CTOs are willing - @bradhanebury, @andreasschroth, @michaelgv - do any of you have strong feelings about who should or should not take over? Not trying to create competition - just want to make sure everyone is heard :)

@michaelbutler - you have been around for a while and you seem to have interest in keeping things healthy :) - do you or anyone you know have some time to dedicate?

@julianseeger any thoughts/input?

I realize dedicating time is a big deal. I expect nothing, and I'm sure a ton of people would be grateful for any time spent.

**Comment by julianseeger** [comment]
> @julianseeger any thoughts/input?

Hard decision. Maybe a hybrid approach might be possible? If the project stays in some unrelated namespace (like paratest/paratest) but said company / companies are added as maintainers, then everybody should benefit from it.
If it works, then the company get's credibility from that anyways and if it doesn't work then there is a dead maintainer on the collaborators list but the project doesn't have to die with the broken promise.

Normally I would prefer anyone with existing contributions and a full contribution-list on his profile (@andreasschroth  has at least a steady amount of private contributions though) but as history has shown us (with me), that might not be enough here.

**Comment by michaelgv** [comment]
If I may, why don’t a few of us team up and joint maintain it? There’s no hurt having multiple maintainers!

Thoughts everyone? 

@julianseeger @bradhanebury @andreasschroth

**Comment by andreasschroth** [comment]
Well, I think it's a very tough decision to make, as nobody here knows each other really.

The main thing why I replied here is that I'd be sad to see such a great project be gone. Especially in a time, where having automated tests is an absolute standard which everyone should follow and not only continuous integration, but also continuous deployment applied almost everywhere. Thus, at least for us, having parallel tests and fast CI / CD is crucial.

Regarding me, I'd be absolutely fine when there are multiple maintainers in the project, I think that's a nice idea. @michaelgv  👍 

Maybe, if all agree, we could set up something like a dedicated communication channel, depending on what you use (e.g. maybe Slack?) and discuss the most important next steps for this project.

**Comment by Potherca** [comment]
+1 for having a separate Paratest organization on github with multiple maintainers added.

**Comment by julianseeger** [comment]
+1 (thats what I was trying to suggest ^^)
For slack we would need a sponsor I think. Maybe this works for now: https://discord.gg/5vYrQzX

**Comment by brianium** [comment]
Ok sweet. I set up an organization a while ago and I have yet to do anything with it - https://github.com/paratestphp

Is anyone willing to make the switch?

I still haven't fully researched what moving a repo to an org means - especially with regards to composer. Would really love it if someone took this task over.

**Comment by michaelgv** [comment]
@brianium I’m willing to make the switch, I’ve moved repos around before, typically it’s just a matter of updating composer config (git link), and then it should work.

**Comment by andreasschroth** [comment]
Thanks for creating the Discord @julianseeger, I just joined.

**Comment by bradhanebury** [comment]
:+1 this sounds good to us as well.

**Comment by michaelbutler** [comment]
I think moving to `paratestphp` organization would be great. :)

**Comment by julianseeger** [comment]
@brianium move instructions are here: https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/
If you have time, you might wan't to join us at discord. 5 people have already joined

**Comment by brianium** [comment]
Alright - I'll give it a go transferring it to the org sometime this weekend. I'll get the interested maintainers here added as well 👍

**Comment by brianium** [comment]
Ok - repo has been moved and invites sent. @michaelgv - if there is any work to be done in terms of making composer users path forward a happy one, can you take that work over?

I've invited everyone that I thought may be interested, if I invited you and you are not interested/able - then please ignore :)

I am a little uncertain how to hand over admin rites - should all the maintainers be given admin rites? Or is it enough to leave write access enabled? Would be great to have one or more people able to manage collaborators. Anyone interested?

**Comment by julianseeger** [comment]
All maintainers should also bei maintainers on packagist. (Packagist -> menu -> Username -> my packages -> paratest -> the Big plus to add maintainers).

**Comment by brianium** [comment]
Alright - everyone has been added in packagist with the exception of @andreasschroth and @michaelbutler (usernames weren't the same as github username - if you have a different account let me know 😄 )

I added everyone to the former `brianium/paratest` in packagist, as it seems to understand that redirect. Not sure if there is work to be done here to finish the transfer.

Some immediate tasks look like updating CI tasks - i.e travis, scrutinizer, packagist badge, etc..

Thanks a ton everyone!

**Comment by geggleto** [comment]
Let's coordinate work on discord?

**Comment by andreasschroth** [comment]
@brianium I just set up my Packagist account, same username as here.

**Comment by luispabon** [comment]
@brianium thank you so much for your hard work on paratest, and thank you also to whoever took it over 👍

**Comment by luispabon** [comment]
I have a PR to make for PHPUnit 7, is https://github.com/paratestphp/paratest now the right place?

**Comment by brianium** [comment]
@luispabon yes 👍 - I'm glad you have found this project useful 😄 

I'm going to close this issue for now because it looks like we are moving forward 😄 If there is anything else I can do to facilitate the transition - please mention me in discord.

Thanks everyone!
