### ISSUE TITLE
Travis integration

### ISSUE THREAD

**Issue by julianseeger** [paratestphp/paratest#300]
does not work since we moved to paratestphp/paratest

**Comment by andreasschroth** [comment]
As far as I can see, it works now again and you fixed it already?

https://travis-ci.org/paratestphp/paratest

So I guess we can close this issue?

**Comment by julianseeger** [comment]
The badge in the readme needs to be fixed and I'm still not sure if the PR-Integration works (waiting for proof). But you may close this issue anyways as we'll handle it "internally" ^^

**Comment by michaelgv** [comment]
pretty sure we've fixed this now? @julianseeger @andreasschroth

**Comment by andreasschroth** [comment]
Yes, it's fixed, thanks for closing.
