### ISSUE TITLE
Delete stale & merged branches

### ISSUE THREAD

**Issue by andreasschroth** [paratestphp/paratest#303]
I suggest that we delete stale & merged branches to keep the project clearer and so that only actively developed branches are kept.

Imo, after a PR got merged, we should directly delete the branch as well.

What do you think about it?

**Comment by andreasschroth** [comment]
Would be great to hear what other people think about my suggestion?

**Comment by geggleto** [comment]
deleting merged branches 👍 
stale branches, depends. If it fails too far back then yeah.

**Comment by geggleto** [comment]
Ideally we would not commit directly to the repo, instead fork and then open a cross-repo PR then we wouldn't need to deal with it at all! :)

**Comment by andreasschroth** [comment]
@geggleto Regarding forks and cross-repo PRs: True, I'd like that as well.

**Comment by andreasschroth** [comment]
I cleaned up with the branches. All merged ones deleted.
