### ISSUE TITLE
How to handle very old bug issues

### ISSUE THREAD

**Issue by andreasschroth** [paratestphp/paratest#304]
This question is regarding how we should handle very old bug issues. I saw some bug reports from 2014 and 2015 with no real activity or feedback going on.

My recommendation would be to check if we can verify the bug still in the latest version and if not, to close the issue. It can still be re-opened at a later time in case it's still existing.

What do you think about it?

**Comment by michaelgv** [comment]
I think we should investigate all old issues, any valid remaining we should create newer issues, and properly track them accordingly.
