### ISSUE TITLE
paratest hangs indefinitely in some cases

### ISSUE THREAD

**Issue by KarimGeiger** [paratestphp/paratest#310]
Hi there,

first up: Thanks for devoting so much time into parallelizing PHPUnit. It's saved us much time during deployments and we wouldn't want to miss it.

Sadly, we're experiencing some non-reproducible issues during some runs of paratest in which the process just hangs indefinitely after the last test. We tried debugging it using strace and found that it keeps looping through a `select()` syscall. The strace output starting it looks as follows:
```
4857  exit_group(0)                     = ?
4857  +++ exited with 0 +++
4852  <... select resumed> )            = ? ERESTARTNOHAND (To be restarted if no handler)
4852  --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=4857, si_uid=126003, si_status=0, si_utime=40230, si_stime=136} ---
4852  select(8, [7], [], [], {0, 823288}) = 0 (Timeout)
4852  select(8, [7], [], [], {1, 0})    = 0 (Timeout)
4852  select(8, [7], [], [], {1, 0})    = 0 (Timeout)
```
The last line then repeats every second until the end of time.

We tried following the program path and found that the error may occur in `WrapperRunner::waitForStreamsToChange()`, since this is where the `select()` syscall is being made. Our theory is that one worker quits without letting the parent know and then the parent thinks there is still one worker left, but we don't have enough insight in how paratest works to debug it any further. Maybe you can give us a hint or any guess on what might happen, so we can try to develop a fix.

Debug information:
* This can be reproduced on a Debian and CentOS VM, but not locally on macOS.
* Paratest hangs in about 1 in 4 runs.
* All machines have enough memory built in so they don't have to swap.
* We're running 447 tests with 2312 assertions in 4 processes on 4 cores with the `WrapperRunner` runner and no xdebug extension enabled.
* The error occurs on both PHP 7.1 and 7.2. Versions below that haven't been tested.
* We've been using paratest version 1.1 with PHPUnit 6 as well as the master branch with PHPUnit 7.

If you like, we can send you the strace output via email.

Thanks for your help!

**Comment by michaelbutler** [comment]
Thanks for this report! I also ran into some issues with using WrapperRunner where it would hang, so I think your findings are correct... WrapperRunner needs some work to have better handling of child processes especially in this case. As a workaround you can use the regular runner for now... though the performance benefits won't be as great since it has to spin up a new process for each test file.
Perhaps even a new runner could be written from the ground up that does inter-process communication in a different way.

**Comment by KarimGeiger** [comment]
Hi @michaelbutler,

thanks for the quick reply, really appreciated! We've now switched to the regular runner and haven't had any problems as of now, so that seems to work.

We were thinking about - if we can find the time - implementing an sqlite runner which acts more like a job queue. The idea was that the runner spawns workers and these workers proactively pick outstanding jobs from the sqlite queue until all are resolved. What do you think of that idea in regards to performance?

**Comment by michaelbutler** [comment]
@KarimGeiger I like that option... having an SQLite runner that first parses all the test info and then inserts into a queue, then spins up parallel processes that can read off that queue (as long as atomic transactions are guaranteed) would be a nice feature to have. As they're processing tasks, if the query returns 0 results (meaning queue is empty), they could then exit. or alternately wait a few seconds to see if any new jobs come along, then exit if nothing still.

However, does SQLite support that? being opened by multiple processes, all modifying the same data file?

**Comment by KarimGeiger** [comment]
It seems so, yes. It might not be perfectly fast, but it's worth testing, I think:
http://www.sqlite.org/faq.html#q5

We'll go ahead and try implementing it. We'll let you know if anything interesting happens.

Thanks again for your support!

**Comment by oojacoboo** [comment]
So, I was having this issue and ended up disabling xdebug for tests.  This fixed the issue for me, it seems.  I was having issues with paratest hanging after tests had actually completed, but wasn't printing out the error results.
