### ISSUE TITLE
 [RuntimeException]Log file /private/var/folders/p9/flwyfctj26s3t0hvh6vxqf3w0000gn/T/PT_KJvaCG is empty.

### ISSUE THREAD

**Issue by JiangYuf** [paratestphp/paratest#312]
➜  php vendor/bin/paratest --phpunit vendor/phpunit/phpunit/phpunit

Running phpunit in 5 processes with vendor/phpunit/phpunit/phpunit

Configuration read from /Users/jiangyufeng/work/xingse/release/server/php/phpunit.xml

  [RuntimeException]
  Log file /private/var/folders/p9/flwyfctj26s3t0hvh6vxqf3w0000gn/T/PT_KJvaCG is empty. This mean
  s a PHPUnit process has crashed.
  The process: 'vendor/phpunit/phpunit/phpunit' '--configuration' '/Users/jiangyufeng/work/xingse
  /release/server/php/phpunit.xml' '--log-junit' '/private/var/folders/p9/flwyfctj26s3t0hvh6vxqf3
  w0000gn/T/PT_KJvaCG' 'tests\DummyTest' '/Users/jiangyufeng/work/xingse/release/server/php/tests
  /DummyTest.php'
  This means a PHPUnit process was unable to run "/Users/jiangyufeng/work/xingse/release/server/p
  hp/tests/DummyTest.php"

paratest [-p|--processes PROCESSES] [-f|--functional] [--no-test-tokens] [-h|--help] [--coverage-clover COVERAGE-CLOVER] [--coverage-html COVERAGE-HTML] [--coverage-php COVERAGE-PHP] [-m|--max-batch-size MAX-BATCH-SIZE] [--filter FILTER] [--phpunit PHPUNIT] [--runner RUNNER] [--bootstrap BOOTSTRAP] [-c|--configuration CONFIGURATION] [-g|--group GROUP] [--exclude-group EXCLUDE-GROUP] [--stop-on-failure] [--log-junit LOG-JUNIT] [--colors] [--testsuite [TESTSUITE]] [--path PATH] [--] [<path>]

---------------------------------------------------
I can not run test

**Comment by andreasschroth** [comment]
Could you please provide us with more information about this, e.g. with the `DummyTest.php` file?

**Comment by michaelbutler** [comment]
Please implement a test listener so you can record what is happening. If your code contains exit statements, paratest currently has no way to know what happened or how it arrived at that exit statement... the process simply exits.

**Comment by andreasschroth** [comment]
Closing this due to no feedback.
