### ISSUE TITLE
Bump version for phpunit ^7.0 become compatible

### ISSUE THREAD

**Issue by maxgorovenko** [paratestphp/paratest#315]
Compatibility is already in master branch, so could you please make new release, to become this changes usable?

**Comment by alexkvak** [comment]
+1

**Comment by jetexe** [comment]
ping @andreasschroth

**Comment by andreasschroth** [comment]
@michaelbutler What is your opinion on that?

**Comment by michaelbutler** [comment]
That means we'll have to maintain different branches (one for phpunit 7, other for phpunit 6.5) correct? Or just update new features for phpunit 7 and essentially freeze older branch. Does that sound correct?

**Comment by maxgorovenko** [comment]
@michaelbutler you already have `"phpunit/phpunit": "^7.0"` in master branch. We need just a release to have ability to use it in our projects

**Comment by andreasschroth** [comment]
Hmm, imo, I'd just freeze old branch, not support it anymore with new features and just bump version of `paratest` to new major.

**Comment by michaelgv** [comment]
I think it’s time we just support the newer branch, and only provide minor releases as necessary for older branches

**Comment by andreasschroth** [comment]
Yeah, I agree, that's what I also meant...

**Comment by jstolp** [comment]
@maxgorovenko i'm currently using "dev-master" in my project with PHPUnit 7.x

**Comment by andreasschroth** [comment]
@michaelbutler @michaelgv Do you both agree that we should tag a new version? If yes, let's just do it, so devs can take advantage of PhpUnit 7.x support. ;) Having people rely on `dev-master`, imo, is nothing we should aim for.

**Comment by michaelbutler** [comment]
@andreasschroth are you familiar with doing that? I haven't updated Packagist yet but can research it tonight if needed

**Comment by andreasschroth** [comment]
Done, v2 released & updated on Packagist.

**Comment by jstolp** [comment]
Thanks guys
