### ISSUE TITLE
Memory/Performance Optimizations when running Magento Test Suite

### ISSUE THREAD

**Issue by michaelbutler** [paratestphp/paratest#319]
Opening an issue for myself to work on. There may be some performance enhancement opportunities, I found while debugging a run of the [Magento2](https://github.com/magento/magento2) test suite -- it's a pretty large suite that takes over 2 minutes to run in normal PHPUnit, so it's a good thing to test paratest against.

SuiteLoader (https://github.com/paratestphp/paratest/blob/master/src/Runners/PHPUnit/SuiteLoader.php#L60) has a number of array_merge calls inside foreach loops, which takes a lot of CPU overhead to continually do a new array merge operation. A way to fix is to simply append to an array list, and then after the foreach loop do one flatten operation.

Some other issues I noticed while running this... 

- Magento uses `<testsuite>` definition in the root level of their phpunit.xml.dist, instead of `<testsuites><testsuite>...`, so Paratest can't detect the tests.
- When running Magento test suite, the parent paratest process needs a LOT of memory, about 1024M. There might not be any good way around this due to the sheer number of classes there, but might be worth investigating.

**Comment by Slamdunk** [comment]
Hi, with the recent version of ParaTest I was able to run Magento suite, even though it needs a parallelization setup because some tests work on the same fixtures.

Feel free to reopen this if you re-encounter similar issues.
