### ISSUE TITLE
No info about risk tests

### ISSUE THREAD

**Issue by ahmedsamirtaj** [paratestphp/paratest#329]
if I have a risk test I just go that I have ones but I have no details about it like phpunit

**Comment by rask** [comment]
You mean paratest does not tell you what tests were risky? I'm having the same problem here. There is a `E` in the test run output, but paratest does not tell me where that happened, so I need to run basic PHPUnit to get the information.

**Comment by validaide-mark-bijl** [comment]
Hi,

Could this be a possible duplicate?
https://github.com/paratestphp/paratest/issues/282

Cheers,
Mark

**Comment by andreasschroth** [comment]
@validaide-mark-bijl Thanks, I agree, they seem to be basically the same. I added the risky test part to the title of the other issue and closing this one now.
