### ISSUE TITLE
Environment variables not being passed to child processes

### ISSUE THREAD

**Issue by cs278** [paratestphp/paratest#334]
I have a custom wrapper around PHP which allows me to select different versions and enable xdebug using environment variables, problem is these variables do not reach the child processes paratest creates. This seems to be caused by Symfony modifying `$_ENV` when `variables_order` does not include `E`, basically: https://github.com/brianium/habitat/issues/2

However now paratest requires PHP ≥ 7.1 can't it now just call `getenv()` and just work?

Possibly related to #103

**Comment by andreasschroth** [comment]
I'm not sure I understand your suggestion correctly. how should `getenv()` fix the underlying problem?

Could you please create a PR for it?
