### ISSUE TITLE
default number of processes should depend on system

### ISSUE THREAD

**Issue by Nemo64** [paratestphp/paratest#337]
Currently the number of processes spawned is simply 5. While this is better than 1 and it is an ok default, I think it could be better.

The default should depend on the number of logical cores on the system. I know that it isn't the easiest thing to detect but [there are libraries for that](https://packagist.org/packages/wyrihaximus/cpu-core-detector) and it could always fallback to 5.

If it can be detected, I'd argue that the number of processes should be `ceil(logicalProcessors() * 1.2)` since it is better to have a few processes more.
- 1 core = 2 processes
- 2 cores = 3 processes
- 4 cores = 5 processes
- 8 cores = 10 processes
- 10 cores = 12 processes

so on... I think this is a nice distribution... and of corse it is just a default so it can be changed if needed.

**Comment by andreasschroth** [comment]
Thanks, but there is always a PR open for that: #336 

Just the tests are not adjusted yet in the PR, but otherwise the PR is going to be merged.

**Comment by Nemo64** [comment]
Ohh, i only searched for issues, my bad 😅
