### ISSUE TITLE
New Releases

### ISSUE THREAD

**Issue by andreasschroth** [paratestphp/paratest#339]
My question to all collaborators and contributors would be, when should we release new versions? Whenever we feel like there are enough changes?

If yes, I would say after PR #336 gets merged, we should release a new version. v2.1?

What are your thoughts? @michaelbutler @michaelgv

**Comment by michaelgv** [comment]
Agreed, when necessary at our discretion, or in the event of a significant change. It may be worth a “next” stream to be released with all PRs merger, after N next builds we do a minor or major update?

**Comment by andreasschroth** [comment]
@michaelgv You mean a `next` branch? Hmm, I think `master` should always be the branch where new PRs and developments are merged into, as this is usually in most projects this way. Could you please describe the exact workflow you suggest?

**Comment by andreasschroth** [comment]
Alright, I just tagged version 2.1. Now we have a .phar as well. 😄

**Comment by andreasschroth** [comment]
I'll close this issue now.
