### ISSUE TITLE
php constants and etc. 

### ISSUE THREAD

**Issue by N3XT0R** [paratestphp/paratest#340]
Hello Guys,
when testing with phpunit.xml it seems there is a difference between the normal running of phpunit tests and with paratest.

I have in my project some environement vars and globals that i define in the phpunit.xml for testing reasons like database credentials and etc inside the <php> blog of the configuration:

`
    <php>
        
        <var name="DB_UNITTEST_USER" value="root"/>
        <var name="DB_UNITTEST_PASSWD" value="password"/>
        <var name="DB_UNITTEST_HOST" value="localhost"/>
        <var name="DB_UNITTEST_DBNAME" value="xxxxxx"/>
        
        <const name="PHPUNIT_TESTS" value="true"/>
        <ini name="memory_limit" value="128M"/>
        <ini name="xdebug.max_nesting_level" value="100"/>
        
        <server name="REMOTE_ADDR" value="127.0.0.1"/>
        <server name="HTTP_USER_AGENT" value="test"/>
        <server name="HTTPS" value="true"/>
        <server name="HTTP_ACCEPT_LANGUAGE" value="de"/>
        <server name="HTTP_ACCEPT_ENCODING" value="gzip, deflate, compress;q=0.9"/>
    </php>
`

it seems that this block of the phpunit.xml configuration is fully ignored on loading the configuration and all defined overwrites of superglobals, defines of constants or $GLOBAL defines are ignored. 

Also it seems like, that first the bootstrap.php will be loaded before the configuration is loaded:

`
ibeliaev@vilya-7:~/www/htdocs/xxx/intern/tests$ vendor/bin/paratest -c phpunit.xml
[.. many many errors....]
PHP Stack trace:/data/srv/htdocs/www/htdocs/xxx/intern/tests/vendor/brianium/paratest/src/Console/Testers/PHPUnit.php:196
PHP  13. bootstrap->run() /data/srv/htdocs/www/htdocs/xxx/intern/tests/bootstrap.php:108
PHP  14. bootstrap->init() /data/srv/htdocs/www/htdocs/xxx/intern/tests/bootstrap.php:102
PHP  15. require_once() /data/srv/htdocs/www/htdocs/xxx/intern/tests/bootstrap.php:77
PHP  16. AuConfig->__construct() /data/srv/alphaonline/www/htdocs/xxx/php/config.inc:3

Running phpunit in 5 processes with /data/srv/htdocs/www/htdocs/xxx/intern/tests/vendor/bin/phpunit

`
Normally phpunit load first the configuration with the php-block inside the configuration before it execute the bootstrap.php. 

Actually i am running phpunit in version 6.5 with paratest in version 1.1

**Comment by andreasschroth** [comment]
I understand, but unfortunately, we're not going to support the old branch anymore, sorry.

If you need to fix this, please try cherry-picking the commit from this PR: https://github.com/paratestphp/paratest/pull/318
