### ISSUE TITLE
Coverage does not report error for missing whitelist

### ISSUE THREAD

**Issue by Weysan** [paratestphp/paratest#346]
I was running test and trying the coverage test option. But always get a error thrown:
`Coverage file /tmp/CV_hI2eug is empty. This means a PHPUnit process has crashed.`

After few iteration of debugging, trying different configuration, etc, I had to try running phpunit directly and getting the error that I don't have whitelist configured.

That would be great to have better described errors to at least being able to debug more easily. My issue here is the description is wrong, PHPUnit didn't crashed.

**Comment by paslandau** [comment]
Hey @Weysan,
unfortuntately this is one of the "harder-to-change" parts of the codebase. For now, I added a better explanation of the general code coverage process under [docs/code-coverage.md](docs/code-coverage.md#troubleshooting) (when https://github.com/paratestphp/paratest/pull/362 gets merged).

I also added better debugging output via `--verbose=1` option. That wouldn't solve the whitelist-reporting issue but it makes it easier to copy-paster the underlying phpunit command to replicated the behaviour.
