### ISSUE TITLE
JUnit addSystemOut fails with warning when TestCase has multiple failures or errors

### ISSUE THREAD

**Issue by BHSPitMonkey** [paratestphp/paratest#352]
The following function attempts to process `<system-out>` from JUnit XML nodes produced by PHPUnit:

https://github.com/paratestphp/paratest/blob/87aa787eaf2f3d2d3baad14af50d18e277a56f6f/src/Logging/JUnit/TestCase.php#L129-L149

If the test case being processed contains more than one `<failure>` (or `<error>`), Paratest will throw out an ugly warning and stack trace during execution:

```
PHP Warning:  ParaTest\Logging\JUnit\TestCase::addSystemOut(): Cannot assign to an array of nodes (duplicate subnodes or attr detected) in /opt/hellofax/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php on line 141
PHP Stack trace:
PHP   1. {main}() /opt/hellofax/vendor/brianium/paratest/bin/paratest:0
PHP   2. ParaTest\Console\ParaTestApplication->run($input = *uninitialized*, $output = *uninitialized*) /opt/hellofax/vendor/brianium/paratest/bin/paratest:35
```

Additionally, the system-out text won't appear anywhere in the generated JUnit XML output.

There are a couple things going wrong here, but I think the main takeaway is that Paratest shouldn't even be trying to concatenate the system-out text into the content of the failure and error node (or nodes) like this at all. Instead, this function shouldn't exist and the `caseFromNode` should be ingesting the node's `system-out` value directly (because it's supposed to be a child of the `<testcase>`). This will probably require adding a new property to the `ParaTest\Logging\JUnit\TestCase` class and some code in the `Writer` class to handle rendering it to the finished XML.

**Comment by cuchac** [comment]
Hi, I'm experiencing the same error. Is there any workaround? I'm unable to switch to paratest. There seems to be no way how to detect where the problem comes from.

**Comment by Fedcomp** [comment]
wow, almost a year since it's opened. Facing same issue.

**Comment by cuchac** [comment]
Unfortunately this is showstopper and I can't use paratest :-( Did not find any workaround or what  triggers this error.

**Comment by Fedcomp** [comment]
And i got legacy project with it and can't see the errors.
`3.1.0` version appear to have same issue.

**Comment by Fedcomp** [comment]
```
<?php

class ParaTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @small
     */
    public function testTimeoutNotice()
    {
        sleep(10);
    }
}
```

This test case 100% reproduces the issue on my machine. If test is timed out it returns array of errors from phpunit.

Running in phpunit:
```
$ php vendor/bin/phpunit 
PHPUnit 8.4.3 by Sebastian Bergmann and contributors.

Runtime:       PHP 7.3.11
Configuration: /projects/paratest_case/phpunit.xml

R                                                                   1 / 1 (100%)R

Time: 1.03 seconds, Memory: 4.00 MB

There were 2 risky tests:

1) ParaTest::testTimeoutNotice
Execution aborted after 1 second

2) ParaTest::testTimeoutNotice
This test did not perform any assertions

/projects/paratest_case/test/paraTest.php:8

OK, but incomplete, skipped, or risky tests!
Tests: 1, Assertions: 0, Risky: 2.
```

Running in paratest:
```
$ php vendor/bin/paratest

Running phpunit in 8 processes with /home/sorenel/projects/paratest_case/vendor/phpunit/phpunit/phpunit

Configuration read from /home/sorenel/projects/paratest_case/phpunit.xml

PHP Warning:  ParaTest\Logging\JUnit\TestCase::addSystemOut(): Cannot assign to an array of nodes (duplicate subnodes or attr detected) in /home/sorenel/projects/paratest_case/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php on line 161
E

Time: 1.13 seconds, Memory: 4.00 MB

There were 2 errors:

1) Risky Test

2) Risky Test

FAILURES!
Tests: 1, Assertions: 0, Failures: 0, Errors: 2.
```

**Comment by Fedcomp** [comment]
I made a PR to fix it.

**Comment by Fedcomp** [comment]
@cuchac my fix was just merged and new version released. Could you confirm latest release solves this for you?

**Comment by cuchac** [comment]
@Fedcomp Hello, I can confirm it works like a charm. We were finally able to switch to paratest and I must say, the speed increase is awesome! :-) Thank you!

**Comment by Fedcomp** [comment]
@cuchac keep in mind - for risky tests paratest do not return description in junit format, not even filename afaik. But that's phpunit issue and they think about new tests format.
