### ISSUE TITLE
Dusk Support

### ISSUE THREAD

**Issue by clovenlife** [paratestphp/paratest#358]
Tried running this with our suite which has a large number of Dusk tests and while some did manage to pass, a lot return the following error
`Facebook\WebDriver\Exception\NoSuchDriverException: no such session
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.13.6 x86_64)`

I think multiple instances of chromium might be the issue. Maybe being able to force a function or class to use the first thread could be a possible solution

**Comment by clovenlife** [comment]
After installing the dev-master branch, I found the parallel-suite option allows the dusk tests to run fine. But splitting the remaining tests into suites arbitrarily is not the best experience for my team.

**Comment by neochief** [comment]
How do deal with the fact that all dusk instances use the same database (since they share the same .env file)?
