### ISSUE TITLE
Support for PHPunit 8

### ISSUE THREAD

**Issue by Tlapi** [paratestphp/paratest#365]

**Comment by Tlapi** [comment]
I have made some work here: https://github.com/paratestphp/paratest/pull/366

There are 3 functional tests failingm but I guess there won't be a problem for you ;-)

**Comment by andreasschroth** [comment]
Thank you. I merged your PR right now and thus close this issue.

**Comment by Tlapi** [comment]
@Tlapi Thank you. And now, how to tag this?

**Comment by andreasschroth** [comment]
@Tlapi I will tag a new version soon. :)

**Comment by andreasschroth** [comment]
New release tagged as `3.0.0`. Thank you again.
