### ISSUE TITLE
Idea: Synchronise paratest version numbers to phpunit version numbers

### ISSUE THREAD

**Issue by andreasschroth** [paratestphp/paratest#367]
What does everyone here think about synchronising the Paratest package version numbers to the ones of phpunit? E.g. v8 of Paratest will match to PHPUnit 8, etc.

Recently, there seems to be a lot of cleaning up going on within PhpUnit so I guess more breaking changes will come regarding the compatibility with Paratest. Any thoughts?

**Comment by andreasschroth** [comment]
Any more feedback besides one upvote and one downvote?

**Comment by michaelbutler** [comment]
I really think it's a good idea and we should do it!

**Comment by andreasschroth** [comment]
Won't do for now, we'll keep a list in the `README.md` which PhpUnit version matches which Paratest version.
