### ISSUE TITLE
Wrong number of tests

### ISSUE THREAD

**Issue by VincentClair** [paratestphp/paratest#369]
When executing paratest, test number and percentage are wrong and the final line as no number.
Here a result set:

```
rm -Rf var/cache/*; vendor/bin/paratest --colors --phpunit="bin/phpunit"

Running phpunit in 4 processes with bin/phpunit

Configuration read from /home/dev/api/phpunit.xml.dist

...............................................................  63 / 191 ( 32%)
............................................................... 126 / 242 ( 52%)
.........................WW.................................... 189 / 329 ( 57%)
............................................................... 252 / 329 ( 76%)
............................................................... 315 / 409 ( 77%)
............................................................... 378 / 436 ( 86%)
............................................................... 441 / 471 ( 93%)
............................................................... 504 / 575 ( 87%)
...........................................................EEEE 567 / 619 ( 91%)
.EEE.EEE..............................................

Time: 13.12 minutes, Memory: 8.00MB
```

I suspected that it is due to many used providers.
Thanks for your help

**Comment by VincentClair** [comment]
Just noticed, if I analysed correctly paratest code, results form each proc are analysed using regexp.

Is it interesting to replace it with something like a TestListener (--printer command option of phpunit) https://phpunit.readthedocs.io/en/8.0/extending-phpunit.html#extending-phpunit-examples-simpletestlistener-php ?

The idea is to open a socket/pipe (don't know the right word) by main paratest proc and each sub proc communicate with it through listener. Thanks to latter, the test is directly qualified (addError, addRiskyTest, etc.).
An other advantage is to allow to report directly to tty, without waiting the end of a ClassTest.

**Comment by slt** [comment]
#393 I've got a open pull request which will count the tests correctly.

The two things I've noticed/fixed are:
* Group filtering doesn't work properly if groups are on the classes instead of the methods
* Data providers were only used in functional mode, meaning they weren't counted correctly outside of functional mode

**Comment by VincentClair** [comment]
Seems the #402 does not fix this issue. Here a test suit run with 3.1 :

```
Configuration read from /app/symfony/phpunit.xml.dist

...............................................................  63 / 242 ( 26%)
............................................................... 126 / 242 ( 52%)
.....................................S......................... 189 / 243 ( 77%)
............................................................... 252 / 267 ( 94%)
................

Time: 55.62 seconds, Memory: 12.00 MB
```
