### ISSUE TITLE
Feature request: Stop after N failures

### ISSUE THREAD

**Issue by BHSPitMonkey** [paratestphp/paratest#381]
It would be great if `--stop-on-failure` could be extended to accept an arbitrary number of failures (rather than just stopping when the failure count has exceeded `1`). 

We use paratest in a project with a very large number of tests which takes a bit of time to finish, and sometimes a build contains a catastrophic change that causes most or all the tests to fail to an extent that letting the build continue is just a waste of time and resources in our CI queue. The ability to abort the run after some sane failure threshold has been reached would be helpful in these scenarios.

**Comment by Slamdunk** [comment]
I'm sorry but it is already tough enough to stay aligned with PHPUnit quick evolution and BC breaks, I'm not going to implement features that are not already available in PHPUnit.
