### ISSUE TITLE
coverage-text in file ?

### ISSUE THREAD

**Issue by CocoJr** [paratestphp/paratest#385]
Hi!

It's not possible to put the coverage in text format inside a file?  
  
Currently, i have the following error:  
`The "--coverage-text" option does not accept a value.`  
  
Thx.

**Comment by rask** [comment]
I'd also like to see summary as an option for the text format. I think the PHPUnit XML config is not respected and non-summary is printed anyways.

**Comment by graemlourens** [comment]
we're struggling as well currently to define --coverage-text but setting showOnlySummary to true, as with the amount of classes we have, the output is gigantic. It seems that whatever we try (even changing phpunit.xml) does not seems to work as it should. Any info if this is just not supported or any workaround to pass those options along with --coverage-text ?

**Comment by Slamdunk** [comment]
That's simply not supported right now, any PR is welcome
