### ISSUE TITLE
Warnings are not reported by para test

### ISSUE THREAD

**Issue by marcingy** [paratestphp/paratest#395]
I have warnings set up to be treated in failure, however when running latest version of para test I see output such as

`
.............................................................   61 / 2678 (  2%)

.............................................................  122 / 2678 (  4%)

.............................................................  183 / 2678 (  6%)

.............................................................  244 / 2680 (  9%)

.............................................................  305 / 2684 ( 11%)

.............................................................  366 / 2684 ( 13%)

.............................................................  427 / 2686 ( 15%)

.............................................................  488 / 2686 ( 18%)

.............................................................  549 / 2691 ( 20%)

.............................................................  610 / 2694 ( 22%)

.............................................................  671 / 2714 ( 24%)

.............................................................  732 / 2714 ( 26%)

.............................................................  793 / 2714 ( 29%)

.............................................................  854 / 2744 ( 31%)

.............................................................  915 / 2765 ( 33%)

.............................................................  976 / 2770 ( 35%)

............................................................. 1037 / 2783 ( 37%)

............................................................. 1098 / 2783 ( 39%)

............................................................. 1159 / 2785 ( 41%)

............................................................. 1220 / 2785 ( 43%)

............................................................. 1281 / 2785 ( 45%)

............................................................. 1342 / 2785 ( 48%)

............................................................. 1403 / 2789 ( 50%)

............................................................. 1464 / 2793 ( 52%)

............................................................. 1525 / 2793 ( 54%)

................................................S............ 1586 / 2794 ( 56%)

............................................................. 1647 / 2799 ( 58%)

............................................................. 1708 / 2808 ( 60%)

............................................................. 1769 / 2870 ( 61%)

............................................................. 1830 / 2870 ( 63%)

..................................S.......................... 1891 / 2894 ( 65%)

............................................................. 1952 / 2894 ( 67%)

............................................................. 2013 / 2905 ( 69%)

............................................................. 2074 / 2977 ( 69%)

............................................................. 2135 / 2977 ( 71%)

............................................................. 2196 / 2977 ( 73%)

............................................................. 2257 / 2981 ( 75%)

............................................................. 2318 / 2982 ( 77%)

.......................................................S..... 2379 / 2982 ( 79%)

............................................................. 2440 / 2985 ( 81%)

............................................................. 2501 / 2990 ( 83%)

............................................................. 2562 / 2999 ( 85%)

............................................................. 2623 / 2999 ( 87%)

............................................................. 2684 / 3003 ( 89%)

............................................................. 2745 / 3005 ( 91%)

............................................................. 2806 / 3030 ( 92%)

............................................................. 2867 / 3035 ( 94%)

............................................................. 2928 / 3037 ( 96%)

..........S.................................................. 2989 / 3037 ( 98%)

........................................................

FAILURES!

Tests: 3045, Assertions: 102809, Failures: 166, Errors: 0.

Makefile:38: recipe for target 'db_tests_ci_parallel' failed
`

But no information on what failed.

**Comment by slt** [comment]
I also noticed this recently, I think PHPUnit 8 throws a lot of new warnings for depreciated methods.  I had to run without paratest to figure out what was wrong.

**Comment by kiler129** [comment]
Reporting after spending 2 hours debugging invalid class in `@use`.

**Comment by ftzdomino** [comment]
It also seems to be failing to display incomplete tests in the progress output.

**Comment by andreasschroth** [comment]
Should be fixed by https://github.com/crzdeveloper/paratest/commit/5ee9e284fbc67f1775f1efde165c1ee918b4b5bb . Please feel free to create a new issue if it happens again.
