### ISSUE TITLE
coverage php out of memory

### ISSUE THREAD

**Issue by jesusslim** [paratestphp/paratest#401]
paratest version:0.14.0

vendor/bin/paratest --phpunit vendor/phpunit/phpunit/phpunit --coverage-php coverage_result.php

memory_limit 128M

it will cause PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) in /tmp/CV_8AgC5d in CoverageMerger , but if i remove --coverage-php,it works well,how can i solve this problem?

thx

**Comment by andreasschroth** [comment]
You can pass a specific `memory_limit` to the underlying PHP process, e.g. like this:

```--passthru-php="'-d' 'memory_limit=2G'"

**Comment by jesusslim** [comment]
> You can pass a specific `memory_limit` to the underlying PHP process, e.g. like this:
> 
> `--passthru-php="'-d' 'memory_limit=512M'"`

Thx,but my paratest version is 0.14.0,not support passthru-php.and i cant update to new version because composer dependency conflict. Now the unittest with coverage-php is very very slow and always out of memory.is there any other way to solve it?

**Comment by andreasschroth** [comment]
> > You can pass a specific `memory_limit` to the underlying PHP process, e.g. like this:
> > `--passthru-php="'-d' 'memory_limit=512M'"`
> 
> Thx,but my paratest version is 0.14.0,not support passthru-php.and i cant update to new version because composer dependency conflict. Now the unittest with coverage-php is very very slow and always out of memory.is there any other way to solve it?

Well, obviously you could apply the patch with this feature manually (see the matching PR), which I wouldn't recommend. Unfortunately, because this is a spare time project (and time is limited), I can't provide support for older versions.

I'm going to close this issue now, I definitely would recommend trying to update to the latest version.
