### ISSUE TITLE
Pretty testcase output

### ISSUE THREAD

**Issue by sksethi25** [paratestphp/paratest#408]
I was using [sempro/phpunit-pretty-print](https://github.com/sempro/phpunit-pretty-print) to beautify and readable output for the test case while they are running in Plain Phpunit.Phpunit required it to set printerClass in phpunit.xml. But with paratest, paratest is not utilizing the configrued printerclass from phpunit.xml.
 After going through paratest code, i found the paratest is using its custom ResultPrinter class.I want to know if there is some way either we can utilize  [sempro/phpunit-pretty-print](https://github.com/sempro/phpunit-pretty-print) or have proper readable progress in paratest.

Attaching phpunit-pretty-print sample output.
![pretyoutput](https://user-images.githubusercontent.com/6614662/68464015-cb90ad00-0235-11ea-9d92-0b402ce2e5a7.gif)

**Comment by robsontenorio** [comment]
@sksethi25 have you found a solution?

**Comment by sksethi25** [comment]
@robsontenorio  Nopes, the scale I was working on was not big so I end up avoiding the para test itself. Even i was facing some issues with in lumen framework with this.so had no choice.
