### ISSUE TITLE
Support PHP 5.6

### ISSUE THREAD

**Issue by kubawerlos** [paratestphp/paratest#409]
Hello,

can this library support PHP 5.6 in latest version? I'm trying to set it up [here](https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4635) with `0.15.`, but no luck yet.

This is the scenario that I believe can be quite common - having tests against multiple PHP versions and PHP 5 being much slower than PHP 7 ones.

**Comment by crabbly** [comment]
Probably not. The composer dependency is PHP 7.1.

I strongly recommend moving to a newer version. PHP 5.6 is no longer supported. You could end-up having bigger problems other than the speed of your automated tests.
https://www.php.net/supported-versions.php
Good luck.

**Comment by andreasschroth** [comment]
Well from what I understood at @kubawerlos tried to add Paratest to a library that still has compatibility for PHP 5.6.

Although I can understand the request of course and I agree it might be a good thing, I (and probably all other contributors) don't have resources to backporting fixes to older versions, sorry.

Thus, I'll close the issue.

**Comment by kubawerlos** [comment]
@crabbly ![co]

@andreasschroth sounds fair.

[co]: https://i.kym-cdn.com/photos/images/original/000/190/890/082.jpg
