### ISSUE TITLE
PCOV doesn't work with paratest? 

### ISSUE THREAD

**Issue by hgpull** [paratestphp/paratest#414]
I can’t understand if my configuration error or if pcov cannot be started with paratest.
I execute the command:

` /usr/bin/php -d memory_limit=2G -d pcov.enabled=1 -d pcov.directory=/srv/http/api.zp.ru/scripts/Job /srv/http/api.zp.ru/vendor/bin/phpunit -c /srv/http/api.zp.ru/tests/functional/phpunit.xml --coverage-text /srv/http/api.zp.ru/tests/functional/scripts/Job/Users`

and get result 

> Code Coverage Report:         
>   2019-11-24 14:16:14         
>                               
>  Summary:                     
>   Classes:  2.51% (46/1831)   
>   Methods:  7.02% (727/10361) 
>   Lines:    7.45% (4754/63852)

so, when run :

`/usr/bin/php -d memory_limit=2G -d pcov.enabled=1 -d pcov.directory=/srv/http/api.zp.ru/scripts/Job /srv/http/api.zp.ru/vendor/bin/paratest -p 4 -c /srv/http/api.zp.ru/tests/functional/phpunit.xml --coverage-text /srv/http/api.zp.ru/tests/functional/scripts/Job/Users `

we get zero result =( 

> Code Coverage Report:       
>   2019-11-24 14:18:38       
>                             
>  Summary:                   
>   Classes:  0.00% (0/1831)  
>   Methods:  0.00% (0/10362) 
>   Lines:    0.00% (0/110095)

Am I missing something?

**Comment by maxnk** [comment]
PCOV definitely works with paratest.
Check that you don't have coverage settings in phpunit.xml - I've got almost empty reports in that case. By "almost" I mean that the report contained coverage from the run of the last test only.

**Comment by hgpull** [comment]
oops
the wrong php ini settings were
