### ISSUE TITLE
Autoloading woes

### ISSUE THREAD

**Issue by oojacoboo** [paratestphp/paratest#416]
Honestly, I'm not even entirely sure where to start with this ticket.  We have a somewhat unusual testing setup I guess.  It works find with phpunit, but for some reason paratest doesn't seem to be handling the autoloading properly, as I continue to end up with a class not found error.

Any thoughts on where to start with debugging this?  The current command I'm executing looks like this:

```
docker exec -it --user www-data php /srv/www/vendor/bin/paratest \
--phpunit=/srv/www/vendor/phpunit/phpunit/phpunit \
--configuration=/srv/test/phpunit.xml  \
--stop-on-failure \
/srv/test/Integration
```

**Comment by oojacoboo** [comment]
Here is the exact error I receive:

```
Log file /tmp/PT_NUX9Cy is empty. This means a PHPUnit process has crashed.
  The process: /usr/local/bin/php '/srv/www/vendor/phpunit/phpunit/phpunit' '--configuration' '/srv/test/phpunit.xml' '--log-junit' '/tmp/PT_NUX9Cy' 'Test\Unit\Foo\Bar\Baz\BuilderTest' '/srv/test/Unit/src/Foo/Bar/Baz/BuilderTest.php'
  This means a PHPUnit process was unable to run "/srv/test/Unit/src/Foo/Bar/Baz/BuilderTest.php"
```

**Comment by TysonAndre** [comment]
Try invoking the exact command it mentioned in docker? If that doesn't give you a useful error message, I'm out of ideas.

```
docker exec -it --user www-data  /usr/local/bin/php '/srv/www/vendor/phpunit/phpunit/phpunit' '--configuration' '/srv/test/phpunit.xml' '--log-junit' '/tmp/PT_NUX9Cy' 'Test\Unit\Foo\Bar\Baz\BuilderTest' '/srv/test/Unit/src/Foo/Bar/Baz/BuilderTest.php'
```

**Comment by oojacoboo** [comment]
This issue has been resolved.  Frankly, I'm not sure, at this point what the exact issue was.
