### ISSUE TITLE
Deprecation of Symfony\Component\Process\Process::inheritEnvironmentVariables()

### ISSUE THREAD

**Issue by limenet** [paratestphp/paratest#417]
`symfony/process` deprecated its `Process::inheritEnvironmentVariables()` method in [4.4](https://github.com/symfony/process/blob/master/CHANGELOG.md#440) and removed it in [5.0](https://github.com/symfony/process/blob/master/CHANGELOG.md#500). The method in question is called in [`src/Runners/PHPUnit/ExecutableTest.php` on line 197](https://github.com/paratestphp/paratest/blob/master/src/Runners/PHPUnit/ExecutableTest.php#L195-L198).

I'm unaware of the implications of not calling the method as I came across this while running `./test` in [`phan/phan`](https://github.com/phan/phan) under PHP 7.4 which is why I didn't create a pull request to remove the method call and just wanted to alert you to this deprecation :)

**Comment by andreasschroth** [comment]
I believe this should be fixed by the merge of https://github.com/paratestphp/paratest/pull/410

Thus I'm closing this issue.
