### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by JulianaApolo** [paratestphp/paratest#418]
I'm having timeout message below. Is there any setting?

[Symfony\Component\Process\Exception\ProcessTimedOutException]                                
  The process "vendor/bin/paratest --coverage-text tests" exceeded the timeout of 300 seconds.

**Comment by andreasschroth** [comment]
Apologies for the late reply.

The timeout might come from composer (because you are calling vendor/bin/paratest). Please try setting an environment variable like this:

`export COMPOSER_PROCESS_TIMEOUT=1800`

I'm closing this issue now as I don't think this limit comes from Paratest itself.
