### ISSUE TITLE
WrapperRunner: conflict on PHPUnit 9 for already loaded classes

### ISSUE THREAD

**Issue by Slamdunk** [paratestphp/paratest#425]
See https://github.com/sebastianbergmann/phpunit/pull/4037

**Comment by Slamdunk** [comment]
So, it seems a refactor of `WrapperRunner` is needed:

1. https://github.com/sebastianbergmann/phpunit/pull/4037#issuecomment-584144345
1. https://github.com/sebastianbergmann/phpunit/issues/3387

Ping @andreasschroth

**Comment by andreasschroth** [comment]
Thanks for your effort @Slamdunk 

Yes, it seems so.

**Comment by Slamdunk** [comment]
Maybe we could create a dedicated [ResultPrinter](https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/ResultPrinter.php) in order to get a progress feedback, but leaving all the logic to a single PHPUnit run

**Comment by Slamdunk** [comment]
Note to the reader: this is an issue only if you call a test class from another test class. As long as this doesn't happen, PHPUnit 9 works fine on Paratest 4
