### ISSUE TITLE
Database instance per thread

### ISSUE THREAD

**Issue by oojacoboo** [paratestphp/paratest#427]
So, I'm looking to get paratest working with our integration test suites.  Currently, since we're using phpunit directly, we're only running one instance of mysql (docker container but all in-memory).

Since paratest will execute in parallel, there is obviously no way we can make use of the same database.  I was hoping for a little documentation or details on the best way to go about implementing this.  Would you just manually "checkout" a database instance, manage that state registration with `setUp` and `tearDown` and let that be it, or is there a better way of handling this?

I'd assume this is a fairly common issue for people and including some documentation on this subject, would be helpful.

**Comment by oojacoboo** [comment]
I was able to resolve this issue by using the `TEST_TOKEN` as a unique phpunit process identifier coupled with a database per process (ie. `database-1`, `database-2`, etc., where `TEST_TOKEN` = 1, 2, etc.)

**Comment by andreasschroth** [comment]
Ok great. 👍 

For future readers: Please also see README: https://github.com/paratestphp/paratest#test-token
