### ISSUE TITLE
Can't get TEST_TOKEN

### ISSUE THREAD

**Issue by oojacoboo** [paratestphp/paratest#429]
Can someone please tell me why I wouldn't be able to get the `TEST_TOKEN` within my env variables.  I've tried retrieving it in many places to no avail.  I'm using the following command.

```
/srv/www/vendor/bin/paratest -c /srv/test/phpunit.xml \
    --phpunit /srv/test/bin/phpunit-wrapper \
    --runner Runner \
    --processes 8 \
    --colors \
    $args
```

The `phpunit-wrapper` is a bit complex, but I'm not getting any ENV variables there, in the `bootstrap.php` which paratest appears to call itself and cache (another issue).

Any ideas?  I'm trying to get paratest setup with databases for integration testing, but I cannot find a reliable way to do so, at all - full stop.  Thanks.

**Comment by oojacoboo** [comment]
So, after much digging and inspection/debugging on our bootstrapping, it seems that paratest initially hits the bootstrap file for phpunit itself, then each phpunit worker hits it as well.  The initial hit by paratest does NOT result in any env variables being passed.  This caused major issues for us with bootstrapping, since our bootstrap initializes the database connection among other things dependent on that.

Now knowing this, I have a few questions.

1.  Why does paratest need to this this bootstrap file?  If it's not caching it, what's the point?  It'd be far better if this never happened.
2.  There is no reliable way to determine if the process executing the bootstrap file is of paratest or phpunit.  We're checking for the presence of the `TEST_TOKEN` which is semi-reliable, I guess.
3.  Documenting this behavior I'm sure would save many people a lot of headache down the road.

**Comment by Slamdunk** [comment]
Hi, requiring the bootstrap is essential to get the correct `@dataProvider` test cases, which may rely on it.

https://github.com/paratestphp/paratest/pull/498 also ensure `<php>` section of `phpunit.xml` gets loaded like PHPUnit does.

`TEST_TOKEN` should be a reliable way to test if it's Paratest or PHPUnit running, if it isn't you may reopen this issue.
