### ISSUE TITLE
Paratest hangs indefinitely with WrapperRunner and SqliteRunner

### ISSUE THREAD

**Issue by oojacoboo** [paratestphp/paratest#431]
Please see #310 as another reported case of this.  I'm unsure of why this was closed.

I've spent a little time digging further into this issue and I've identified what I think is the issue.  Paratest hangs after, what seems to be all tests, having completed.  Upon inspection, after the completion of these tests, it appears PHPUnit also has 3 processes still in the process queue with PID assignment.  The number of phpunit processes still left dangling and the number of errors reported in the paratest output are the same.

After debugging the phpunit-wrapper bin script, I've noticed that the `$lastExitCode` for the command `PHPUnit\TextUI\Command::main(false)` is `2` in all of these cases.  In these cases an Exception has been thrown.

It seems to me that, when Exceptions are being thrown and the exit status of phpunit within the `phpunit-wrapper` is not zero, that the processes aren't being handled properly.

I can manually add something like... 

```php
if ($lastExitCode != 0) {
    echo $infoText;
    exit($lastExitCode);
}
```

to the `phpunit-wrapper` within the while loop, but, this of course does not allow for the tests to complete before printing the error.  However, it's far better than having the paratest process hang indefinitely, never printing out any error details.

The funny thing is, if I alter the settings for phpunit.xml to not `stopOnError`, paratest never completes and ends up hanging much earlier in the process of tests.

Firstly, what is the preferred `phpunit.xml` config for paratest?  It doesn't seem that any configuration is entirely compatible.

And also, any insights into the process management for these `phpunit-wrapper` scripts?  If they're terminating with an exit code, how is paratest interpreting this?  It doesn't seem that the processes are exited in this case and if they are, paratest interprets this as a failure and exits itself.

**Comment by Slamdunk** [comment]
I've encountered myself this behaviour many time. Yes we need to better handle wrapper/sqlite runners errors.

**Comment by timglabisch** [comment]
we've the same issue. one worker seems to never stop running.

**Comment by Slamdunk** [comment]
Hi @timglabisch , have you tried the latest version of ParaTest, currently 5?
If yes, can you provide a minimal reproducible environment that replicate the issue?

**Comment by timglabisch** [comment]
@Slamdunk i am using ^3.1 - i'll try upgrading.

**Comment by timglabisch** [comment]
@Slamdunk seems that we've the same issue with with the latest version.
Sorry but i can't provide a minimal reproducible environment. 

it seems to depend on the order of the tests and i guess it is related to error output. we only ran into this issue when an error occurred.

**Comment by Slamdunk** [comment]
If you could debug it a bit and pinpoint some lines, I would try to investigate it further.

**Comment by timglabisch** [comment]
@Slamdunk i think i figured out the reason. the output pipe of the child process overflows and the child could not write more to the pipe. the child process simply blocks on a print but the parent process never reads the pipe.

i used an old paratest / phpunit version to test this but i guess it's the same for the current version.
the line numers are **wrong** because i added a lot of trace functions to find this issue.

trace where it hangs: 

```
#0 vendor/phpunit/phpunit/src/Util/Printer.php(125): paratest_trace()
#1 vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(384): PHPUnit\\Util\\Printer->write()
#2 vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(361): PHPUnit\\TextUI\\ResultPrinter->printDefectTrace()
#3 vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(347): PHPUnit\\TextUI\\ResultPrinter->printDefect()
#4 vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(403): PHPUnit\\TextUI\\ResultPrinter->printDefects()
#5 vendor/phpunit/phpunit/src/TextUI/ResultPrinter.php(170): PHPUnit\\TextUI\\ResultPrinter->printFailures()
#6 vendor/phpunit/phpunit/src/TextUI/TestRunner.php(645): PHPUnit\\TextUI\\ResultPrinter->printResult()
#7 vendor/phpunit/phpunit/src/TextUI/Command.php(208): PHPUnit\\TextUI\\TestRunner->doRun()
#8 vendor/phpunit/phpunit/src/TextUI/Command.php(159): PHPUnit\\TextUI\\Command->run()
#9 bin/phpunit_paratest_wrapper_without_xdebug.php(83): PHPUnit\\TextUI\\Command::main()
```

in the end in my case it hangs exacly here (PHPUnit\\Util\\Printer->write()):

<img width="1067" alt="Screen Shot 2020-08-27 at 15 18 05" src="https://user-images.githubusercontent.com/689269/91447646-34a2e900-e879-11ea-8d72-be719f8315c2.png">

i've to look at the paratest code, but i guess the solution is to consume the pipes.

**Comment by Slamdunk** [comment]
The default behavior of paratest is to wrap Phpuni execution between ob_start and ob_get_clean:
https://github.com/paratestphp/paratest/blob/5dc3a09668af9370678576d21455f2224cfb6c95/bin/phpunit-wrapper.php#L73
What you are telling me it's weird

**Comment by timglabisch** [comment]
@Slamdunk we have a slightly modified wrapper code.
In my case adding `$worker->updateStateFromAvailableOutput(); ` in the `waitForAllToFinish` solves my issue.
We may do nasty things with the output buffer in the tests.

i have to take a closer look at it to rule out that it is due to our test setup. but basically it would make sense to read out the output buffer of the children and i would like to see it displayed. 


```php
private function waitForAllToFinish(): void
    {
        do {
            foreach ($this->workers as $key => $worker) {
                if (!$worker->isRunning()) {
                    unset($this->workers[$key]);
                }
            }
            $worker->updateStateFromAvailableOutput(); // <<<<<<
            usleep(10000);
            $this->printOutput();
        } while (\count($this->workers) > 0);
    }
```

you may could try to print huge amount of data in tests.

**Comment by Slamdunk** [comment]
I have never liked the way `WrapperWorker` communicates with its child process via pipes and `\STDIN`, I wish to change it.

Nevertheless, still I can't figure out how calling `$worker->updateStateFromAvailableOutput();` could help...
More likely I would blame this:

https://github.com/paratestphp/paratest/blob/b2a16958fcb9adaad29af530d532c1e7eb436a7e/bin/phpunit-wrapper.php#L45-L57

if you call `fgets(\STDIN);` inside your tests, you mess up everything, I assume.

In the meantime I suggest you to use `SqliteWrapper`, is reliable as well.

**Comment by timglabisch** [comment]
@Slamdunk seems to be reproducible now, would you takeover the issue?

**Comment by Slamdunk** [comment]
I'll dig into it :+1:

**Comment by timglabisch** [comment]
@Slamdunk did you already worked on this issue?

**Comment by Slamdunk** [comment]
I'm on #526 which will some many issues, including this one
