### ISSUE TITLE
--group option does not filter out test classes with no @group annotation

### ISSUE THREAD

**Issue by ste93cry** [paratestphp/paratest#432]
PHPUnit has a `--group` option that allows to specify which group of tests should be run. While Paratest has the same option, it behaves differently: it does not filter out test classes that do not have the `@group` annotation. Taking as example the code below (one class per file), I would expect that only the second test class is executed using the command `vendor/bin/paratest --group=group1` while instead both are:

```php
class FooTest extends \PHPUnit\Framework\TestCaseTestCase
{
}

/**
 * @group group1
 */
class BarTest extends \PHPUnit\Framework\TestCaseTestCase
{
}
```

Instead running plain PHPUnit using the command `vendor/bin/phpunit --group=group1` works as expected. I tracked the error down to the `SuiteLoader::testMatchGroupOptions` method which returns `true` as long as no groups are defined on the test class. Even though I strongly believe that this is a bugfix, it also causes a huge BC. I'm willing to open PR to address the problem anyway, so let me know how we want to proceed

**Comment by Slamdunk** [comment]
Hi, a PR with the bugfix would be really appreciated. We'll take care of merging it according to an appropriate semver tag.
