### ISSUE TITLE
Support `--max-processes N` or `--processes '<=N'`?

### ISSUE THREAD

**Issue by TysonAndre** [paratestphp/paratest#435]
- On small VMs, there may be less than N processors, making running N tests concurrently inefficient (and running that many may possibly run out of memory)
- On build slaves, there may be more than N processors, but many different build jobs running at the same time, making running N tests make the performance of other jobs unpredictable.

I (or anyone) could submit a patch for either of those if there was interest - src/Runners/PHPUnit/Options.php would be changed.

```php
        if ($opts['processes'] === 'auto') {
            $opts['processes'] = self::getNumberOfCPUCores();
        } elseif ($opts['processes'] === 'half') {
            $opts['processes'] = \intdiv(self::getNumberOfCPUCores(), 2);
        }

        $this->processes = $opts['processes'];
```

**Comment by Slamdunk** [comment]
I'm sorry I don't get what you are asking for. `$opts['processes']` can already be set at a specific integer number, beside `auto` and `half`.

**Comment by TysonAndre** [comment]
For example, a reason I might want to use `--max-processes=8`
- on a VM with 2 CPUs, I'd want to only run 2 phpunit processes in parallel. `--processes=8` would start 8 processes, but I'd want `--max-processes=8` to start 2 instead of 8
- On a jenkins CI build server with 64 CPUs, it may be running dozens of jobs at once in the same gauntlet, and I'd only want to run 8 phpunit processes in parallel to avoid using too much memory and to make performance of other jobs predictable

Alternately, I can/have done this in bash to compute the desired process count before starting paratest (but that wouldn't work for Windows)
