### ISSUE TITLE
sometime success but sometime failed

### ISSUE THREAD

**Issue by chatchaisiwilai** [paratestphp/paratest#436]
I have a problem in same test function ( no code change ). I run 2 time for test but first are success, second are failed. In phpunit is all success. I use version "brianium/paratest": "^4.0".
Example error is `failed to open stream: No such file or directory`

----- first test -------
vendor/bin/paratest --filter=test_fund_loan -f -c phpunit.xml  tests/

Running phpunit in 4 processes with /home/vagrant/code/pp-app-v3/vendor/phpunit/phpunit/phpunit. Functional mode is ON.

Configuration read from /home/vagrant/code/pp-app-v3/phpunit.xml

.......

Time: 10.65 seconds, Memory: 34.00 MB

----- second test -----
`vendor/bin/paratest --filter=test_fund_loan -f -c phpunit.xml  tests/

Running phpunit in 4 processes with /home/vagrant/code/pp-app-v3/vendor/phpunit/phpunit/phpunit. Functional mode is ON.

Configuration read from /home/vagrant/code/pp-app-v3/phpunit.xml

.....F.

Time: 10.67 seconds, Memory: 34.00 MB
`

**Comment by oojacoboo** [comment]
Make sure that other tests aren't possibly changing the state of the environment.  We have issues with this were we have tests that have to clear the redis cache.  And, if there is another parallel test running at the same time, it can remove the cache while that test is running, causing an error.
