### ISSUE TITLE
Publishing a 4.0.1/4.1.0 release?

### ISSUE THREAD

**Issue by TysonAndre** [paratestphp/paratest#439]
https://github.com/paratestphp/paratest/commits/master has a few new changes since Februrary, such as

- Support for colors in output in feedback items
- Removing an unused dependency on an older version of composer/semver
- Avoiding calls to inheritEnvironmentVariables when it would emit E_USER_DEPRECATED

**Comment by Slamdunk** [comment]
@andreasschroth could we tag a new minor release, also because of #440 ?

**Comment by Zarthus** [comment]
ping @andreasschroth :)

**Comment by elijahchancey** [comment]
I'd love a new release because of #440. Thanks!

**Comment by andreasschroth** [comment]
I'd love to, but the builds on Travis are not running through on PHP 7.3 and I honestly don't really know why.
Must have something to do with the dependencies. :-/

**Comment by Zarthus** [comment]
I can take a look later this week hopefully.

**Comment by TysonAndre** [comment]
I think I may know why - Paratest might be failing with PHPUnit 9.2.5 (and other versions of 9), which only supports php 7.3+, which is why 7.3 fails? https://github.com/paratestphp/paratest/issues/446

**Comment by TysonAndre** [comment]
It's possible that it's because I stopped pinning composer/semver, which could have been holding other packages back as a side effect.

**Comment by TysonAndre** [comment]
The behavior seems to have changed between phpunit 9.1.0 and 9.2.0

**Comment by TysonAndre** [comment]
https://github.com/sebastianbergmann/phpunit/blob/9.1.5/ChangeLog-9.1.md

I suspect it's somehow related to https://github.com/sebastianbergmann/phpunit/issues/4232

> #4232: StandardTestSuiteLoader produces warning and does not run any tests if the test class name is partially similar to the parent test case name

**Comment by TysonAndre** [comment]
I think the tests would pass again if you switched from `_` to actual namespaces. Composer 2 will stop the generated autoloader from working for classes when there aren't proper namespaces - not 100% sure if that applies here.

**Comment by andreasschroth** [comment]
I'll close this issue in favor of https://github.com/paratestphp/paratest/issues/446 to have everything in one place.

**Comment by andreasschroth** [comment]
I just released a 4.1.0 version. But it only supports the latest PhpUnit version, sorry @TysonAndre .
