### ISSUE TITLE
Adopt strictier version policy and stick with latest PHPUnit version only

### ISSUE THREAD

**Issue by Slamdunk** [paratestphp/paratest#450]
Hi, the current README table which states that the corresponding ParaTest version to PHPUnit 9 is ParaTest 4 is bit of a lie, because the composer says `"phpunit/phpunit": "^7.5.8|^8.0|^9.0"`.

Also this forces us to test the lowest dependencies, leading to errors such https://travis-ci.org/github/paratestphp/paratest/jobs/706416438#L291 which could be easily ignored if we push users to adopt only the latest versions.

Here I propose (and would gladly make associated PR if accepted) to:

1. Support only the latest PHPUnit version with strict contraint
1. Tag a MAJOR ParaTest version for every MAJOR PHPUnit one (already done), EOLing previous ParaTest MAJOR (currently missing)
1. Tag a MINOR ParaTest version for every MINOR PHPUnit version that breaks anything in ParaTest - warnings included, EOLing previous ParaTest MINOR
1. Suggestion: for both cases, match PHPUnit and ParaTest version numbers

Benefits:

1. Drop multiple/EOL PHP version testing, we will require the same PHP version constraint as PHPUnit
1. Move the code forward quickly to match PHP and PHPUnit evolutions
1. Drop `DEPS=lowest` testing

Further suggestion:

1. Drop `PHPUNIT_DEV=true` testing: have you ever found it useful?

**Comment by andreasschroth** [comment]
Thank you for your efforts and your thoughts.

Regarding your suggestions:

1. I agree, that probably makes sense.
2. Makes sense as well.
3. Yes, agreed.
4. Probably also makes sense. The only problem is, what if some changes in Paratest require a new major version, because it's a BC break?

`PHPUNIT_DEV=true`... I find it useful, but should probably be allowed to fail.

**Comment by Slamdunk** [comment]
> Probably also makes sense. The only problem is, what if some changes in Paratest require a new major version, because it's a BC break?

You are right, better leave that suggestion off.

So, in #451 I've started addressing this, and dropping `DEPS=lowest` isn't feasible due to `"symfony/* "^3.4||^4.0||^5.0"`, but I've noticed that with this we are only testing `3.4` and `5.0`, but not `4.0`.
Moreover, most of this Symfony releases are already EOLed.

To ease the overall maintenance, I suggest to only support the two `Latest Stable Release` and `Latest Long-Term Support Release (previous MAJOR)` as reported by https://symfony.com/releases, currently `5.1` and `4.4`.

Considering the PHPUnit progress path of supported PHP versions (https://phpunit.de/supported-versions.html), this would end up into a total of max 6 builds, `3 PHP` * `2 Symfony`.

Spare time is precious, both Symfony and PHPUnit have chose a strict and fast pace, and we need this library (and our mind) healthy and updated.

What do you think?

Final point, If you do agree with this tightened policy, I propose myself to become a `Collaborator` for this library.

**Comment by TysonAndre** [comment]
Is this a blocker for https://github.com/paratestphp/paratest/issues/439 (Create a 4.0.1/4.1.0 release?). Other than releasing the changes that were made so far, I don't have objections to that plan

I'm stuck on phpunit ^8.5 and a minimum version of php 7.2 for some applications I work on, so it'd be useful to publish something supporting 8.0 (with the fixes that have been made so far, such as dropping the composer/semver constraint) before making the proposed change

> 1. Support only the latest PHPUnit version with strict contraint

**Comment by Slamdunk** [comment]
@TysonAndre I understand your needs, but maintaining software isn't free, even for free and open source libraries.

The more specific a software is, the less effort you'll find available for maintaining it.

PHP can support 3 versions of itself at time.
PHPUnit can support 2 versions of itself at time.
If I'd be a maintainer here, I could support only 1 version of this library at time.
