### ISSUE TITLE
Drop \ParaTest\Console\VersionProvider::getGitVersion support

### ISSUE THREAD

**Issue by Slamdunk** [paratestphp/paratest#456]
Hi, as far as I can tell, [\ParaTest\Console\VersionProvider::getGitVersion](https://github.com/paratestphp/paratest/blob/a9ca5977b3caf45e8c5956ffcd38d1e953b1421c/src/Console/VersionProvider.php#L43) is only used when Paratest runs itself and not installed from composer.

The scope is fairly limited, but brings dependency with the entire `git` history within the test.

I propose to drop that feature.

**Comment by Slamdunk** [comment]
This is failing the master now https://github.com/paratestphp/paratest/runs/918068269?check_suite_focus=true

**Comment by andreasschroth** [comment]
Agreed. Seems pointless, can be dropped.
