### ISSUE TITLE
Refactor internal v4 code with better OOP for easier maintenance

### ISSUE THREAD

**Issue by Slamdunk** [paratestphp/paratest#480]
Most of these are BC break so require a new major version:

- [x] Avoid magic like [`\ParaTest\Logging\MetaProvider::__call`](https://github.com/paratestphp/paratest/blob/4.1.0/src/Logging/MetaProvider.php#L37): very hard for automatic tools to inspect and for humans to maintain
- [x] Move known array structures to value objects, i.e. [`\ParaTest\Logging\JUnit\TestCase::$failures`](https://github.com/paratestphp/paratest/blob/4.1.0/src/Logging/JUnit/TestCase.php#L51), allow for better typehints
- [x] Make classes `abstract` or `final` without exceptions; helps for a better hierarchy classification, i.e. [`\ParaTest\Runners\PHPUnit\SqliteRunner`](https://github.com/paratestphp/paratest/blob/4.1.0/src/Runners/PHPUnit/SqliteRunner.php) should not extends `\ParaTest\Runners\PHPUnit\WrapperRunner`, but a separate abstract class should divide them; it shall not matter if one of the resulting class has no specific methods.
- [x] Make methods of abstract classes `final`: extending classes should not be allowed to overwrite the entire method, but only part of it, i.e. [`\ParaTest\Runners\PHPUnit\Worker\BaseWorker::start`](https://github.com/paratestphp/paratest/blob/4.1.0/src/Runners/PHPUnit/Worker/BaseWorker.php#L24) and https://slamdunk.github.io/blog/when-to-declare-methods-final/

**Comment by andreasschroth** [comment]
Yeah thanks, good points, I agree to all of them. 👍

**Comment by leeovery** [comment]
Hey,

`Make classes abstract or final without exceptions`

Is there an alternate way of overriding a runner now that they've all be marked as final?

I was extended WrapperRunner to add a little sugar for myself - this is now impossible.

Thanks
Lee

**Comment by Slamdunk** [comment]
Yes, by composition.

I'd love to hear what sugar your

**Comment by leeovery** [comment]
Ah ok cool. Ofcourse. I'll take a look over the weekend.

I use Laravel and have a system to make the tests run even quicker :)

1. Migrations are cached as a SQL dump (which is purged if anything changes in the migration dir).
2. A new database is created for each process that is spawned by/for ParaTest.
3. Each db is migrated (but its super quick due to the sqldump)
4. When ALL the processes are finished, then all the new DBs are dropped.

I use the Runner to hook into the run so that I can drop the DBs at the very end, and not while processes are still up and running.

Its been a while since I looked so there may will be a better way.

**Comment by Slamdunk** [comment]
We do the same, no need to code ParaTest for this, a simple PHPUnit listener is enough:

```php
final class DatabaseTestListener implements \PHPUnit\Framework\TestListener
{
    use \PHPUnit\Framework\TestListenerDefaultImplementation;
    
    private static bool $isDatabaseCreated = false;

    public function startTestSuite(\PHPUnit\Framework\TestSuite $suite): void
    {
        if (self::$isDatabaseCreated) {
            return;
        }
        
        (new DatabaseCreator())->create('my_database' . (string) getenv('TEST_TOKEN'));
        
        self::$isDatabaseCreated = true;
    }
}
```
The good this here is that is work on both ParaTest runs and raw PHPUnit run.
