### ISSUE TITLE
ParaTest fails if PHP is installed on path with spaces

### ISSUE THREAD

**Issue by arnovanoordt** [paratestphp/paratest#483]
I'm trying to run paratest on Windows 10 where my php installation resides inside a folder with spaces in it.
This causes paratest to fail.
Here is an excerpt of the output:

    Command: D:\Program Files\PHP7\php.exe D:\Projects\XXXXXX\development\www\vendor\phpunit\phpunit\phpunit --configuration D:\Projects\XXXXXX\development\www\phpunit.xml --log-junit C:\Users\XXXXXX\AppData\Local\Temp\PT_A068.tmp D:\Projects\XXXXXX\development\www\tests\Unit\App\SomeTest.php
    StdErr: 'D:\Program' is not recognized as an internal or external command, operable program or batch file.

For now I've moved my php installation, but would be nicer if the location of my php had no influence on the working of paratest.

**Comment by Slamdunk** [comment]
Sure there's a missing escape somewhere

**Comment by Slamdunk** [comment]
Solved in master, could you test it please?
