### ISSUE TITLE
Replace WrapperRunner and SqliteRunner with file-based processes communication to drop proc_open in favor of Symfony\Process

### ISSUE THREAD

**Issue by Slamdunk** [paratestphp/paratest#526]
Hi, WrapperRunner/SqliteRunner are the golden nugget of ParaTest: not having to kill and respawn sub-processes every test makes a huge performance difference on slow bootstrap environments.

The big issue is that they are not leveraging `Symfony\Process` component, which takes care of lot of bugs related to sub-process handling on both Linux and Windows.

SqliteRunner to me is the most well-coded, simple, easy to maintain and could easily be refactored to use `Symfony\Process`, but requires PDO and Sqlite, a big no-go to me for tools like ParaTest.

WrapperRunner suffers from depending on [`stream_select`](https://github.com/paratestphp/paratest/blob/b2a16958fcb9adaad29af530d532c1e7eb436a7e/src/Runners/PHPUnit/WrapperRunner.php#L115), which helps reducing some overheads and replace the slightly less inefficient `usleep` approach, but forbids us to use `Symfony\Process` (unless doing some nasty reflection stuff on internal attributes) and is not working on Windows.
Last but not least, pipes are a pain to handle, see https://github.com/paratestphp/paratest/issues/431

What I propose here is:

1. Drop SqliteRunner
1. Edit WrapperRunner + WrapperWorker to use `Symfony\Process`
1. Replace WrapperWorker communication with sup-process through pipes (see [`fwrite` here](https://github.com/paratestphp/paratest/blob/b2a16958fcb9adaad29af530d532c1e7eb436a7e/src/Runners/PHPUnit/Worker/WrapperWorker.php#L59) and [`fgets` here](https://github.com/paratestphp/paratest/blob/b2a16958fcb9adaad29af530d532c1e7eb436a7e/bin/phpunit-wrapper.php#L49)) with a file based one

Note that we already depend on the filesystem for logging (and code-coverage), so no new dependencies would be created.

This would (ideally) result in a WrapperRunner with a clean code (such SqliteRunner's one) and no more bugs related to sub-processes and pipes (up to ParaTest, I mean), at the cost of introducing `usleep` again as a wait system for the sub-process to end the current test, a technique already in place for Runner.
`stream_select` could in theory be adopted also for file streams, but `usleep` approach is far more easy to maintain clean in the long run.

Since I've spent the last month refactoring basically each line of the project, I'm a bit confident the proposed solution would work.
What I would like to ask you is what I cannot read from the code:

1. Has ParaTest ever tried such solution?
1. Do you see any blockers for this?

Ping:

1. Active admin: @andreasschroth 
1. Former lead developers: @brianium @julianseeger @giorgiosironi 
1. Notable contributors: @chbiel @timglabisch @michaelbutler @TysonAndre 
1. Persons which may be interested as well: @Jean85

**Comment by Jean85** [comment]
Thanks for the ping. I'm unfortunately unfamiliar with the internals of ParaTest to give an informed opinion, but I'm using `sleep` for Paraunit with no issues whatsoever: sleeping a couple hundreds of milliseconds is more than enough to feel "snappy" to the end user, and not hog the CPU at the same time. 

On the pipe side, I've chosen to avoid those completely: Paraunit parses the output at the end of the test execution, with a tradeoff for simplicity in exchange for less responsive output. But that can't work if you have some kind of reuse for the processes, but I don't know how you do it there.

**Comment by timglabisch** [comment]
I would recommend using Symfony/Process. Alternatively reactphp could be interesting here.
Communication with child processes is very ungrateful with php.
Some systems (I mean https://github.com/php-pm) even go there and start child processes but they handle internal communication via a socket. This has the advantage that internal communication and stdout can be separated well and a bidirectional channel is established. So interesting things would be possible.
usleep is annoying, but will probably not be a big problem in practice.

**Comment by andreasschroth** [comment]
No objections from my side, in fact I like the idea a lot.

And to answer the question: From what I know, this has never been tried.

**Comment by michaelbutler** [comment]
Sorry, I'm not able to contribute much to this project anymore due to not being able to use the latest PHPUnit versions on a daily basis. I'll always be stuck on old versions of paratest .
