### ISSUE TITLE
[Question] Database issues and OpenApi ActionTests

### ISSUE THREAD

**Issue by everton-nasc** [paratestphp/paratest#538]
Hey guys,
Just to give you an overview regarding my test suite, currently we've 3 different workers by test group to run:
* Unit tests (no issues with paratest)
* Integration tests (database issues and assertion issues)
* Http tests (OpenApi) - (http responses issues, e.g: 500, 403 and 401).
All of those I'm trying to setup paratest (mostly for Integration and Http - slower tests)

I've set the processes at `4` runners, using `WrapperRunner` and also I've modified my PDOTestCase in order to bind it with the runner Token:

```
if (getenv('TEST_TOKEN') !== false) {
            $db_paratest = 'paratest_db_test_' . getenv('TEST_TOKEN');
            self::$db = DbConnectionFactory::newConnection($db_paratest);
        } else {
            self::$db = DbConnectionFactory::newConnection('database_test');
        }
```

I've included the databases into the `ini` file like:
```
[paratest_db_test_1]
unix_socket = ''
datasource = Database/Mysql
host = 127.0.0.1
port = 3306
login = root
password =
database = paratest_db_test_1
encoding = utf8mb4

[paratest_db_test_2]
unix_socket = ''
datasource = Database/Mysql
host = 127.0.0.1
port = 3306
login = root
password =
database = paratest_db_test_2
encoding = utf8mb4

[paratest_db_test_3]
unix_socket = ''
datasource = Database/Mysql
host = 127.0.0.1
port = 3306
login = root
password =
database = paratest_db_test_3
encoding = utf8mb4

[paratest_db_test_4]
unix_socket = ''
datasource = Database/Mysql
host = 127.0.0.1
port = 3306
login = root
password =
database = paratest_db_test_4
encoding = utf8mb4
```

Note: We're currently using a specific file to get the database config based on the environment variable, in order to load the database config for: vagrant or CI.
Also this TestClass are getting rid of the database after each test (teardown and truncanteTables).

Here's some logs from OpenApi tests:
```
{
    "title": "Forbidden",
    "type": "https:\/\/httpstatus.es\/403",
    "status": 403,
    "detail": ""
}
Failed asserting that 403 is identical to 400.
```

```
{
    "exception": {
        "class": "ErrorException",
        "code": 0,
        "message": "Undefined index: REQUEST_URI",
        "file": "app\/Lib\/Auth\/XPTOAuthClass.php",
        "line": 54
    },
    "title": "Internal Server Error",
    "type": "https:\/\/httpstatus.es\/500",
    "status": 500,
    "detail": "Undefined index: REQUEST_URI"
}
Failed asserting that 500 is identical to 401.
```
Not 100% sure if the database vs token implementation it's right (haven't any proper documentation about it 😢 ).

Any thoughts will be very appreciated.
(note 2: due the company confidentiality policy, I have removed some logs and classes names).

Binary version:
Paratest: `2.2.0`
Phpunit: `7.5.20` 
php version: `7.3` and migrating to `7.4`

**Comment by Slamdunk** [comment]
Hi, you've given few configuration, but no error logs nor details about the way you accomplished the parallelization sandboxing, so we can't support in any way. You wrote "we have issues", but not what exactly the issues are.

> Paratest: `2.2.0`

We do only give support for the latest version, currently `5.0`
