### ISSUE TITLE
Paratest with pcov requires passing pcov.enabled=1 twice

### ISSUE THREAD

**Issue by Wojciechem** [paratestphp/paratest#558]
Hello, first of all - great tool, saves a ton of CI build time, thanks a lot!

To the issue:

This results in "No code coverage driver available":
```
vendor/bin/paratest --testsuite unit 
--coverage-clover some/path
--coverage-html some/path
--log-junit some/path 
--runner WrapperRunner
--passthru-php "'-d' 'pcov.enabled=1'"
```

This results in:  
"Coverage file /tmp/CV_kgBwp6 is empty. This means a PHPUnit process has crashed."
(-vvv does not give much more than that)

```
php -dpcov.enabled=1 vendor/bin/paratest --testsuite unit 
--coverage-clover some/path
--coverage-html some/path
--log-junit some/path 
--runner WrapperRunner
```
**However!**   
Works like a charm:
```
php -dpcov.enabled=1 vendor/bin/paratest --testsuite unit 
--coverage-clover some/path
--coverage-html some/path
--log-junit some/path 
--runner WrapperRunner
--passthru-php "'-d' 'pcov.enabled=1'"
```
Is this expected behaviour?  
Please let me know, maybe we can document somewhat collecting coverage with pcov?

**Comment by Slamdunk** [comment]
I can confirm that runtime-defined INI entries are **not** automatically passed thru sub-processes.

I agree that this may be confusing, but not that easy to implement cleanly, so we prefer to leave the exercise to the user.

A PR to integrate this knowledge into README.md would be very welcome though :+1:

**Comment by Slamdunk** [comment]
Doc has been updated accordingly https://github.com/paratestphp/paratest#pcov
