### ISSUE TITLE
Using test class constants in other test crashes

### ISSUE THREAD

**Issue by mfn** [paratestphp/paratest#568]
| Q | A
| --- | ---
| ParaTest version | 6.0.0
| PHPUnit version | 9.4.3
| PHP version | 7.4.13

#### Summary

After running for multiple minutes, the test suite crashes with the error:
> `Class 'SomeTest' could not be found in '/project/tests/Foo/Bar/SomeTest.php'.`

#### Current behavior

```
...........................................................  7552 / 13448 ( 56%)
................................................
In WorkerCrashedException.php line 36:

  The command "'/project/vendor/phpunit/phpunit/phpunit' '--configuration' '/project/phpunit.xml.dist' '--no-logging' '--no-coverage' '--printer' 'ParaTest\Runners\PHPUnit\Worker\Null
  PhpunitPrinter' '--log-junit' '/tmp/PT_6RduIW' '/project/tests/Foo/Bar/SomeTest.php'" failed.

  Exit Code: 1(General error)

  Working directory: /project

  Output:
  ================
  Class 'SomeTest' could not be found in '/project/tests/Foo/Bar/SomeTest.php'.


  Error Output:
  ================


paratest [--bootstrap BOOTSTRAP] [--colors] [-c|--configuration CONFIGURATION] [--coverage-clover COVERAGE-CLOVER] [--coverage-cobertura COVERAGE-COBERTURA] [--coverage-crap4j COVERAGE-CRAP4J] [--coverage-html COVERAGE-HTML] [--coverage-php COVERAGE-PHP] [--coverage-test-limit COVERAGE-TEST-LIMIT] [--coverage-text] [--coverage-xml COVERAGE-XML] [--exclude-group EXCLUDE-GROUP] [--filter FILTER] [-f|--functional] [-g|--group GROUP] [-h|--help] [--log-junit LOG-JUNIT] [--log-teamcity LOG-TEAMCITY] [-m|--max-batch-size MAX-BATCH-SIZE] [--no-test-tokens] [--order-by [ORDER-BY]] [--parallel-suite] [--passthru PASSTHRU] [--passthru-php PASSTHRU-PHP] [--path PATH] [-p|--processes PROCESSES] [--random-order-seed [RANDOM-ORDER-SEED]] [--runner RUNNER] [--stop-on-failure] [--testsuite TESTSUITE] [--tmp-dir TMP-DIR] [-v|--verbose VERBOSE] [--whitelist WHITELIST] [--] [<path>]


real	8m36.235s
user	7m2.184s
sys	1m43.281s
```

#### How to reproduce: command, code and error stack trace

This is the exact command:
`time vendor/bin/paratest -p 2 --runner WrapperRunner --passthru-php="'-d' '--update-snapshots'"`

#### Expected behavior

No crash.

## Analysis

- after I ran this command again, it crashed at the very same class so I figured it must be specifically related to the class
- I checked the naming convention, case-sensitive, `*Test` suffix in name and everything checks out;also it works correctly in phpunit and phpstan-strict-rules package which I additionally use to verify correctness does not report anything
- However I noticed this class uses `public const` a few times which are **referenced by other tests**
- I then replaced them with their literal value where used and ran the suite again
- It crash _in another test class_ this time, but this class _also used public const_ referenced from other test classes.
- I checked further classes in my test suite, found a couple more such occasions and temporarily replaced them with literal values
- After that, the suite did not crash again

I checked the issues but could not find anything, any idea what causes this?

**Comment by Slamdunk** [comment]
Hi, this issue is not related to ParaTest, but to PHPUnit, and refers on how it searches for autoloadable classes into test suite files.
If the test class with the constant is already autoloaded, when PHPUnit searches for it to run it as a test, it's missing, see https://github.com/sebastianbergmann/phpunit/blob/2709894c15c8fdda56bf2762af662a0e82ce59a7/src/Runner/TestSuiteLoader.php#L44

The workaround is easy though: put the constants in classes that are *not* test themselves.

**Comment by mfn** [comment]
That was quick 😱 

@Slamdunk fix seams reasonable, thank you. Is this a known issue? Because even if it's a phpunit issue, I never saw this problem exclusively with phpunit 🤷‍♀️ 

Thank you!

**Comment by Slamdunk** [comment]
Ok, what I told was not 100%. The bug is neither in ParaTest nor in PHPUnit, but rather in ParaTest while using WrapperRunner due to how PHPUnit searches classes. It's not easily and reliably fixable by ParaTest itself, hence the `wontfix` label.

I'd really appreciate if you can PR a README.md update creating a new `Caveats` section mentioning this issue&workaround :+1:

**Comment by mfn** [comment]
👍 created https://github.com/paratestphp/paratest/pull/569

**Comment by slt** [comment]
This is also happening if a test uses a static method from another test

**Comment by Slamdunk** [comment]
Yes, the readme must be updated: since it's and autoloading issue, it affect everything related to autoloading, constants, static methods, static attributes, reflection, etc
