### ISSUE TITLE
PHPUnit could not find test class

### ISSUE THREAD

**Issue by tarjei** [paratestphp/paratest#574]
Note: This is not as much a bug report as a way to document the solution to a problem I've been debugging so that others that hit the same issue might find it on the internets. 
| Q | A
| --- | ---
| ParaTest version | 4.0.0
| PHPUnit version | 7.5
| PHP version | 7.4

#### Summary
Paratest exited with a crashed worker and a stacktrace containg the following error:
```
 #message: 
 Class '/var/lib/jenkins/some/path/Foo/FooTest' could not be found in '/var/lib/jenkins/some/path/Foo/FooTest.php'
```
This error was hidden within an exception complaining that "The controller for URI "/some-uri" is not callable: The "kernel" service is synthetic, it needs to be set at boot time", but that message was irrelevant (but caused a lot of debugging).

After a lot of debugging (see https://github.com/paratestphp/paratest/issues/317#issuecomment-753653942) we found the problem.

Another testcase (BooTest) used a static variable fin FooTest that contained a string with a some testdata (a json fixture). This caused the test not be found by PHPUnit's `StandardTestSuiteLoader::load()` method because there was a mismatch between the output of `\class_exists($suiteClassName, false)` and  `\get_declared_classes()`.

#### Current behavior / solution

Do not reference a static variable in another testclass in your tests.

**Comment by Slamdunk** [comment]
Hi, this is already document: https://github.com/paratestphp/paratest#caveats

**Comment by tarjei** [comment]
@Slamdunk  duh! :) Good to know.
