### ISSUE TITLE
how to change phpunit printer

### ISSUE THREAD

**Issue by acidmk** [paratestphp/paratest#576]
As it's written in `Troubleshooting` readme section

```All internal commands run with --printer [...]\NullPhpunitPrinter which silence the original PHPUnit output: during a debugging run remove that option to restore the output and see what PHPUnit is doing.```

How is it possible to remove this option? So far I've tried to add `--passthru="'--printer' 'PHPUnit\TextUI\DefaultResultPrinter'"` and it doesn't replace the default one.

```Executing test via: '/usr/local/bin/php' '-d' 'memory_limit=16G' '/var/www/backend/vendor/phpunit/phpunit/phpunit' '--printer' 'PHPUnit\TextUI\DefaultResultPrinter' '--configuration' '/var/www/backend/phpunit.xml' '--no-logging' '--no-coverage' '--printer' 'ParaTest\Runners\PHPUnit\Worker\NullPhpunitPrinter' '--log-junit' '/tmp/PT_MLgemH'```

**Comment by Slamdunk** [comment]
Copy the command line input, remove the `--printer` part, and execute it directly in the CLI:

`'/usr/local/bin/php' '-d' 'memory_limit=16G' '/var/www/backend/vendor/phpunit/phpunit/phpunit' '--printer' 'PHPUnit\TextUI\DefaultResultPrinter' '--configuration' '/var/www/backend/phpunit.xml' '--no-logging' '--no-coverage' '--log-junit' '/tmp/PT_MLgemH'`

**Comment by acidmk** [comment]
But is it possible to change printer for the `paratest` underlying `phpunit` process ? I hope to make output more verbose with default `phpunit` printer. For instance laravel logs are mostly ignored during `paratest` run while they're shown in `phpunit`

**Comment by Slamdunk** [comment]
Not by options/flags, just comment the line:

https://github.com/paratestphp/paratest/blob/146456972129d69d2529a8842ce3413872c4334b/src/Runners/PHPUnit/ExecutableTest.php#L154

**Comment by mikeerickson** [comment]
@Slamdunk Commenting out this line does not help the situation.  Further, I have tried to use our own report write [Codedungeon PHPUnit Result Printer](https://packagist.org/packages/codedungeon/phpunit-result-printer) by hard coding

```php
paratest/src/Runners/PHPUnit/ExecutableTest.php

$options['printer'] = "Codedungeon\\PHPUnitPrettyResultPrinter\\Printer";

or

$options['printer'] = Codedungeon\PHPUnitPrettyResultPrinter\Printer::class;

```

but it still uses the PHPUnit default reporter.

**Comment by Slamdunk** [comment]
I haven't dug further the topic, but I don't see a point in it: the STDOUT and STDERR of sub-processes are never shown to the user if the process doesn't fail (the process, not the tests).

How can a pretty printer help you, if you don't see its output?

**Comment by mikeerickson** [comment]
So, are you saying that it won’t support defined printers, or that our desire to use a different printer is not warranted?

**Comment by Slamdunk** [comment]
I don't get where your question leads to.

Paratest runs tests into subprocesses, where output is discarded, and test results are logged only into JUnit format; then our [`ResultPrinter`](https://github.com/paratestphp/paratest/blob/master/src/Runners/PHPUnit/ResultPrinter.php) reads those JUnit logs and outputs something similar to what PHPUnit default printer does.

Note the our `ResultPrinter` has nothing to do with PHPUnit printers.

Any PR that abstracts `ResultPrinter` into something that third-party libraries can implement on their own, is welcome.

**Comment by mikeerickson** [comment]
Ok, now that makes perfect sense to me. As for creating a PR, if this is something you would accept (as your statement implies) I would be willing to work on

**Comment by nmeri17** [comment]
> Copy the command line input, remove the `--printer` part, and execute it directly in the CLI:
> 
> `'/usr/local/bin/php' '-d' 'memory_limit=16G' '/var/www/backend/vendor/phpunit/phpunit/phpunit' '--printer' 'PHPUnit\TextUI\DefaultResultPrinter' '--configuration' '/var/www/backend/phpunit.xml' '--no-logging' '--no-coverage' '--log-junit' '/tmp/PT_MLgemH'`

This doesn't work for me. Omitting the printer option complains about it missing. I can't pass null or an empty string to it. Commenting out that line like you suggested, or using phpunit's default printer either causes the test to run without paratest or the runner just dies without any output 

If I may ask, why does paratest hide the output in the first place? All var_dump are swallowed, so there's no way to tell why test is failing or whatever (except maybe writing to a file). The debug and verbose flags convey information about paratest, not my own test. So tests passing with regular phpunit but failing with paratest can't be debugged
