### ISSUE TITLE
PHPUnit's <server> element is ignored

### ISSUE THREAD

**Issue by wouterj** [paratestphp/paratest#582]
| Q | A
| --- | ---
| ParaTest version | 4.0.0
| PHPUnit version | 8.5.14
| PHP version | 7.4.14

#### Summary

PHPunit's configuration has a `<server>` element in `<php>`, allowing to set `$_SERVER` variables.

This is used in Symfony's default PHPUnit configuration, as `$_SERVER` has precedence over `$_ENV` in Symfony's DotEnv component (ref https://github.com/symfony/recipes/pull/561 ).

#### Current behavior

Paratest seems to not support the `<server>` element (`<env>` is supported).

#### How to reproduce: command, code and error stack trace

I'm currently trying to get paratest working with Symfony in: https://github.com/wouterj/symfony-demo/tree/paratest (`vendor/bin/paratest`)

However, any small project with a `<server>` set in the configuration should be able to reproduce this.

#### Expected behavior

Set the `$_SERVER` variable with the provided value.

While doing so, it might also be a good idea to add support for all other `<php>` configuration:
- https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/XmlConfiguration/PHP/Php.php
- https://github.com/sebastianbergmann/phpunit/blob/master/src/TextUI/XmlConfiguration/PHP/PhpHandler.php

**Comment by Slamdunk** [comment]
Already solved in https://github.com/paratestphp/paratest/pull/498 please use Paratest >= v5

**Comment by wouterj** [comment]
Oh, I'm sorry. I had the impression that I was on the latest version (but I now discovered a low php platform requirement in my `composer.json`).

Thanks for your quick response!
