### ISSUE TITLE
Initial seeding once, and parallel testing, is it incompatible ?

### ISSUE THREAD

**Issue by xoco70** [paratestphp/paratest#588]
| Q | A
| --- | ---
| ParaTest version | 6.2.0
| PHPUnit version | 9.5.1
| PHP version | 8.0.1

#### Summary
How should I manage initial seeding of my tests

#### Current behavior

As I use [laravel permissions](https://spatie.be/docs/laravel-permission/v4/introduction), I can't use in-memory test, because I have 105 permissions that I must seed for every tests, and it takes a while to do it.

So, what I do is an initial seeding of a Postgres DB, and then run all my tests against it. I get my 113 tests done in 1min7sec.

But trying to use paralel testing, all tests are failing, because it want to duplicate a table that already exists, or the opposite, the table doesn't exists.

Here's the script I use for initial seeding:

```php
public function setUp() :void
    {
        parent::setUp();
        if (!static::$setUpHasRunOnce) {
            Artisan::call('migrate:fresh');
            $this->seed('SourceTableSeeder');
            $this->seed('RoleTableSeeder');
            $this->seed('PermissionTableSeeder'); // This one is very slow if in-memory DB

            $this->seed('RepartitionTableSeeder'); 
            $this->company = Company::factory()->create();
            $this->operation = Operation::factory()->create(['company_id' => 1]);
            $this->user = User::factory()->create(
                [
                    'email' => 'julien@sun.fr',
                    'company_id' => 1, 
                    'operation_id' => 1, 
                ]);
            $this->user->assignRole(User::SUPER_ADMIN);
            static::$setUpHasRunOnce = true;
        }
        $this->company = Company::find(1);
        $this->user = User::find(1);
        $this->operation = Operation::find(1);
        $this->actingAs($this->user);

    }
```

How am I supposed to manage this use case with parallel testing ?

**Comment by Slamdunk** [comment]
Hi, this topic is specific to Laravel and not to Paratest, please open an issue on that project.
