### ISSUE TITLE
Coverage Report crashes in Linux environment

### ISSUE THREAD

**Issue by am-ma** [paratestphp/paratest#592]
| Q | A
| --- | ---
| ParaTest version | 6.2.0
| PHPUnit version | 9.5.2
| PHP version | 7.3.25

*Environment*
- CentOS 7.5 / Linux 5.4.39 on docker

#### Summary

The output process of the Coverage Report fails in the middle.
And, a garbled string will be output.

#### Current behavior

like this.
```sh
Running phpunit in 10 processes with /var/www/vendor/phpunit/phpunit/phpunit

Configuration read from /var/www/phpunit.xml


......㰿灨瀊牥 /* skip */


In CoverageMerger.php line 33:

  Argument 1 passed to ParaTest\Coverage\CoverageMerger::addCoverage() must be an instance of SebastianBergmann\CodeCoverage\CodeCoverage, int given, called in /var/www/vendor/brianium/paratest/src/Cov
  erage/CoverageMerger.php on line 71
```

#### How to reproduce: command, code and error stack trace

In the environment described above, execute a command like this.
```sh
$ phpdbg -qrr vendor/bin/paratest -p 10 --coverage-html './coverage/php'
```

#### Expected behavior

The Coverage Report will be output.

##### Additional Information

The error seems to be occurring in the following.
https://github.com/paratestphp/paratest/blob/997e611f296a71c82169282f38c4804e61f19424/src/Coverage/CoverageMerger.php#L63-L64

It seems that the loaded php coverage file is judged as 'ACII' format, so the include fails and becomes garbled.

**Comment by am-ma** [comment]
How can I fix it?
Please help me.

**Comment by Slamdunk** [comment]
It's hard for me to inspect this from the outside: may you reproduce a complete repo that shows this behavior, without any sensitive data in it?

**Comment by am-ma** [comment]
> reproduce a complete repo that shows this behavior, without any sensitive data in it

OK, I'll try.
(But it might be hard for me too)
