### ISSUE TITLE
Does ParaTest have a way to mark tests as non-parallelisable?

### ISSUE THREAD

**Issue by halfer** [paratestphp/paratest#593]
I am running ParaTest with Symfony Panther to drive a ChromeDriver stack. It is working very well so far.

One piece of my testing journey is testing against a third-party site, which redirects back to my app on our staging server. I suspect that the third-party site operates some denial of service protection, and so does not take well to 8-12 processes hitting it from the one IP address.

I was wondering if I could mark the test as `@donotparallelise` or something, so that those tests are done sequentially at the start or the end of the tests. Indeed, this feature may already exist and I haven't seen it in the docs.

If I were to do this, I would just use PhpUnit groups or suites to run parallelisable and non-parallelisable tests as separate chunks, and then merge the JUnit XML output using SimpleXML afterwards. But is there a better way?

**Comment by Slamdunk** [comment]
No such feature yet, but easy with groups:

```
& vendor/bin/paratest --exclude-group donotparallelise \
    && vendor/bin/phpunit --group donotparallelise
```

**Comment by jonhinks** [comment]
Good shout, @Slamdunk - thanks. In each case I'd be creating JUnit report output, and my initial worry was that CircleCI would need to have the XML files amalgamated in order to produce a report. In fact, it takes a target XML _folder_, and not a file, so I think it will do the merging itself!

https://circleci.com/docs/2.0/configuration-reference/#store_artifacts

**Comment by halfer** [comment]
Good shout, @Slamdunk - thanks. In each case I'd be creating JUnit report output, and my initial worry was that CircleCI would need to have the XML files amalgamated in order to produce a report. In fact, it takes a target XML _folder_, and not a file, so I think it will do the merging itself!

https://circleci.com/docs/2.0/configuration-reference/#store_artifacts
