### ISSUE TITLE
phar is missing from recent releases

### ISSUE THREAD

**Issue by jakzal** [paratestphp/paratest#598]
| Q | A
| --- | ---
| ParaTest version | >5.0.4
| PHPUnit version | -
| PHP version | -

#### Summary

The latest release with published phar is 5.0.4.

**Comment by Slamdunk** [comment]
Hi, PHAR release has been dropped since it has no meaning in the context of this very tool.

**Comment by jakzal** [comment]
What do you mean y "it has no meaning"?

**Comment by Slamdunk** [comment]
Paratest needs the PHPUnit binary to run the sub-processes, the exact one the user chose to include in its `composer.json`, we can't embed it

**Comment by tPl0ch** [comment]
Sorry, but it wouldn't be hard to make this configurable, right? We could just pass the binary from the composer path as an argument, or am I missing something?

Why? We can't install paratest currently through composer due to the fixed versions of `symfony/console`and `symfony/process`. We are still running Symfony 5.4 LTS, and, since we recently switched from PHPUnit 9 to 10, it becomes uninstallable due to the version constraints.

**Comment by Slamdunk** [comment]
It is two orders of magnitude easier and quicker for you to upgrade `symfony/console` and `symfony/process` from 5.4 to 6.0 then for us to provide a comprehensive and reliable PHAR solution and to maintain it for the rest of our lives.

**Comment by tPl0ch** [comment]
@Slamdunk that's a pretty bold assumption. I disagree that migrating a multi-million LOC code base to a new major framework version is two orders of magnitude easier than maintaining a phar building CI job (which is a solved problem, just look at hundreds of other libraries doing it).

**Comment by Slamdunk** [comment]
Symfony did a decent good job at creating self-contained packages. You can keep the framework components at version `5.4` while upgrading `console` and `process` ones:

1. `console` has only one cross-dependency pinned with both versions supported (https://github.com/symfony/console/blob/6.3/composer.json#L23)
2. `process` has no dependency at all (https://github.com/symfony/process/blob/6.3/composer.json#L18-L20)

Regarding the PHAR, the fact that is a solved problem doesn't wipe out that is a tricky and exhausting one.

**Comment by Jean85** [comment]
Also, big difference: you're probably paid to migrate that multi-million LOC codebase. 

We're not.
