### ISSUE TITLE
Incomplete/Skipped Tests are ignored

### ISSUE THREAD

**Issue by dbaltas** [paratestphp/paratest#60]
Incomplete/Skipped tests are not accounted for.
For example if you have 450 regular tests and 50 incomplete or skipped for a total of 500, you are expected to see the progress bar going 63/500, 126/500, where the 126 are the regular ones only.
So the progress bar will stop before 100% at 450 and in the end you will see 
OK (450 tests, X assertions)

**Comment by sormy** [comment]
this problem fixed in the master

**Comment by julianseeger** [comment]
Seems like there is a release missing. ... -> 0.12.2

**Comment by TysonAndre** [comment]
PHPUnit 6 adds the test names for `skipped` and `incomplete` to the XML output. However, paratest doesn't yet, even in the planned 1.x/0.16 release supporting phpunit 6.

A followup task for https://github.com/brianium/paratest/pull/237  would be to output (in CLI mode) the classes and names of tests that were skipped

**Comment by Slamdunk** [comment]
To me this seems fixed in the latest version, currently `4.1.0`

**Comment by TysonAndre** [comment]
Same - I'm no longer seeing this issue in newer phpunit versions, and phpunit 6 support was dropped long ago. Totals are the same with phpunit/paratest
