### ISSUE TITLE
How i can output teamcity metadata(additional teamcity service messages)?

### ISSUE THREAD

**Issue by lirik44** [paratestphp/paratest#604]
How i can output teamcity metadata(additional teamcity service messages)?
Link to documentation [here](https://www.jetbrains.com/help/teamcity/reporting-test-metadata.html).
I write this code in tearDown section and its work well in phpunit:
`    public function tearDown():void

    {
        if ($this->hasFailed()) {
            //Get test name
            $nameOfTest=$this->getName();
            //Get fail time
            $currenttime = date('Y_m_d_H_i_s', time());
            //Screenshot name
            $strerrorTC=$nameOfTest."_".$currenttime."_.png";
            //Get screenshot
            $this->webDriver->takeScreenshot("$dirLinux//$strerrorTC");
            //Additional teamcity service message 1
            fwrite(STDOUT,"\r\n##teamcity[publishArtifacts './report/screenshots/$strerrorTC => ./screenshots']\r\n");
            //Additional teamcity service message 2
            fwrite(STDOUT,"\r\n##teamcity[testMetadata testName='$nameOfTest' type='image' value='./screenshots/$strerrorTC' name='Screenshot']\r\n");
        }
        parent::tearDown();
        $this->webDriver->quit();
    }`

When i'm using Paratest i cant output my custom service messages because of STDOUT and STDERR blocked by paratest.
Option 
`--log-teamcity php://stdout`
 works well, but it not provide extra metadata messages

**Comment by Slamdunk** [comment]
Hi, `STDOUT` & `STDERR` are not supported by ParaTest as an interaction tool, and won't be because they are needed to be handled in a particular way to get things working.
