### ISSUE TITLE
Trying to pass options to phpuint via -d

### ISSUE THREAD

**Issue by mathieutu** [paratestphp/paratest#607]
| Q | A
| --- | ---
| ParaTest version | 6.2.0
| PHPUnit version | 9.5.4
| PHP version | 8.0.3

#### Summary

Hi,

Trying to make the equivalent of `phpunit -d --without-creating-snapshots` from https://github.com/spatie/phpunit-snapshot-assertions

#### Current behavior

The option is not taken in account.

It's checked with:

```php
!in_array('--without-creating-snapshots', $_SERVER['argv'], true);
```

I've tried with ` --passthru-php="'-d' '--without-creating-snapshots'" ` and ` --passthru="'-d' '--without-creating-snapshots'" ` without success, `$_SERVER['argv']` is equal to:

```
array:3 [                                                                                                                                                                  
    0 => "/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php"                                                                     
    1 => "--write-to"                                                                                                                                                        
    2 => "/var/folders/sy/mt42fvjx1rv4lw1895lcfl9w0000gn/T/worker_3_stdout_6078b20aad8c5"                                                                                    
  ]  
```

Am I doing anything wrong?

Thanks.

**Comment by Slamdunk** [comment]
In Paratest the command is passed to PHPUnit directly, not through `$_SERVER` var:

https://github.com/paratestphp/paratest/blob/82d50dadbc357bc6a24c0a69710b6cae004017d5/bin/phpunit-wrapper.php#L41-L42

I see you are leveraging a non orthodox way to get an option to the PHPUnit extension: the `-d` should be reserved for `php.ini` settings.

Yes it would be possible to have `$_SERVER` working on Paratest too, but I suggest you to ask/PR https://github.com/spatie/phpunit-snapshot-assertions to move away from `$_SERVER['argv']` and rely on environment variables: they are widely used for this purpose (custom flags) and already supported both into `phpunit.xml` configuration and one-time runs.

**Comment by mathieutu** [comment]
Ok thanks, I'll see what we can do with them.
