### ISSUE TITLE
QUESTION: Parallel testing with PostgreSQL database. Is it possible?

### ISSUE THREAD

**Issue by aibarra11** [paratestphp/paratest#611]
Is there a combination of settings to have each execution go through a class/file of tests/methods, and once that thread/execution finishes it moves on to another class/file of tests?

**Situation?** I need to test using PostgresSQL ( i have custom migrations for views and functions). I used the ENV_TOKEN and setup additional databases, and Refresh Database trait. 
I execute a migrate:fresh in the setUp method.
But of course, things are tripping over each other and tests are failing, because the database they're using has been re-migrated, so i have missing table errors popping up somewhat randomly. everything works fine in a regular phpunit test. 
Also the tests are independent of each other, although i was looking for ways to have a sort of "initial state" at the start of each class. that feels like a bonus at this point.

Thanks!

**Comment by mfn** [comment]
> migrate:fresh

This leads me to believe you're using Laravel and should target the question there, as the framework does all the heavy lifting supporting the various scenarios as part of the framework.

**Comment by Slamdunk** [comment]
Indeed, you should ask this to Laravel community

**Comment by aibarra11** [comment]
ah alright, i'll ask there. I thought here was the appropriate place, since i'm not using laravel 8 (which seems to pull this in as a dependency) i'm currently stuck with laravel 7 (due to other package's updates) and have added this package in manually
