### ISSUE TITLE
Using the `default` group has no effect - zero tests executed

### ISSUE THREAD

**Issue by maks-rafalko** [paratestphp/paratest#622]
| Q | A
| --- | ---
| ParaTest version | 6.3.0
| PHPUnit version | 9.5.4
| PHP version | 8.0.8

#### Summary

Running `paratest --group=default` executes 0 tests, while running `phpunit --group=default` executes all the tests, not explicitly marked with the group

#### Current behavior

Paratest filters out all the test cases where `@group` annotation is absent when `--filter=default` is used

#### How to reproduce: command, code and error stack trace

`paratest --filter=default` - 0 tests executed

#### Expected behavior

All the tests without `@group` explicit annotation, or tests in the classes without explicit `@group` annotation as well as `@small`, `@medium`, `@large` annotations should be executed when `paratest --group=default` is used, just like PHPUnit does it

If you run `phpunit --list-groups` on a fresh project, it will always output the following:

```
vendor/bin/phpunit --list-groups
PHPUnit 9.5.6 by Sebastian Bergmann and contributors.

Available test group(s):
 - default
```

#### Workaround

As a workaround, I can list all the existing groups **except** default and use `--exclude-group`

**Comment by Slamdunk** [comment]
> as well as `@small`, `@medium`, `@large` annotations should be executed when `paratest --group=default` is used, just like PHPUnit does it

AFAICT, that's not the case:

```php
final class GroupDefaultTest extends TestCase
{
    /**
     * @small
     */
    public function testTruth(): void
    {
        $this->assertTrue(true);
    }

    /**
     * @group group1
     */
    public function testFalsehood(): void
    {
        $this->assertFalse(false);
    }
}
```

```console
$ vendor/bin/phpunit --group default test/fixtures/group_default/GroupDefaultTest.php
PHPUnit 9.5.8 by Sebastian Bergmann and contributors.

No tests executed!
```

**Comment by maks-rafalko** [comment]
Thank you

> AFAICT, that's not the case:

hm, seems like I missed "not" in my sentence. Indeed, `@small` is just an alias of `@groups small`, so it should not be executed when `--group=default` is used.

Thank you for the fix!
