### ISSUE TITLE
[JUnit/Writer] JUnit report not found in nonexistent directory

### ISSUE THREAD

**Issue by raneomik** [paratestphp/paratest#629]
| Q | A
| --- | ---
| ParaTest version | 6.3.1
| PHPUnit version | 9.5.8
| PHP version | 8.0.9

#### Summary
It seems the JUnit writer cannot create a report in a nonexistent directory.

#### Current behavior & How to reproduce: (command, code and error stack trace)
for example when running tests like this :

```
XDEBUG_MODE=coverage vendor/bin/paratest -f --log-junit var/coverage/junit.xml 
```

if `var/coverage` doesn't exist, it ends up outputting this:

```
file_put_contents(var/coverage/junit.xml): Failed to open stream: No such file or directory in vendor/brianium/paratest/src/Logging/JUnit/Writer.php on line 99
```

#### Expected behavior

No error. Currently it can be achieved by creating the missing dir. But using phpunit only, there's no such error ...

**Comment by raneomik** [comment]
Greetings ! here's my proposal to fix for this issue : #630

**Comment by remorhaz** [comment]
Stumbled upon this issue, too.

**Comment by frutsel32** [comment]
I'm having this issue as well. Any update on the related PR?
