### ISSUE TITLE
`--verbose=<int>` options fails with fatal error

### ISSUE THREAD

**Issue by maks-rafalko** [paratestphp/paratest#633]
| Q | A
| --- | ---
| ParaTest version | 6.3.1
| PHPUnit version | 9.5.9
| PHP version | 8.0.10

#### Summary

```
--verbose=<int>
```

option does not work, while it mentioned on README https://github.com/paratestphp/paratest#troubleshooting

#### Current behavior

`--verbose=1` fails with the following exception:

```
In ArgvInput.php line 228:
                                                          
  [Symfony\Component\Console\Exception\RuntimeException]  
  The "--verbose" option does not accept a value.         
                                                          

Exception trace:
  at /srv/api/vendor/symfony/console/Input/ArgvInput.php:228
 Symfony\Component\Console\Input\ArgvInput->addLongOption() at /srv/api/vendor/symfony/console/Input/ArgvInput.php:140
 Symfony\Component\Console\Input\ArgvInput->parseLongOption() at /srv/api/vendor/symfony/console/Input/ArgvInput.php:76
 Symfony\Component\Console\Input\ArgvInput->parse() at /srv/api/vendor/symfony/console/Input/Input.php:55
 Symfony\Component\Console\Input\Input->bind() at /srv/api/vendor/symfony/console/Command/Command.php:258
 Symfony\Component\Console\Command\Command->run() at /srv/api/vendor/symfony/console/Application.php:978
 Symfony\Component\Console\Application->doRunCommand() at /srv/api/vendor/symfony/console/Application.php:295
 Symfony\Component\Console\Application->doRun() at /srv/api/vendor/symfony/console/Application.php:167
 Symfony\Component\Console\Application->run() at /srv/api/vendor/brianium/paratest/bin/paratest:37

```

Passing `--verbose` works, but does not do anything.

What I would like to do is to understand how coverage are combined and merged, because `paratest` definitely breaks coverage (will report under separate issue).

**Comment by Slamdunk** [comment]
> because `paratest` definitely breaks coverage

Take a look at:
1. https://github.com/paratestphp/paratest/issues/400
2. https://github.com/sebastianbergmann/php-code-coverage/issues/726

**Comment by maks-rafalko** [comment]
@Slamdunk any recommendations on how to debug the issues with "random" coverage on each run for the same commit?

btw, I've checked https://github.com/paratestphp/paratest/issues/400 - it works correctly, so the issue reported there is not reproduced. But on my project - we have different jumps related to code coverage when `paratest` is used

`#1`
![coverage-covered](https://user-images.githubusercontent.com/3725595/134369794-2f99067e-e94b-43d2-add2-c3cf753a6397.png)

`#2`
![coverage-not-covered](https://user-images.githubusercontent.com/3725595/134369796-3259575a-8ae6-46cd-be6c-f7219a02a300.png)

`#3`
![coverage-not-exectured](https://user-images.githubusercontent.com/3725595/134369799-b781b4a2-50de-48fc-bf9e-815b4482bf57.png)

**Comment by Slamdunk** [comment]
I have this issue from the beginning of my usage of ParaTest, and never been able to properly debug it ever since, any help is welcome

**Comment by maks-rafalko** [comment]
But feom paratest point of view, is there any commands/options useful for debugging?

I hoped it would be `--verbose`, but it doesn't work :)

The only one way I see is by using debugger

**Comment by Slamdunk** [comment]
I have to say I'm a bit ashamed, I've never put much effort in providing better debugging tools for inspecting ParaTest issues.
What I can say is:

1. `-vv` is the only meaningful verbosity, it prints the underlying command ParaTest executes; what it **doesn't** tell you is, in the `WrapperRunner` context, the `n-th` process the command is running on, that would be a bit more helpful
2. Right now there is no way to have deterministic runs: the first process that returns free receives the next test. That's a pita for debugging purposes, because we can't have always `#1` or `#2` or `#3` output, but just a random one out of the three base on how each test lasted

So, in order to fix this I'd say we'd first need a deterministic `Runner` to properly debug the exact same run multiple times.

**Comment by Slamdunk** [comment]
Hi, https://github.com/paratestphp/paratest/pull/679 aligned `--verbose` behavior to PHPUnit's one, and added `--debug` like PHPUnit's one.
