### ISSUE TITLE
Paratest fails when no tests are found

### ISSUE THREAD

**Issue by enumag** [paratestphp/paratest#636]
| Q | A
| --- | ---
| ParaTest version | 6.3.1
| PHPUnit version | 9.5.10
| PHP version | 8.0.10

#### Summary

When the configured directories don't contain any tests, Paratest behaves differently than PHPUnit.

#### Current behavior

PHPUnit:

```
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

No tests executed!

```

Paratest:

```
In SuiteLoader.php line 172:

  No path or configuration provided (tests must end with Test.php)

```

#### How to reproduce: command, code and error stack trace

Delete all tests and try running phpunit and paratest to see the difference.

#### Expected behavior

Same as PHPUnit, Paratest should succeed with a note that there are no tests.

**Comment by remorhaz** [comment]
This problem also occurs when given group selects no tests, and it breaks our pipelines in CI.

**Comment by Slamdunk** [comment]
A PR would be very welcome

**Comment by remorhaz** [comment]
I didn't dig into code yet, but I run the following command in my CI:

`vendor/bin/paratest --processes=10 --log-junit=build/log/junit.xml --configuration=phpunit.system.xml --testsuite=ui --group=API`

In this case, given suite is not empty, but it doesn't contain any tests in a given group. I have the following output:

```
Running phpunit in 10 processes with /builds/tsp/websites-apps/site-tests/vendor/phpunit/phpunit/phpunit
Configuration read from /builds/tsp/websites-apps/site-tests/phpunit.system.xml
Time: 00:00.200, Memory: 12.00 MB
OK (0 tests, 0 assertions)
```

Everything seems okay, no errors; but the command returns exit code 1.

**Comment by remorhaz** [comment]
I've prepared a PR, please take a look.
