### ISSUE TITLE
Missing support of --stderr argument

### ISSUE THREAD

**Issue by bancer** [paratestphp/paratest#637]
| Q | A
| --- | ---
| ParaTest version | 6.3.1
| PHPUnit version | 9.5.10
| PHP version | 7.4.3

#### Summary

Using `--stderr` argument fails with "The "--stderr" option does not exist. " error. Our tests do not pass without `--stderr`.

#### Current behavior

phpunit supports `--sterr`:

```
Vendor/bin/phpunit --help | grep stderr
  --stderr                    Write to STDERR instead of STDOUT
```
but paratest command does not recognize it.

#### How to reproduce: command, code and error stack trace

Run `Vendor/bin/paratest --stderr tests`.

#### Expected behavior

I would expect paratest to take `--stderr` argument and pass it to phpunit.

**Comment by bancer** [comment]
Still needed.

**Comment by Jean85** [comment]
I fear that changing the output of the underlying PHPUnit processes could mess with how Paratest collects that output.

Also, I think you can already use that option leveraging the `--passthru` option, so `--passthru="--stderr"`; have you tried it?

**Comment by bancer** [comment]
`--passthru="--stderr"` seems to work. Thanks.

**Comment by Jean85** [comment]
Great! I'll close this since we have `--passthru` exactly to avoid having to maintain every single specific PHPUnit option directly.
