### ISSUE TITLE
Windows 11 compatibility issue

### ISSUE THREAD

**Issue by Temepest74** [paratestphp/paratest#638]
| Q | A
| --- | ---
| ParaTest version | x.y.z
| PHPUnit version | x.y.z
| PHP version | x.y.z

#### Summary

I am on windows 11 and they stopped using wmic.

#### Current behavior

    ```
PS D:\Applications\Programming\WAMP\www\intern> php artisan test -p
Warning: TTY mode is not supported on Windows platform.
'wmic' is not recognized as an internal or external command,
operable program or batch file.

Time: 00:00.270, Memory: 22.00 MB

OK (21 tests, 0 assertions)
```
but no test actually runs

#### How to reproduce: command, code and error stack trace

Just use the lastest win 11 version

**Comment by Slamdunk** [comment]
Hi, I have no opportunity to test in windows environment, and as far as I can tell GitHub actions doesn't provide win11.

If you can debug and propose a pr to solve the issue, i will be glad to review it.

**Comment by Temepest74** [comment]
> Hi, I have no opportunity to test in windows environment, and as far as I can tell GitHub actions doesn't provide win11.
> 
> If you can debug and propose a pr to solve the issue, i will be glad to review it.

Maybe I will give it a shot, but I cannot guarantee. I just wanna know (if u can answer), is this package using wmic or it is a dependency?

**Comment by Slamdunk** [comment]
I have no idea what wmic is

**Comment by flexchar** [comment]
@Temepest74 heads up! I would strongly recommend to use WSL 2, far easier!

**Comment by Temepest74** [comment]
> @Temepest74 heads up! I would strongly recommend to use WSL 2, far easier!

I do now, but the package is still broken on win 11
