### ISSUE TITLE
Update code coverage instructions for latest phpunit.xml format.

### ISSUE THREAD

**Issue by Beakerboy** [paratestphp/paratest#642]
| Q | A
| --- | ---
| ParaTest version | x.y.z
| PHPUnit version | x.y.z
| PHP version | x.y.z

#### Summary
The existing documentation (docs/code-coverage.md) links to and references the xml Schema for PHPUnit 7.4. The Schema has been updated for PHPUnit 9.

#### Current behavior
The existing documentation suggests \<filter\> and \<whitelist\> tags, while PHPUnit currently uses \<coverage> and \<include> tags.

**Comment by Slamdunk** [comment]
Closed in https://github.com/paratestphp/paratest/pull/674
