### ISSUE TITLE
Paratest is unstable and coverage retrieve different percentages each time I rerun tests

### ISSUE THREAD

**Issue by EARodriguez2021** [paratestphp/paratest#651]
| Q | A
| --- | ---
| ParaTest version | 6.4.1
| PHPUnit version | 9.5.11
| PHP version | 8.1.1

When I run tests, the percentage of the coverage is different

if I execute simple phpunit command, the percentage of my coverage is always the same. and after executing paratest, that percentage is different each time I rerun tests

**Comment by Slamdunk** [comment]
Hi, I am aware of the bug, but need the time to investigate it

**Comment by EARodriguez2021** [comment]
Thank you, I think this is a great library :)

**Comment by Slamdunk** [comment]
I finally made it to create a self-contained small enough repo that shows the bug.

@EARodriguez2021 @maks-rafalko can you confirm the issue you're having is similar to https://github.com/Slamdunk/paratest_phpunit_codecoverage_bug/tree/master#readme ?

**Comment by EARodriguez2021** [comment]
Yes, @Slamdunk you're right, this is one of the main bugs that we experimented using different quantity of processes in the command executed because sometimes constants inside of an array are covered and suddenly same values are not covered without any logical reason. thank you for your valuable time you give us, we really appreciate it.

**Comment by Slamdunk** [comment]
Thread continues at https://github.com/sebastianbergmann/php-code-coverage/issues/889

**Comment by EARodriguez2021** [comment]
Perfect, thanks

**Comment by Slamdunk** [comment]
So, after for 4 days of digging the bug, there's a workaround: autoload the class with the constants in the test bootstrap.
Taking the first example of https://github.com/Slamdunk/phpunit_codecoverage_bug#readme a simple
```php
// tests_bootstrap.php
class_exists(AType::class);
```
will get you to a consistent report of both tested and untested lines.

I have an idea on how to avoid this manual step, but in the meantime that's what I have for you

**Comment by EARodriguez2021** [comment]
Excellent, thank you so much @Slamdunk that was a good solution

**Comment by Slamdunk** [comment]
Stay tuned: https://github.com/sebastianbergmann/php-code-coverage/pull/892 will likely solve the issue altogether :muscle:

**Comment by Slamdunk** [comment]
[`v6.4.3`](https://github.com/paratestphp/paratest/releases/tag/v6.4.3) release now brings much more consistency between  PHPUnit and ParaTest code coverage reports
