### ISSUE TITLE
Allow maximum threads option

### ISSUE THREAD

**Issue by specialtactics** [paratestphp/paratest#658]
Hello

We have a situation where we are not limiting threads on our testsuite for a given project (ie. go as many threads as possible), but we are seeing concurrency issues after around 8-12 threads. Because this test suite runs on different computers and CI servers, we don't want to hardcode it at the limit, since sometimes it may need to run well under (ie. small resource CI thread), and that's fine.

What I would propose is allowing an option on the upper limit on threads - say X, essentially such that if p > X, then p = X

I am happy to try and code this extra option if you think it's an acceptable idea, and if you want to suggest a parameter name for it.

Thanks

**Comment by Slamdunk** [comment]
Hi, I think this kind of issue would be better solved on user side, with something like a custom `Makefile` that decides the `--processes` value the way you like.

Having said that, `--processes` option already accepts multiple value types, so we can add a new syntax like `<8` there:

https://github.com/paratestphp/paratest/blob/5123a31dbf0b5deeaec17b00c0c5f31732c14483/src/Runners/PHPUnit/Options.php#L352-L358

If you are going to propose it in a new PR, please also update the option description with the already supported values (integer, `half` and `auto`):

https://github.com/paratestphp/paratest/blob/5123a31dbf0b5deeaec17b00c0c5f31732c14483/src/Runners/PHPUnit/Options.php#L753-L759
