### ISSUE TITLE
Debug mode and continuing on crash

### ISSUE THREAD

**Issue by JoelMarcey** [paratestphp/paratest#66]
Hi, two questions about paratest:

**\* 1. Is there a way to run phpunit in --debug mode with paratest, so that I can see the name of each individual test running as paratest is executing? I tried:

paratest --phpunit "phpunit --debug" 

but that continues to run the tests like the --debug switch was never specified.

**\* 2. Is there an option to have paratest continue running even after a phpunit crash? I am using HHVM to run various framework test suites and some of the tests in those suites cause fatal errors. So I get the 

"Log file /tmp/PT_G8Mg9B is empty. This means a PHPUnit process has crashed." 

type of message. Instead, is there a way to (1) spawn another instance of phpunit that continues with the next test after the crash? (2) run each test in its own process so that one crash does not affect all of the other tests (sort of like phpunit --process-isolation, I guess).

Thank you.

**Comment by uzbxodgiev** [comment]
Hi guys in Laravel 5.4 I installed paratest with composer but it crashes when I run my tests. Crash Log below

Log file C:\Users\SomUserName\AppData\Local\Temp\PT_9E76.tmp is empty. This means a PHPUnit process has crashed.
  The process: C:\xampp\htdocs\project\project_project\some_project\vendor\bin\phpunit.bat --configuration C:\xampp\htdocs\project\project_project\some_project\phpunit.xml --log-junit C:\Users\
  SomUserName\AppData\Local\Temp\PT_9E76.tmp Tests\Feature\ExampleTest C:\xampp\htdocs\project\project_project\some_project\tests\Feature\ExampleTest.php
  This means a PHPUnit process was unable to run "C:\xampp\htdocs\project\project_project\some_project\tests\Feature\ExampleTest.php"

**Comment by paslandau** [comment]
@JoelMarcey 

For 
> *** 1. Is there a way to run phpunit in --debug mode with paratest, so that I can see the name of each individual test running as paratest is executing? I tried:

I added a `--verbose=1` option that will now output the underyling phpunit command.
