### ISSUE TITLE
How to organize BeforeFirstTestHook

### ISSUE THREAD

**Issue by jokaorgua** [paratestphp/paratest#660]
Hello.

I have around 2.5k tests (functional and unit) and a single phpunit.xml for running them. Also I have a class that setups the database before running each case and it has been implemented with the help of BeforeFirstTestHook

Could anyone recommend the logic of how to organize the tests for using the paratest? Seems to me paratest runs this webhook before each test which slows down the whole testsuite (even with unit test where the database is not needed at all)?

Thanks in advance

**Comment by Slamdunk** [comment]
Something like https://github.com/paratestphp/paratest/issues/480#issuecomment-691823517 ?

**Comment by jokaorgua** [comment]
@Slamdunk awesome :) thanks
