### ISSUE TITLE
PHPStorm integration not working

### ISSUE THREAD

**Issue by Orrison** [paratestphp/paratest#676]
| Q | A
| --- | ---
| ParaTest version | 6.5.0
| PHPUnit version | 9.5.21
| PHP version | 8.1

#### Summary

The file mentioned in https://github.com/paratestphp/paratest#integration-with-phpstorm (`./vendor/bin/paratest_for_phpstorm`) is not with the `./vender/bin` folder even after a fresh install. So it is not possible to setup the PHPStorm integration.

#### Current behavior

The file `./vendor/bin/paratest_for_phpstorm` does not exist even on a fresh install of `6.5.0` so it is not possible to setup the new PHPStorm integration

#### Expected behavior

`./vendor/bin/paratest_for_phpstorm` should exist on an update or fresh install

**Comment by Orrison** [comment]
Possible false alarm

**Comment by Orrison** [comment]
Nvm it is not working, sorry!

**Comment by Jean85** [comment]
Bin export is missing, #677 should fix it.
