### ISSUE TITLE
Show skipped tests messages with `--verbose`

### ISSUE THREAD

**Issue by machitgarha** [paratestphp/paratest#683]
At [Serenata](https://gitlab.com/Serenata/Serenata), there are performance tests written using PHPUnit. They use `TestCase::markTestSkipped()` to report the execution time to standard output. Running these tests takes a long time, so running them in parallel makes even more sense than normal tests. However, it's not possible because `paratest` throws the execution time messages away.

Would you please add this feature if `--verbose` option is used?

**Comment by Slamdunk** [comment]
> They use `TestCase::markTestSkipped()` to report the execution time to standard output.

That's definitively a weird hack.

[`v6.6.0`](https://github.com/paratestphp/paratest/releases/tag/v6.6.0) added support for TestDox output, which in verbose mode also outputs the times of each test.

**Comment by machitgarha** [comment]
@Slamdunk, we want to exclude part of a test from being included in the measured time. See [this one](https://gitlab.com/Serenata/Serenata/-/blob/master/tests/Performance/FunctionListProvidingPerformanceTest.php#L10) for example, we don't want to include the indexing time.

**Comment by machitgarha** [comment]
This issue is still relevant...

**Comment by Slamdunk** [comment]
Tracking data by the output of `TestCase::markTestSkipped()` it's far from optimal and standard.

Messing with `STDOUT`/`STDERR` in ParaTest is a nightmare and I'm not gonna do it for someone's hack: I sugget you to track times in other manners.

**Comment by machitgarha** [comment]
@Slamdunk, you mean by using tools other than PHPUnit? If so, then we might loose the benefits of ParaTest...

**Comment by Slamdunk** [comment]
No, I mean by logging times into an external file like `file_put_contents('times.txt', $elapsedTime, FILE_APPEND);` and then inspect that file

**Comment by machitgarha** [comment]
Makes sense. Thanks.

**Comment by Jean85** [comment]
Another suggestion: https://github.com/johnkary/phpunit-speedtrap

**Comment by Slamdunk** [comment]
> Another suggestion: https://github.com/johnkary/phpunit-speedtrap

There are two issues with ParaTest and `SpeedTrapListener`:

1. it outputs its result in the `STDOUT` of the subprocess, which ParaTest currently discards 
2. it cannot aggregate data over different/concurrent processes

In general, TestListeners are not natively supported in the parallel context, they need do be designed that way in order to work properly
