### ISSUE TITLE
Coverage with phpstorm

### ISSUE THREAD

**Issue by MikeDevresse** [paratestphp/paratest#685]
| Q | A
| --- | ---
| ParaTest version | 6.6.1
| PHPUnit version | 9.5.21
| PHP version | 8.1.8

#### Summary

When running with coverage, it throw an error, that the process argument is not found

#### Current behavior

When running it runs with phpunit and not paratest

#### How to reproduce: command, code and error stack trace

Create a phpstorm convide as described in the readme, and then run with coverage

#### Expected behavior

Should run with coverage

The reason why it's doing it is because when preparing, paratest_for_phpstorm removes the phpunit command line argument. But when running with coverage, phpstorm adds an aditional argument to enable pcov.

I managed to make an hotfix for this but I don't think it's clean enough but it may be a start, in src/Util/PhpstormHelper.php, I added at line 21 :
```php
if($argv[1] === '-dpcov.enabled=1') {
    unset($argv[1]);
    unset($argv[2]);

    return $paratestBinary;
}
```

**Comment by billypoke** [comment]
Accounting for xdebug coverage as well, here's what I came up with.

```php
if (! in_array('--filter', $argv, true)) {
    if (in_array(
        $argv[1],
        [
            '-dpcov.enabled=1',
            '-dxdebug.mode=coverage',
        ],
        true
    )) {
        // If coverage is enabled, then $argv[2] is the phpunit binary
        unset($argv[2]);
    }

    // If coverage is disabled, then $argv[1] is the phpunit binary, otherwise $argv[1] is the coverage option 
    unset($argv[1]);

    return $paratestBinary;
}
```
