### ISSUE TITLE
Is this package compatible with CI/CD?

### ISSUE THREAD

**Issue by TheDevick** [paratestphp/paratest#696]
It's may a dumb question, but can we use it on Github Workflows ( With no big issues )?

If yes, it's there any example of a `.yml` file for CI on Github Actions?

**Comment by mfn** [comment]
It works like anything else you write a github action workflow: make sure your PHP version is right, composer dependencies are installed and call `vendor/bin/paratest`, assuming you configured it correctly with it's default options or pass additional args.

I usually wrap them in a composer `scripts` entry and call this in CI/CD, so I'm sure when I call it locally, it's the same args.
