### ISSUE TITLE
Is there a way to redirect the output to a file to read it more easily?

### ISSUE THREAD

**Issue by thomasmoors** [paratestphp/paratest#699]
I tried

`php artisan test --parallel --without-tty  out.txt`

`php artisan test --parallel > out.txt`

`php artisan test --parallel | tee out.txt`

None of those work in this case

**Comment by Slamdunk** [comment]
Hi, the commands you provided are specific to Laravel, which I don't know anything about, sorry

**Comment by thomasmoors** [comment]
@Slamdunk I understand, but is there a way to forward the --without-tty call?

**Comment by Slamdunk** [comment]
Hi, I have no clue what `--without-tty` is nor how Laravel uses this package, so I can't know the answer

**Comment by thomasmoors** [comment]
Then I will close this issue, still thanks for the great work on the package
