### ISSUE TITLE
Color support cannot be disabled by omitting --colors

### ISSUE THREAD

**Issue by benr77** [paratestphp/paratest#706]
It seems that colourised output is always created where colours are supported, rather than only when the `--colors` flag is present.

I think this comes down to the following line:

https://github.com/paratestphp/paratest/blob/7b0595af467cbf2655c2f297740f0307c9f173f8/src/Console/Commands/ParaTestCommand.php#L92

I'm trying to use the output of the code coverage in CI to extract the current coverage level, and cannot disable the colors.

It would be much better if colour support was only enabled only if the `--colors` flag was specified.

**Comment by Slamdunk** [comment]
You can disable the colors with `--colors=never`

**Comment by benr77** [comment]
Yep thanks. I was using `6.4.4` and see this option was sorted in `6.6.0`.
