### ISSUE TITLE
Multiple configurations depending on process that is running

### ISSUE THREAD

**Issue by kdocki** [paratestphp/paratest#712]
It would be nice if I could have different configurations depending on which process is running. This could be done in different ways.

One way to handle this might be to expose a variable inside of the phpunit.xml file. The variable could be something like ${{paratests.processer_number}}. This would allow me to do things inside of my phpunit.xml like this:

```
<phpunit ...>
   ... omitted stuff here, irrelevant...
  <php>
    <server name="DATABASE_NAME" value="my_test_db_${{paratests.processer_number}}"/>
  </php>
</phpunit>
```
I would expect the above to use the database name my_test_db_3 when running on processor 3.

**Comment by Jean85** [comment]
This feature is already present, it's the test token: https://github.com/paratestphp/paratest#test-token
