### ISSUE TITLE
Fatal error while loading tests

### ISSUE THREAD

**Issue by enumag** [paratestphp/paratest#716]
| Q | A
| --- | ---
| ParaTest version | 6.8.0
| PHPUnit version | 9.5.28
| PHP version | 8.2.1

#### Summary

I'm getting this very odd fatal error after composer update. It only happens when I use paratest, not with just phpunit:

```
Fatal error: Uncaught TypeError: PHPUnit\Util\Annotation\DocBlock::__construct(): Argument #4 ($startLine) must be of type int, bool given, called in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php on line 145 and defined in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php:164
Stack trace:
#0 /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php(145): PHPUnit\Util\Annotation\DocBlock->__construct('', true, Array, false, false, false, '__construct', 'Exception')
#1 /app/vendor/phpunit/phpunit/src/Util/Annotation/Registry.php(93): PHPUnit\Util\Annotation\DocBlock::ofMethod(Object(ReflectionMethod), 'Exception')
#2 /app/vendor/phpunit/phpunit/src/Util/Test.php(590): PHPUnit\Util\Annotation\Registry->forMethod('Exception', '__construct')
#3 /app/vendor/brianium/paratest/src/Parser/Parser.php(118): PHPUnit\Util\Test::isTestMethod(Object(ReflectionMethod))
#4 /app/vendor/brianium/paratest/src/Parser/Parser.php(94): ParaTest\Parser\Parser->getMethods()
#5 /app/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php(192): ParaTest\Parser\Parser->getClass()
#6 /app/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php(171): ParaTest\Runners\PHPUnit\SuiteLoader->initSuites()
#7 /app/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(96): ParaTest\Runners\PHPUnit\SuiteLoader->load()
#8 /app/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(77): ParaTest\Runners\PHPUnit\BaseRunner->load(Object(ParaTest\Runners\PHPUnit\SuiteLoader))
#9 /app/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php(101): ParaTest\Runners\PHPUnit\BaseRunner->run()
#10 /app/vendor/symfony/console/Command/Command.php(312): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /app/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /app/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /app/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /app/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
#15 /app/vendor/bin/paratest(120): include('/app/vendor/bri...')
#16 {main}
  thrown in /app/vendor/phpunit/phpunit/src/Util/Annotation/DocBlock.php on line 164
```

I'm digging around in the code of PHPUnit and Paratest and one odd thing I found is here:

https://github.com/paratestphp/paratest/blob/6.x/src/Parser/Parser.php#L46

The reflection returned by `StandardTestSuiteLoader::load()` is eventually assigned into `$this->refl` at the end of the constructor. However `$this->refl` is annotated with `ReflectionClass<TestCase>` but `StandardTestSuiteLoader::load()` returns reflections for other classes too. :thinking: In this case it's a reflection of a class which extends `\Exception` which eventually leads to the fatal error above.

**Comment by Slamdunk** [comment]
Can you provide a small sample that reproduces the issue please?

**Comment by enumag** [comment]
I don't think so. I have no idea what the prerequisites are to trigger it.

**Comment by enumag** [comment]
This seems to fix it for me: https://github.com/paratestphp/paratest/commit/638dffa69d3356a2efe6fed4dc814da7a9a9d412

**Comment by Slamdunk** [comment]
Do you have any test that doesn't extend `\PHPUnit\Framework\TestCase`?

**Comment by enumag** [comment]
Well many of them don't extend it directly but it always is among the ancestors...

**Comment by enumag** [comment]
I'm experimenting with only updating some libraries to see what exactly will trigger the issue. I'll let you know.

**Comment by enumag** [comment]
Alright. This happens specifically with PHPUnit 9.5.28 while 9.5.27 is fine. Looking at the [changes](https://github.com/sebastianbergmann/phpunit/compare/9.5.27...9.5.28) I suspect something went wrong in [this commit](https://github.com/sebastianbergmann/phpunit/commit/83eaffa12425bb512ba55f466ed9092dcb8e3ffe). I'll experiment with it more tomorrow.

I should also note that StandardTestSuiteLoader is apparently deprecated.

**Comment by enumag** [comment]
Closing in favor of https://github.com/sebastianbergmann/phpunit/issues/5139.

**Comment by enumag** [comment]
Looks like I forgot to actually click the close button... anyways it seems the breaking commit in PHPUnit won't be reverted because `StandardTestSuiteLoader` is marked as `@internal` meaning you are not supposed to use it in Paratest. It's also `@deprecated` now and removed in PHPUnit 10.

**Comment by Slamdunk** [comment]
> `StandardTestSuiteLoader` is marked as `@internal` meaning you are not supposed to use it in Paratest. It's also `@deprecated` now and removed in PHPUnit 10.

I know: https://github.com/paratestphp/paratest#versions

I'm willing to fix the issue on ParaTest side as soon as you are able to provide a minimal, self-contained, with a **meaningful** data set reproducing test case that shows the problem you are reporting.

**Comment by enumag** [comment]
Sadly I already exceeded the time I can spend on this issue while working on the test case for Sebastian which he ended up refusing anyway. So I'll have to stick to PHPUnit 9.5.27 for now. Thanks for understanding.

That said I believe the same issue will happen on pretty much any project when you use Paratest + PHPUnit 9.5.28. I don't think the issue is specific to my project in any way.

**Comment by Slamdunk** [comment]
Thank you @enumag for your precious help

**Comment by enumag** [comment]
Oh you fixed it. Awesome. Thank you!
