### ISSUE TITLE
Class 'PHPUnit_Runner_Version' not found when running ParaTest

### ISSUE THREAD

**Issue by Noojuno** [paratestphp/paratest#718]
| Q | A
| --- | ---
| ParaTest version | 6.8.1
| PHPUnit version | 9.5.28
| PHP version | 7.4

#### Summary

When I try to run paratest, it instantly fails with an error

#### Current behavior

Paratest will not start, regardless of options passed through

#### How to reproduce: command, code and error stack trace
It happens with every command I try, specifically:
`php -d memory_limit=1G -d pcov.enabled=1 ./vendor/bin/paratest -c ./phpunit.xml --passthru-php="'-d' 'pcov.enabled=1'"`
`php vendor/bin/paratest`
`php vendor/bin/paratest --help`
`./vendor/bin/paratest --help`

Stack trace:
```
Fatal error: Uncaught Error: Class 'PHPUnit_Runner_Version' not found in /var/code/project1/vendor/brianium/paratest/src/ParaTest/Console/Commands/ParaTestCommand.php:29
Stack trace:
#0 /var/code/project1/vendor/brianium/paratest/src/ParaTest/Console/Commands/ParaTestCommand.php(48): ParaTest\Console\Commands\ParaTestCommand::isWhitelistSupported()
#1 /var/code/project1/vendor/symfony/console/Command/Command.php(77): ParaTest\Console\Commands\ParaTestCommand->configure()
#2 /var/code/project1/vendor/brianium/paratest/src/ParaTest/Console/Commands/ParaTestCommand.php(19): Symfony\Component\Console\Command\Command->__construct('paratest')
#3 /var/code/project1/vendor/brianium/paratest/src/ParaTest/Console/ParaTestApplication.php(28): ParaTest\Console\Commands\ParaTestCommand->__construct(Object(ParaTest\Console\Testers\PHPUnit))
#4 /var/code/project1/vendor/symfony/console/Application.php(148): ParaTest\Console\ParaTestApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 /var/code/project1/vendor/brianium/paratest/bin/paratest(34): Symfony\Component\Console\Application->run()
#6 /var/code/project1/vendor/bin/paratest(115): include('/var/code/ezyve...')
#7 {main}
  thrown in /var/code/project1/vendor/brianium/paratest/src/ParaTest/Console/Commands/ParaTestCommand.php on line 29
```

#### Expected behavior

Paratest will work (at least to the point where I can use --help on the CLI)

**Comment by Slamdunk** [comment]
`PHPUnit_Runner_Version` call has been removed in https://github.com/paratestphp/paratest/commit/b5f29f2809d932e2175247fee3fe05842eefa115 6 years ago, and no stable release has even been created with it.

I highly doubt this error occurs on ParaTest `6.8.1` as you claim.
