### ISSUE TITLE
Show errors when I stop tests

### ISSUE THREAD

**Issue by dealense7** [paratestphp/paratest#719]
In the project we have 2k+ tests, so it's kind of slow even with paratest. So sometimes when failed tests are shown on the top I want to stop it with `Ctrl+C` and see if which tests are failed.  

Imagine failed tests are shown instead of those skipped tests on the top
![image](https://user-images.githubusercontent.com/60123889/213161441-a9462cd2-67cf-4ab4-bbb8-8a8fc44203e9.png)

**Comment by Slamdunk** [comment]
> I want to stop it with `Ctrl+C` and see if which tests are failed.

That doesn't work in PHPUnit neither.

Try the `--testdox` output for that.

**Comment by Jean85** [comment]
Maybe `--stop-on-failure` could help too? I don't remember if Paratest uses that or not.

**Comment by Slamdunk** [comment]
Yes it does: https://github.com/paratestphp/paratest/blob/168c1cfdf79e5b19b57cb03060fc9a6a79c5f582/src/Runners/PHPUnit/Options.php#L792-L797

Thank you @Jean85 :+1:
