### ISSUE TITLE
Process isolation not possible on version 7

### ISSUE THREAD

**Issue by schonhoff** [paratestphp/paratest#736]
| Q | A
| --- | ---
| ParaTest version | v7.0.6
| PHPUnit version | 10.0.13
| PHP version | 8.1.9

#### Summary
Hey,

after upgrading my Laravel app to phpunit 10 and paratest 7 I can no longer use `--passthru="--process-isolation"` as a command to give phpunit the possibility to isolate every test in its own php process. This was very useful for my test suite because it has a lot of feature tests and even with 4GB RAM it will continue to go out of memory.

I declared it as a bug because the v6 could use this type of command.

#### Current behavior

Neither the passthru command exists:
`The "--passthru" option does not exist.`
nor does the process-isolation command
`The "--process-isolation" option does not exist.`

#### How to reproduce: command, code and error stack trace

My command was/is:

`php artisan test --parallel --passthru="--process-isolation" --coverage --coverage-html coverage`

#### Expected behavior

In my opinion it should be possible to isolate each test in his own php process. This will allow big applications with a lot of feature tests to run the coverage command without running into memory problems. 
See: https://docs.phpunit.de/en/10.0/textui.html?highlight=process%20isolation#configuration

Thanks for doing a great job with this package!

**Comment by Slamdunk** [comment]
`passthru` was a curse: we wouldn't control anything passed to it.

I've added the flag as an explicit one in `v7.1`

**Comment by schonhoff** [comment]
@Slamdunk Thanks for the fast update! I can understand the problem with the `passthru` command.
