### ISSUE TITLE
Broken with the latest PHPUnit version

### ISSUE THREAD

**Issue by gehrisandro** [paratestphp/paratest#740]
| Q | A
| --- | ---
| ParaTest version | 7.1.0
| PHPUnit version | 10.0.16
| PHP version | 8.1.14

#### Summary

Fatal error: Uncaught Error: Call to undefined method PHPUnit\Event\TestSuite\TestSuite::fromTestSuite() in vendor/brianium/paratest/src/WrapperRunner/ApplicationForWrapperWorker.php:69

`fromTestSuite()` has been remove from PHPUnit:
https://github.com/sebastianbergmann/phpunit/commit/29d5ed82a53024537e7c80c89876dd0fb5b7cdb0#diff-dd79e073346deb652faa86b70cd845ca5683919ba92feb21cdc533eb941a6c92L27

#### Current behavior

Paratest does not run

#### How to reproduce: command, code and error stack trace

1. Upgrade to the latest PHPUnit version
2. Run Paratest

#### Expected behavior

Paratest should run

**Comment by gehrisandro** [comment]
Thank you very much @Slamdunk

**Comment by dan-the-dev** [comment]
Tests are back to green so it's very good, thanks for the speed!
But this is my current output (only the end): 

`
  12754 / 1647 (774%)
  12755 / 1647 (774%)
  12756 / 1647 (774%)
. 12757 / 1647 (774%)
  12758 / 1647 (774%)
  12759 / 1647 (774%)
  12760 / 1647 (774%)
  12761 / 1647 (774%)
  12762 / 1647 (774%)
  12763 / 1647 (774%)
  12764 / 1647 (774%)
  12765 / 1647 (775%)
. 12766 / 1647 (775%)
  12767 / 1647 (775%)
  12768 / 1647 (775%)
  12769 / 1647 (775%)
  12770 / 1647 (775%)
  12771 / 1647 (775%)
  12772 / 1647 (775%)
  12773 / 1647 (775%)
  12774 / 1647 (775%)
. 12775 / 1647 (775%)

Time: 01:00.396, Memory: 54.00 MB

OK (1647 tests, 5237 assertions)`

there's probably something weird going on here :D it seems to work so no urgency.
Do you think it's worth for me to open a new bug?

**Comment by Slamdunk** [comment]
Yes please
