### ISSUE TITLE
Cannot use Paratest globally with the PHAR version of PHPUnit in PHPStorm

### ISSUE THREAD

**Issue by lperamo** [paratestphp/paratest#747]
| Q | A
| --- | ---
| ParaTest version | 7.1.2
| PHPUnit version |10.0.18
| PHP version | 8.2.4

#### Summary

I run an XML configuration file using Paratest via PHPStorm and it fails even before the test really begins.

#### Current behavior
As I said in the title, I use the PHAR version of PHPUnit **10.0.18** and I have installed Paratest **7.1.2** _globally_ via Composer.
I am launching it via PHPStorm **2022.3.3**.

I use an XML configuration file and a custom bootstrap that contains a custom autoloader for my own framework.

I get :

> /usr/bin/php /home/lionel/.config/composer/vendor/bin/paratest_for_phpstorm /var/www/html/lib/phpunit.phar --bootstrap /var/www/html/perso/otra/tests/testBootstrap.php -v --configuration /var/www/html/perso/otra/tests/phpunitAll.xml --teamcity
> Testing started at 10:40 ...
> PHP Fatal error:  Uncaught RuntimeException: Missing path to '/phpunit' in /home/lionel/.config/composer/vendor/brianium/paratest/src/Util/PhpstormHelper.php:60
> Stack trace:
> #0 /home/lionel/.config/composer/vendor/brianium/paratest/src/Util/PhpstormHelper.php(20): ParaTest\Util\PhpstormHelper::getArgvKeyFor()
> #1 /home/lionel/.config/composer/vendor/brianium/paratest/bin/paratest_for_phpstorm(10): ParaTest\Util\PhpstormHelper::handleArgvFromPhpstorm()
> #2 /home/lionel/.config/composer/vendor/bin/paratest_for_phpstorm(120): include('...')
> #3 {main}
>   thrown in /home/lionel/.config/composer/vendor/brianium/paratest/src/Util/PhpstormHelper.php on line 60
> 
> Process finished with exit code 255

I tried (temporarily, just to see if it works) to replace in the file `~/.config/composer/vendor/brianium/paratest/src/Util/PhpstormHelper.php` the line :
```php
$phpunitKey = self::getArgvKeyFor($argv, '/phpunit');
```
by
```php
$phpunitKey = self::getArgvKeyFor($argv, '/var/www/html/lib/phpunit.phar');
```
but then I got :

> /usr/bin/php /home/lionel/.config/composer/vendor/bin/paratest_for_phpstorm /var/www/html/lib/phpunit.phar --bootstrap /var/www/html/perso/otra/tests/testBootstrap.php -v --configuration /var/www/html/perso/otra/tests/phpunitAll.xml --teamcity
> Testing started at 10:41 ...
> ParaTest v7.1.2 upon PHPUnit 10.0.18 by Sebastian Bergmann and contributors.
> 
> 
> Path not found for the class name : phpunit\framework\TestCase
> PHP Fatal error:  Uncaught Error: Class "phpunit\framework\TestCase" not found in /var/www/html/perso/otra/tests/src/BlocksTest.php:13
> Stack trace:
> #0 /home/lionel/.config/composer/vendor/phpunit/phpunit/src/Runner/TestSuiteLoader.php(107): require_once()
> #1 /home/lionel/.config/composer/vendor/phpunit/phpunit/src/Runner/TestSuiteLoader.php(46): PHPUnit\Runner\TestSuiteLoader->loadSuiteClassFile()
> #2 /home/lionel/.config/composer/vendor/phpunit/phpunit/src/Framework/TestSuite.php(257): PHPUnit\Runner\TestSuiteLoader->load()
> #3 /home/lionel/.config/composer/vendor/phpunit/phpunit/src/TextUI/Configuration/Xml/TestSuiteMapper.php(92): PHPUnit\Framework\TestSuite->addTestFile()
> #4 /home/lionel/.config/composer/vendor/phpunit/phpunit/src/TextUI/Configuration/TestSuiteBuilder.php(53): PHPUnit\TextUI\XmlConfiguration\TestSuiteMapper->map()
> #5 /home/lionel/.config/composer/vendor/brianium/paratest/src/WrapperRunner/SuiteLoader.php(52): PHPUnit\TextUI\Configuration\TestSuiteBuilder->build()
> #6 /home/lionel/.config/composer/vendor/brianium/paratest/src/WrapperRunner/WrapperRunner.php(103): ParaTest\WrapperRunner\SuiteLoader->__construct()
> #7 /home/lionel/.config/composer/vendor/brianium/paratest/src/ParaTestCommand.php(89): ParaTest\WrapperRunner\WrapperRunner->run()
> #8 /home/lionel/.config/composer/vendor/symfony/console/Command/Command.php(312): ParaTest\ParaTestCommand->execute()
> #9 /home/lionel/.config/composer/vendor/symfony/console/Application.php(1022): Symfony\Component\Console\Command\Command->run()
> #10 /home/lionel/.config/composer/vendor/symfony/console/Application.php(314): Symfony\Component\Console\Application->doRunCommand()
> #11 /home/lionel/.config/composer/vendor/symfony/console/Application.php(168): Symfony\Component\Console\Application->doRun()
> #12 /home/lionel/.config/composer/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
> #13 /home/lionel/.config/composer/vendor/brianium/paratest/bin/paratest_for_phpstorm(10): require('...')
> #14 /home/lionel/.config/composer/vendor/bin/paratest_for_phpstorm(120): include('...')
> #15 {main}
>   thrown in /var/www/html/perso/otra/tests/src/BlocksTest.php on line 13
> 
> Process finished with exit code 255

Error that I didn't get without the use of Paratest.

**Comment by Slamdunk** [comment]
Hi, we only support PHPUnit installed by composer, sorry
