### ISSUE TITLE
Test classes are not found under provided paths

### ISSUE THREAD

**Issue by Wirone** [paratestphp/paratest#749]
| Q | A
| --- | ---
| ParaTest version | 6.9.1
| PHPUnit version | 9.6.5
| PHP version | 7.4.33 / 8.2.4

#### Summary

I wanted to try [ParaTest in PhpCsFixer](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6883) but it seems like not all tests are executed. [Here's the reason described](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6883#issuecomment-1497321496).

I know that project's readme states that only latest PHPUnit supported and latest ParaTest is maintained, but in order to introduce ParaTest in PhpCsFixer we need support for PHP 7.4. Otherwise we only could run tests through ParaTest only on 8.1+, while regular PHPUnit on older versions (which wouldn't provide as much improvement as it was used on all PHP versions).

#### Current behavior

`SuiteLoader` can't find some of the test classes under test file paths, [here](https://github.com/paratestphp/paratest/blob/51691208db882922c55d6c465be3e7d95028c449/src/Runners/PHPUnit/SuiteLoader.php#L190-L199).

#### How to reproduce: command, code and error stack trace

Checkout [`Wirone:codito/paratest`](https://github.com/Wirone/PHP-CS-Fixer/tree/codito/paratest), run `composer install` and then `vendor/bin/paratest` - only ~11k of tests are executed, while it should be ~32k.

Example `NoClassInFileException` caught [here](https://github.com/paratestphp/paratest/blob/51691208db882922c55d6c465be3e7d95028c449/src/Runners/PHPUnit/SuiteLoader.php#L197) for [this test file](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/fb7f3523d563406554a3e739ecc98c25b7943867/tests/Console/Report/FixReport/JunitReporterTest.php):

```
^ ParaTest\Parser\NoClassInFileException^ {#11801
  #message: "/<project_path>/tests/Console/Report/FixReport/JunitReporterTest.php"
  #code: 0
  #file: "/<project_path>/vendor/brianium/paratest/src/Parser/Parser.php"
  #line: 73
  -previous: PHPUnit\Runner\Exception^ {#11802
    #message: "Class JunitReporterTest could not be found in /<project_path>tests/Console/Report/FixReport/JunitReporterTest.php"
    #code: 0
    #file: "/<project_path>/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php"
    #line: 50
    trace: {
      /<project_path>/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:50 { …}
      /<project_path>/vendor/brianium/paratest/src/Parser/Parser.php:46 { …}
      /<project_path>/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php:193 { …}
      /<project_path>/vendor/brianium/paratest/src/Runners/PHPUnit/SuiteLoader.php:170 { …}
      /<project_path>/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php:96 { …}
      /<project_path>/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php:77 { …}
      /<project_path>/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php:101 { …}
      /<project_path>vendor/symfony/console/Command/Command.php:312 { …}
      /<project_path>/vendor/symfony/console/Application.php:1022 { …}
      /<project_path>/vendor/symfony/console/Application.php:314 { …}
      /<project_path>/vendor/symfony/console/Application.php:168 { …}
      /<project_path>/vendor/brianium/paratest/bin/paratest:37 { …}
      /<project_path>/vendor/bin/paratest:120 { …}
    }
  }
```

#### Expected behavior

All test classes are loaded properly and tests are executed.

**Comment by Slamdunk** [comment]
I am aware that this happened in the past.
It doesn't seem to be caused by https://github.com/paratestphp/paratest#caveats

I will merge any well-written PR that fix this on `v6`, but I'm not going to work on it personally.

**Comment by oojacoboo** [comment]
Also running into this issue fairly regularly.  Is there file locking going on in PHPUnit?  Are the runners colliding, attempting to access the same file at the same time?

**Comment by Wirone** [comment]
@oojacoboo when I looked into implementation it just collects set of loaded classes, then tries to load test class and then compares new set of loaded class with previous one. It's a little naïve, because some classes can load different classes too. It most probably needs a rework, but as author said, it must be done by contributor.

**Comment by oojacoboo** [comment]
>@oojacoboo when I looked into implementation it just collects set of loaded classes, then tries to load test class and then compares new set of loaded class with previous one

What's collecting a set of loaded classes?  I'm specifically wondering if PHPUnit is placing file locks.  PHPUnit isn't designed for parallel processing really, although I'm sure improvements have been made to support it better.

**Comment by Wirone** [comment]
There's explanation linked in the description, specifically [this part](https://github.com/paratestphp/paratest/blob/51691208db882922c55d6c465be3e7d95028c449/src/Runners/PHPUnit/SuiteLoader.php#L190-L199) does not work as expected.

**Comment by oojacoboo** [comment]
Cool, we're not using the `SuiteLoader` I don't believe.  That'd come from using the `--parallel-suite` flag, right?

**Comment by Wirone** [comment]
No, it's used internally when regular command is run.

**Comment by oojacoboo** [comment]
The error exists with PHPUnit not finding the test class though.  All that does it gets the tests to send to PHPUnit for running.

> previous: PHPUnit\Runner\Exception^ {#11802 #message: "Class JunitReporterTest could not be found in /<project_path>tests/Console/Report/FixReport/JunitReporterTest.php")

> /<project_path>/vendor/phpunit/phpunit/src/Runner/StandardTestSuiteLoader.php:50 { …}

It's possible JUnit is an issue for you.  We're not using that.

**Comment by Wirone** [comment]
No, JUnit is not a problem. It's only example exception, one of many, and it's for PHPCSFixer's internal class related to JUnit reporter. It does not matter, the problem is most probably related to reflections used in tests (as [caveates](https://github.com/paratestphp/paratest#caveats) describe).

> The error exists with PHPUnit not finding the test class though.

I know, because Paratest's [parser](https://github.com/paratestphp/paratest/blob/51691208db882922c55d6c465be3e7d95028c449/src/Parser/Parser.php) uses PHPUnit's `StandardTestSuiteLoader` internally and in some scenarios it thinks class was not loaded, because of the implementation mentioned earlier.

I believe we should not continue such discussion here - everything is described, author knows the problem but does not want work on it since it's related to previous release (v6), and it's fair. We're only generating unnecessary noise now.

**Comment by Wirone** [comment]
We'll probably bump PHP requirement to `^8.0` soon, so I'll try newer version of ParaTest too. I hope it's fixed there 🤞🙂.

**Comment by Wirone** [comment]
Sorry for the noise, it's because of rebasing branch within PR that has long lifecycle 🙁. I'll remove reference from the commit.

**Comment by Wirone** [comment]
@Slamdunk I understand why you close it, but at least do it as "not planned", because it wasn't completed (resolved) 😉.

**Comment by Slamdunk** [comment]
Didn't know that was even an option, thanks :smile:
