### ISSUE TITLE
Result printer does not display all details when testdox attribute is used

### ISSUE THREAD

**Issue by KarinaRashchynskaya** [paratestphp/paratest#759]
| Q | A
| --- | ---
| ParaTest version | 7.1.4
| PHPUnit version | 10.1.2
| PHP version | 8.1

#### Summary

Hello, 

I am executing my `phpunit tests` using the combination of `brianium/paratest`, `nunomaduro/collision` and `orchestral/testbench` packages. Recently, I started using the `testdox` functionality. 
I noticed when `testdox= true`, then any warning or error information is missing from console.

#### Current behavior

After some research, I noticed that the `ResultPrinter:194` of `brianium/paratest`, does not go forward, in case it finds the `testdox` functionality enabled. So, it prints only `testdox` details and if there are any errors or warnings, they are been skipped.

![Screenshot from 2023-05-09 14-24-37](https://github.com/paratestphp/paratest/assets/115797465/0c2d3876-1684-42c7-97ce-5a543f5baf0a)
![Screenshot from 2023-05-09 14-39-18](https://github.com/paratestphp/paratest/assets/115797465/15997f52-6ac9-4d04-ba24-21183c692782)

#### How to reproduce: command, code and error stack trace

However, If I remove the `return` statement, then I receive all the information correctly.

![Screenshot from 2023-05-09 14-25-51](https://github.com/paratestphp/paratest/assets/115797465/22238d83-52cf-4d3e-9640-74e81acedf37)

Can you please check it ?

Thanks a lot

**Comment by KarinaRashchynskaya** [comment]
Hello,

Do you have any update on the issue above?

Thank you

**Comment by KarinaRashchynskaya** [comment]
Hello @Slamdunk ,

Thank you for your feedback. However, after the fix, I still do not get a complete response in case of warnings. That's because configuration options like `displayPhpunitWarnings, displayPhpunitErrors` etc are not supported by `phpunit.xml` configuration. So, again  when` testdox= true`, then any warning or error information is missing from the console.

So, I would like to ask, if it is possible instead of using ` if else` statement to do something like this ?
![Screenshot from 2023-06-22 14-28-25](https://github.com/paratestphp/paratest/assets/115797465/b19a77cc-1e7a-4ccd-b4c7-0afc1eaa76af)



Also in my understanding, the difference comes to the Printer type which in the case of ` testdox= true` the `SummaryPrinter` takes place. So, what about if it is replaced by the  `DefaultResultPrinter`?

Thanks a lot

**Comment by Slamdunk** [comment]
You are right: I've tagged https://github.com/paratestphp/paratest/releases/tag/v7.2.2 with an additional fix
