### ISSUE TITLE
General error: 1 table "migrations" already exists -- error using Laravel + ParaTest

### ISSUE THREAD

**Issue by netdjw** [paratestphp/paratest#760]
| Q | A
| --- | ---
| ParaTest version | 7.1.3
| PHPUnit version | 10.1.2
| PHP version | 8.2.5
| Laravel | 10.9.0

#### Summary

After I ugraded PHPUnit & Laravel versions I needed to upgrade paratest too. Previous 6.x version was worked fine. When I run paratest now I get repeated error messages about table already exists and database locked. Configurations and test files are not changed, only changes was the version upgrade.

#### Current behavior

When I run paratest (vendor/bin/paratest) I get these errors multiple times:

```
PDOException: SQLSTATE[HY000]: General error: 5 database is locked
```
```
Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: 1 table "migrations" already exists
```
```
PDOException: SQLSTATE[HY000]: General error: 1 table "migrations" already exists
```

Paratest says:
```
Processes:     12
```

#### How to reproduce: command, code and error stack trace

PHPUnit XML file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="https://schema.phpunit.de/10.1/phpunit.xsd"
    bootstrap="vendor/autoload.php"
    colors="true"
    cacheResult="true"
    backupGlobals="false"
>
    ...
    <php>
        <env name="DB_CONNECTION" value="sqlite"/>
        <env name="DB_DATABASE" value=":memory:"/>
    </php>
    ...
</phpunit>
```

#### Expected behavior

What was the expected (correct) behavior? Run tests without errors.

**Comment by Slamdunk** [comment]
Version 7 now defaults to `WrapperRunner`. From your error I guess you are trying to create the database every test: add a `DROP DATABASE IF EXISTS` before the `CREATE DATABASE`, to ensure a clean up of previous tests.

**Comment by netdjw** [comment]
I don't know what `WrapperRunner` is.

Yes I run migrate before all tests, because I want a clean database for each tests. But how it's possible this worked before update and now it's broken? Does `WrapperRunner` have anything to do with it?

**Comment by Slamdunk** [comment]
In `v6` the default was `Runner`, which spawned a separate process for each test.
In `v7` the `WrapperRunner` spawns a process and then runs multiple tests in the same sub-process.

**Comment by netdjw** [comment]
I see. Is there any way to configure Paratest to work the same as v6?

**Comment by Slamdunk** [comment]
No

**Comment by netdjw** [comment]
Ok, so little more details for my case.

I use Spatie's multitenancy package for Laravel.

For testing I created a custom `MultitenancyTestCase` what is extends the `Illuminate\Foundation\Testing\TestCase` class. Here is my code:

```php
class MultitenancyTestCase extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        // setup run tests without middlewares and so on...

        $this->setUpLandlord();

        $this->setUpTenant();

        // some other settings
    }

    private function setUpLandlord(): void
    {
        // migrate landlord database
        Artisan::call('migrate --path=database/migrations/landlord --database=landlord');
        Artisan::call('db:seed --class=RoleSeeder');

        // ... some other configuration, seeding for landlord db
    }

    private function setUpTenant(): void
    {
        Artisan::call('tenants:artisan "migrate --database=tenant"');
    }

    // some extra functions
}
```
The multitenancy package is configured to use different database for tenant and for landlord, but in testing both uses the `:memory:` database (I logged out in both function.)

So if I drop the database and recreate it it will happening on `:memory:` db and this leads to this situation:

1. drop db in landlord function
2. run the landlord migration and seed
3. drop db in tenant function
4. run the tenant migration and seed

So in the 3rd step I drop the database what is created in step 2nd. 

Am I right?

And if I'm right, how can I avoid this situation and/or fix my issue?

**Comment by Slamdunk** [comment]
I'm sorry I don't know Laravel nor Spatie's packages.
I suggest you to ask them how to better integrate your tests with their port of ParaTest in the respective libraries.

**Comment by netdjw** [comment]
The situation is not depend on Laravel, nor Spatie's package I think. It was just more details.

The point is: I use two databases in real life, but in tests are both created into `:memory:` database. If I drop the db, I destroy half of my tables what are neccessary for testing.

So the question is: is there any other way to fix my issues without dropping database?

**Comment by Slamdunk** [comment]
I have no clue, but if you find a solution please share it here

**Comment by netdjw** [comment]
Okay, thanks for your support!

**Comment by CLCWebsiteServices** [comment]
> Okay, thanks for your support!

Did you manage to find a solution for this?! I've just encountered the same issue!
