### ISSUE TITLE
Support for Custom Printer

### ISSUE THREAD

**Issue by alexander-schranz** [paratestphp/paratest#775]
I'm using in mostly all new projects the following printer, which has a really nice output for success and failures: https://github.com/nunomaduro/collision

It would be nice if I could use it also with Paratests, maybe there is also a general solution to support custom printers.

**Comment by Slamdunk** [comment]
Custom printers have been removed from PHPUnit 10:
https://github.com/sebastianbergmann/phpunit/blob/10.0.0/ChangeLog-10.0.md#removed

Pest does a lot under the hood to get it working, I suggest you to try that framework if you really need `collision`,
