### ISSUE TITLE
Dead spinners in phpstorm test runner

### ISSUE THREAD

**Issue by mrozbarry** [paratestphp/paratest#777]
| Q | A
| --- | ---
| ParaTest version | 7.2.2
| PHPUnit version | 10.2.4
| PHP version | 8.1.z

#### Summary

When I use the paratest_for_phpstorm wrapper, test output is mismatched. Test files marked as failures are sometimes incorrect, and if a test fails in a nested namespace, at least one other test in that namespace seem to have locked spinner animations.

Behaviour only started with we upgraded to laravel 10 and php unit 10. We have about 2.5k tests, running in 12 processes.

Everything works as expected running directly in the terminal.

#### Current behavior

This behaviour only happens when running tests through paratest_for_phpstorm in phpstorm's test runner.

When a test fails:

 - It _sometimes_ reports the wrong filename (but clicking on it gives a proper stack trace and references the correct file)
 - If a test fails near the root namespace, at least one other test deeper in the same namespace won't "complete" and the spinner animation doesn't go away.

#### How to reproduce: command, code and error stack trace

`paratest_for_phpstorm`

We don't have a specific test that fails that causes this bug

#### Expected behavior

 - Failing tests should not affect other tests being marked as completed
 - Failing tests should be displayed properly in the phpstorm test runner

**Comment by Slamdunk** [comment]
Bugs related to a desktop client are almost impossible for me to reproduce.

I will merge any well crafted PR about this issue, but I don't have the means to deal with this myself.
