### ISSUE TITLE
Worker crashing after all tests doesn't produce any meaningful output

### ISSUE THREAD

**Issue by oprypkhantc** [paratestphp/paratest#788]
| Q | A
| --- | ---
| ParaTest version | 7.2.6
| PHPUnit version | 10.3
| PHP version | 8.1.9

#### Summary

If a worker crashes for whatever reason after executing all of the assigned tests (i.e. `ApplicationForWrapperWorker::end()` method), then ParaTest doesn't acknowledge the worker has crashed and hence doesn't print any meaningful debugging output. 

#### Current behavior

If a worker crashes after all tests, this is the output produced (in this case - with coverage):

```
........................................................... 17936 / 17964 ( 99%)
......R
Time: 59:16.353, Memory: 439.50 MB
No tests executed!
Generating code coverage report in Clover XML format ... done [01:16.524]
Generating code coverage report in Cobertura XML format ... done [00:13.068]
Generating code coverage report in HTML format ... done [01:11.969]
Code Coverage Report:       
  2023-09-04 16:39:47       
                            
 Summary:                   
  Lines:    0.00% (0/123123123)
```

There's no "100%" line; it states that no tests were executed (although 18k were indeed executed) and the coverage is empty. It's all due to silent discarding of missing output files from the wrapper worker.

#### How to reproduce: command, code and error stack trace

Add a `throw new \RuntimeException();` into `ApplicationForWrapperWorker::end()` and run ParaTest.

#### Expected behavior

I'd expect a "WorkerCrashedException" with a full STDOUT/STDERR output printed the same way it does when a worker crashes when executing a test.

I'd also expect a stack trace if it was due to an exception. Right now, `error_reporting()` or `ini_set('display_errors', 'On');` is never called anywhere in ParaTest and there are no try-catch blocks inside of `phpunit-wrapper.php`. That means that even if `WorkerCrashedException` was thrown in this case, it'd still have an empty output and would still be harder to debug than it should be.

**Comment by Slamdunk** [comment]
I acknowledge the bug, and that it should indeed be fixed, but can yo give me please a real-world example that happened to you?

**Comment by oprypkhantc** [comment]
We are upgrading from PHPUnit 9 and ParaTest 6. We have about 18k tests and were previously able to generate coverage using the default "Runner". Now that that's gone, generating a coverage (specifically the `--coverage-php` printer that ParaTest uses internally) requires insane amounts of memory because of how inefficiently PHP/PHPUnit serialize CodeCoverage object [here](https://github.com/sebastianbergmann/php-code-coverage/blob/main/src/Report/PHP.php#L25). PHPUnit was trying to allocate too much memory, hence crashing. 

We had a 2GiB memory_limit set for workers and that still wasn't enough, and increasing that to 3GiB per worker didn't help. Of course a lot of that 3GiB+ of memory is shared memory between all PHP processes, but it still manages to use 12GiB allocated to the Docker container running ParaTest :(

`--max-batch-size` should've helped in this case, but without the 7.2.6 [fix](https://github.com/paratestphp/paratest/commit/7f372b5bb59b4271adedc67d3129df29b84c4173) workers were also mysteriously crashing without giving any information on what causes it, so I gave up on trying to use that option. That's fixed (thank you), but now using `--max-batch-size` generates a segfault 🤦🏻 : `7 Segmentation fault      (core dumped)`

**Comment by Slamdunk** [comment]
You seems someone who did your research, but I'll tell you anyway: `#[CoversClass(MyClass::class)]` annotations are definitively a must for sane `CodeCoverage` object sizes (see https://github.com/sebastianbergmann/php-code-coverage/blob/d74598007cc2cd4094b6185ba9fcaf0e784120ac/src/CodeCoverage.php#L237-L242)

Then a `--max-batch-size=1` process should be no more than few MB (on top of your application memory footprint).

**Comment by oprypkhantc** [comment]
Yes that's in our backlog :) But first we wanted to get up-to-date on all of the dependencies.

**Comment by Slamdunk** [comment]
Our prod app has 45k LoC, 13MB in size, 3k tests, 95% CodeCoverage, 70% CC Mutation Score.
We enforce `#[CoversClass()]` annotations, we do **not** use `--max-batch-size`, and these are our serialized outputs before ParaTest merges them together:

```console
$ docker-compose exec php ls -lh /tmp
total 43M
-rw-rw---- 1 code code 3.8M Sep  6 11:19 worker_01_stdout_64f84420d4a9d_coverage
-rw-rw---- 1 code code 4.3M Sep  6 11:19 worker_02_stdout_64f84420d53c1_coverage
-rw-rw---- 1 code code 3.2M Sep  6 11:19 worker_03_stdout_64f84420d5b23_coverage
-rw-rw---- 1 code code 3.2M Sep  6 11:19 worker_04_stdout_64f84420d6120_coverage
-rw-rw---- 1 code code 2.9M Sep  6 11:19 worker_05_stdout_64f84420d679e_coverage
-rw-rw---- 1 code code 3.1M Sep  6 11:19 worker_06_stdout_64f84420d72e0_coverage
-rw-rw---- 1 code code 2.8M Sep  6 11:19 worker_07_stdout_64f84420d7c0f_coverage
-rw-rw---- 1 code code 2.9M Sep  6 11:19 worker_08_stdout_64f84420d8838_coverage
-rw-rw---- 1 code code 3.5M Sep  6 11:19 worker_09_stdout_64f84420d95f5_coverage
-rw-rw---- 1 code code 2.4M Sep  6 11:19 worker_10_stdout_64f84420da3b3_coverage
-rw-rw---- 1 code code 4.3M Sep  6 11:19 worker_11_stdout_64f84420db269_coverage
-rw-rw---- 1 code code 7.1M Sep  6 11:19 worker_12_stdout_64f84420dc067_coverage
```
And after the merge:
```console
$ ll data/code-coverage/coverage.php 
-rw-rw---- 1 code code 29M Sep  6 11:20 data/code-coverage/coverage.php
```
I would prioritize this over dep updates :wink:

**Comment by oprypkhantc** [comment]
Ours has almost 200k LoC and of all tests only about 10% are units. The rest are integration tests, so adding `#[CoversClass]` to them will not be trivial I imagine. We also can't add `#[CoversNothing]` to them because that wouldn't show a true picture about covered lines and our coverage would drop to 10% 😆 

Do you also have `#[CoversClass]` in your integration tests or have you limited them to units?

**Comment by Slamdunk** [comment]
We do use `#[CoversClass]` for integration tests too, with the rule of thumb to be pragmatic:

1. Multiple annotations for a single Integration test are allowed
2. You can include covers for a class that the test was not specifically written for, but you don't have a unit test for yet (so at least you know where it's used)
3. Don't add covers annotations just for the sake of 100% CC
4. A single `./src` class shouldn't have more than 2 or 3 related covers annotation

That's something I wouldn't allow in a library, but hey we gotta pay the bills here :smile:

**Comment by oprypkhantc** [comment]
Got it. That is helpful, thank you :) 

Now all that's left is to automate adding `#[Covers]` to all of our tests. Hopefully Rector helps me here.

**Comment by oprypkhantc** [comment]
We were able to generate coverage with 6GiB per worker and 49GiB for the master ParaTest process 😆  Yeah definitely need the `#[Covers]` attributes, that won't work for too long.

**Comment by Slamdunk** [comment]
@oprypkhantc https://github.com/sebastianbergmann/phpunit/pull/5509 has been merged and you should see now a drastic reduction in coverage files size as well as memory consumption

**Comment by oprypkhantc** [comment]
That's awesome, but it did not help 😅  The reason it didn't help I suppose is that at no point in time are we generating both `--coverage-php` and any other coverage type at the same time, be it on PHPUnit or ParaTest side.

ParaTest workers only use `--coverage-php`, so they couldn't have been affected by cache generated from other `--coverage-*` options. We don't use `--coverage-php` on our side, only the rest of `--coverage-*` options, so again cache is not important here.

I've started automating `#[Covers]` attributes through a PHPUnit extension and will open-source the solution if it comes out okay. I'm hoping to at least save 50% on efforts from our team.

**Comment by CanVuralStudocu** [comment]
> I've started automating #[Covers] attributes through a PHPUnit extension and will open-source the solution if it comes out okay. I'm hoping to at least save 50% on efforts from our team.

@oprypkhantc Just out of curiosity, what was the experience with the extension? Was it successful?

**Comment by oprypkhantc** [comment]
> > I've started automating #[Covers] attributes through a PHPUnit extension and will open-source the solution if it comes out okay. I'm hoping to at least save 50% on efforts from our team.
> 
> @oprypkhantc Just out of curiosity, what was the experience with the extension? Was it successful?

Unfortunately I had other tasks, this one is on pause. It looked like the extension solution may work for Integration tests.

For unit tests though it doesn't seem like that's a good solution, so my plan for them is to write a Rector rule that matches a class and it's test case based on namespace / class name.

**Comment by oprypkhantc** [comment]
@CanVuralStudocu This is the extension we ended up using: https://github.com/oprypkhantc/phpunit-auto-covers

Keep in mind that it's not a composer package, it's not "production ready" and I'm not going to support it. But I specifically added an MIT license to that repo so you can hard fork it and do whatever you want with it.

The algorithm is as follows:
  - look for coverage metadata (attributes, annotations) from PHPUnit. If there's any already specified, skip to the next test;
  - look for `@see` annotation above the test case. We use that to reference the class that's being tested, which is pretty much `#[CoversClass]`. If there are any, then add `#[CoversClass]` or `#[CoversFunction]`  and skip to the next test;
  - check the namespace. If it's a unit test (namespace contains Tests\Unit\ ), then guess the source class name by removing the Tests\Unit\ from the class name. So `Modules\ABC\Tests\Unit\SomeService` test will get a `#[CoversClass(\Modules\ABC\SomeService::class)]`  and skip to the next test;
  - otherwise treat it as an integration test and use code coverage driver to get classes that the test covers. I only capture the covered files between the end of setUp hook and the end of the test to avoid a lot of clutter in covered classes. I also filter covered classes by a "root namespace" - i.e. a test in `Modules\ABC\Tests\Integration\SomethingTest` can only cover source classes from `Modules\ABC\` namespace

This successfully covered 98.5% of our tests, leaving just 61 test case files to fix by hand. They were unit tests without `@see` annotations and with non-matching namespace structure. After that I added a `requireCoverageMetadata=true` that was it. In the end, the coverage dropped by about 13% in lines, functions, methods and classes 🙃  But that's alright, at least now generated coverage better represents the real picture.

This change has also resolved performance/resources usage problems with coverage:
  - paratest now uses 3GB of RAM to merge and generate reports at the end of the run instead of 53GB
  - paratest now generates an HTML report in about 20 seconds instead of 8+ minutes

**Comment by CanVuralStudocu** [comment]
@oprypkhantc Thank you for the detailed information! I'll look into it :+1:
