### ISSUE TITLE
Typed property ParaTest\WrapperRunner\ApplicationForWrapperWorker::$configuration must not be accessed before initialization

### ISSUE THREAD

**Issue by Koudy** [paratestphp/paratest#789]
| Q | A
| --- | ---
| ParaTest version | 7.2.6
| PHPUnit version | 10.3.3
| PHP version | 8.2.6

#### Summary
I get error in container logs when run parallel tests on Laravel. It looks like the instance of the `ApplicationForWrapperWorker` class that is created here: https://github.com/paratestphp/paratest/blob/7.x/bin/phpunit-wrapper.php#L49 is missing either a call to the `bootstrap()` method or configuration setting.

#### Current behavior
Tests pasts well, but I get error in container logs
```
/var/www# php artisan test --parallel --processes=16 tests/Unit
ParaTest v7.2.6 upon PHPUnit 10.3.3 by Sebastian Bergmann and contributors.
Processes:     16
Runtime:       PHP 8.2.6
Configuration: /var/www/phpunit.xml
.                                                                   1 / 1 (100%)
Time: 00:01.327, Memory: 44.50 MB

OK (1 test, 1 assertion)
```

#### How to reproduce: command, code and error stack trace
Call command in Laravel project:
```
php artisan test --parallel --processes=16 tests/Unit
```

```
PHP Fatal error:  Uncaught Error: Typed property ParaTest\WrapperRunner\ApplicationForWrapperWorker::$configuration must not be accessed before initialization in /var/www/vendor/brianium/paratest/src/WrapperRunner/ApplicationForWrapperWorker.php:211
2023-09-14T10:15:35.408177770Z Stack trace:
2023-09-14T10:15:35.408181887Z #0 /var/www/vendor/brianium/paratest/bin/phpunit-wrapper.php(67): ParaTest\WrapperRunner\ApplicationForWrapperWorker->end()
2023-09-14T10:15:35.408186055Z #1 /var/www/vendor/brianium/paratest/bin/phpunit-wrapper.php(77): {closure}()
2023-09-14T10:15:35.408189312Z #2 {main}
2023-09-14T10:15:35.408192490Z   thrown in /var/www/vendor/brianium/paratest/src/WrapperRunner/ApplicationForWrapperWorker.php on line 211
```

#### Expected behavior
No error in logs

**Comment by Slamdunk** [comment]
I can confirm that this happens, but it should only happen under the hood as the sub-process output gets ignored by ParaTest.
I have no idea how it could end up in any log :man_shrugging:
