### ISSUE TITLE
Negative num. of processes, not to use maximum threads

### ISSUE THREAD

**Issue by pistej** [paratestphp/paratest#791]
Hi,

we are running test without -p or --processes=PROCESSES options, to not limit threads, but often we run tests on different computers and then we wanna save at least one thread(process) for different purposes. Would be nice to allow negative number o process. -> -1 means: `self::getNumberOfCPUCores() -1` and so on... or add word as option to save/decrease one thread.

Thx, can send PR if needed.
Similar issue: https://github.com/paratestphp/paratest/issues/658

**Comment by Slamdunk** [comment]
See https://github.com/paratestphp/paratest/pull/792#issuecomment-1731098202
