### ISSUE TITLE
Fatal Error JUnit

### ISSUE THREAD

**Issue by erikbrgn** [paratestphp/paratest#804]
| Q | A
| --- | ---
| ParaTest version | 6.10.1
| PHPUnit version | 9.6.13
| PHP version | 8.1.11

#### Summary

Running `paratest` with `--log-junit` results in a Fatal Error: `Uncaught AssertionError: assert(count($nodes) === 1) in /[REDACTED]/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php:79`

#### Current behavior

A couple of tests execute successfully before crashing in a `Fatal error: Uncaught AssertionError: assert(count($nodes) === 1) in /[REDACTED]/vendor/brianium/paratest/src/Logging/JUnit/TestCase.php:79`

#### How to reproduce: command, code and error stack trace

Unclear at this point. Running natively doesn't produce this error on neither MacOS (Apple silicon) or Linux (AMD). Running in a php container seems fine too. The error occurs when running `paratest` in a container (same image) on a GitHub runner.

#### Expected behavior

No crash.

**Comment by mglaman** [comment]
Bummer this auto-closed (or that I didn't see it sooner.) I'm seeing it as well on our CI runner. I wonder if it is due to symfony/phpunit-bridge generating invalid schema for the XML file.
