### ISSUE TITLE
Multiple skipped not reported

### ISSUE THREAD

**Issue by mpoiriert** [paratestphp/paratest#808]
| Q | A
| --- | ---
| ParaTest version | 6.10.1
| PHPUnit version | 9.6.9
| PHP version | 8.2.11

#### Summary

When executing test with paratest the phpunit progress show multiple S but int the summary only one is shown. (see the attached imaged)

![image](https://github.com/paratestphp/paratest/assets/4175616/cc731461-9f1f-44b9-a899-fb679d620760)

#### How to reproduce: command, code and error stack trace

just runned paratest

#### Expected behavior

Progress and summary should match

**Comment by Slamdunk** [comment]
Thank you for reporting the bug.

I will merge any well-crafted pull request aimed at resolving it, but I will not work on it myself since it's on `v6`, which is not the latest version.

**Comment by mpoiriert** [comment]
Is this ever happen before ?

Issue I have is that if I do a textdot report instead nothing seems skipped.

Not sure where the issue is coming from, is it the summary or the progress
report.

I was planning to upgrade too phpunit 10 soon, I might do this instead.
Hopefully the bug will it be present.

I'll let you know.

**Comment by mpoiriert** [comment]
I end up migrating to Symfony 6.4 (requirement for paratest version 7) and latest version of paratest. 

Everything is working so I will not try to fix it either on version 6.
