### ISSUE TITLE
WorkerCrashedException on class not found

### ISSUE THREAD

**Issue by Rhedynen** [paratestphp/paratest#824]
| Q | A
| --- | ---
| ParaTest version | 6.11.0
| PHPUnit version | 9.6.13
| PHP version | 8.2.13

#### Summary

Running paratest results in a WorkerCrashedException on a class not found

#### Current behavior

When we run our full test suite with paratest, it ends up with this error :
```
In WorkerCrashedException.php line 41:
                                                                               
  The command "PARATEST='1' TEST_TOKEN='1' '/app/vendor/phpunit/phpunit/phpunit' '--configuration' '/app/phpunit.xml.dist' '--no-logging' '--no-coverage' '--printer' 'ParaTest\Runners\PHPUnit\Worker\NullPhpunitPrinter' '--log-junit' '/tmp/xxx' '/app/tests/Controller/SomeEndpointTest.php'" failed.                
                                                                               
  Exit Code: 1(General error)                                                  
                                                                               
  Working directory: /app

Output:                                                                      
================ 

Testing App\Tests\xxx\SubscriberTest
Class SomeEndpointTest could not be found in /app/tests/Controller/SomeEndpointTest.php
```
This issue occurs intermittently, approximately 50% of the time. 

Notice that the file where the error occurs is always the same, even if we change its name and the execution order is different. But the classname mentionned just after the `Output` (here, `App\Tests\xxx\SubscriberTest`) may vary, and `SubscriberTest` does not have any dependency on `SomeEndpointTest`.

#### How to reproduce: command, code and error stack trace

Unfortunatly I cannot provide a reproducer, because the error happens occasionnaly (~50% of the time), in a very long test suite, so I couldn't find a pattern which reproduces the error 100% of the times

#### Expected behavior

No crash

**Comment by Slamdunk** [comment]
Sounds like this refers to https://github.com/paratestphp/paratest#caveats
