### ISSUE TITLE
Reversion from v6: Output test descriptions while tests are running with --testdox

### ISSUE THREAD

**Issue by paullallier** [paratestphp/paratest#829]
I've done some digging, but I'm struggling to work out if this change is a Paratest or PHPUnit feature.  I know the behaviour of --testdox changed in PHPUnit 10, but I think the way paratest tracks output from PHPUnit also changed.

With paratest 6 and PHPUnit, I get a status report output as each test completes - which is very useful to me because my test suite takes a while to run and it gives me an early indiction which tests are failing:
<img width="1153" alt="Screenshot 2023-12-30 at 12 06 59" src="https://github.com/paratestphp/paratest/assets/42591123/d5690614-cdb1-499d-b788-2e1b94033148">

In Paratest 7 and PHPUnit 10, I just get the .FE, etc output as each test continues, and a list of test results at the end.
<img width="1147" alt="Screenshot 2023-12-30 at 12 31 19" src="https://github.com/paratestphp/paratest/assets/42591123/c56467ce-66cb-493a-9faa-0229f1488e06">

Essentially, to generate that output, I'm running `vendor/bin/paratest --functional -p 2 --testdox --filter <string>` - the script is a wrapper to run it inside a docker container.

Is there any way to reinstate the previous behaviour? Or can you help me work out if it's a Paratest or a PHPUnit issue, please?  I can see in Paratest 7 there is a /tmp/worker_xx_*_progress file which contains the . (or F or E), but this seems to be new in Paratest 7 and v6 did something different.  Possibly PHPUnit has changed what goes to stdout while running tests with --testdox.

**Comment by Slamdunk** [comment]
Due to how PHPUnit's code is written right now, ParaTest cannot produce the exact behaviour of PHPUnit on `--testdox` mode, and the one you're describing is the expected one.

You can still however leverage the `--stop-on-defect`.

**Comment by paullallier** [comment]
So it's a PHPUnit 10 change - thanks.

**Comment by Slamdunk** [comment]
Yes and no: the change is in PHPUnit 10, but using a single process only PHPUnit can behave differently from ParaTest regarding the progress output.

Please don't open an issue in PHPUnit: its behavior remained consistent from PHPUnit `v9`.
