### ISSUE TITLE
Dynamically allocate tests to available workers

### ISSUE THREAD

**Issue by sk33wiff** [paratestphp/paratest#833]
Currently, Paratest statically divides tests across workers. For example, with 100 tests and 4 workers, we get 4 groups of 25 tests per worker.

If the average time for these 4 groups of tests is similar, effective allocation across workers occurs. However, if 3 of the test groups take a similar average time to run while 1 takes much longer (e.g. due to lengthy functional tests), we may end up with a single worker running for an extended period. 

Ideally, as long as there are tests that haven't been run yet, they should dynamically allocate to idle workers. This feature request is about adopting a dynamic allocation approach instead.

**Comment by Slamdunk** [comment]
Hi, ParaTest already allocates tests dynamically as you can see in `WrapperRunner::assignAllPendingTests`

https://github.com/paratestphp/paratest/blob/b3341b5ab19549310211defb5176b89228f55c44/src/WrapperRunner/WrapperRunner.php#L129
