### ISSUE TITLE
Unit testing failing on multiple database connection

### ISSUE THREAD

**Issue by shahakshay938** [paratestphp/paratest#843]
| Q | A
| --- | ---
| ParaTest version | 7.3.1
| PHPUnit version | 10.5.10
| PHP version | 8.1.27

#### Summary

Using multiple database connections not Refreshing the database using "RefreshDatabase" trait.
check this [https://github.com/laravel/framework/issues/50194](url)

#### Current behavior

All unit test cases are failing as it was not able to handle multiple database connection
working fine with single database connection

#### How to reproduce: command, code and error stack trace

1. Create a new Laravel Breeze project or use an existing one.
2. Set up two database connections.
3. Update models and migrations to use the desired database via the $connection property.
4. Write test cases or use existing ones (default provided by Breeze).
5. Run the tests.

#### Expected behavior

It should pass the test cases by refreshing multiple database connection with --parallel option

**Comment by Slamdunk** [comment]
Please report the issue to Laravel, `RefreshDatabase` isn't in this library.

**Comment by trovster** [comment]
I have the same issue. Without running in parallel, my databases are seeded. But with parallel, I get errors as paratest only creates numerically indexed databases for the primary connection.
