### ISSUE TITLE
Performance issue on new machine

### ISSUE THREAD

**Issue by DriverCat** [paratestphp/paratest#847]
Hi, I recently upgraded my local machine from i7 12600H to i9 13900H, made similar installation (Laradock) and now my tests run slower 3x.
I understand that this is not Paratest problem, but I search for some advices. Paratest provides easy and understandable measurements. I have about 2K tests running in 20 processes on both old and new machines.
My project files are inside WSL. I tried different settings of WSL resources and much more things, nothing changes.

**Comment by Slamdunk** [comment]
I'm sorry I have no experience in WSL.
