### ISSUE TITLE
Wait between test

### ISSUE THREAD

**Issue by Luc45** [paratestphp/paratest#849]
Feature request: `./vendor/bin/paratest --wait-between-test 5`

**Comment by Slamdunk** [comment]
Hi, this is not something ParaTest should care about.

**Comment by Luc45** [comment]
If you think about it, ParaTest acts as a process manager.

It's much easier to wait before starting another process on the process manager than inside the subprocess. It's a QoL improvement so that we don't need to over-engineer a solution in the context of a subprocess.

I think this QoL pertains to the process manager, it makes it a better process manager, and doesn't deviate from it's purpose and focus :shrug:

**Comment by Slamdunk** [comment]
Providing 1:1 features of PHPUnit is already challenging enough, and doing it for free isn't fun.

But I can give you a quote for a 1 year support for that specific feature: ping me if interested.

**Comment by Luc45** [comment]
Ok, this I can understand :)
