### ISSUE TITLE
[Bug]: Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file

### ISSUE THREAD

**Issue by mikkolukas** [paratestphp/paratest#858]
Coming from [pestphp/pest#1167](https://github.com/pestphp/pest/issues/1167), it turns out the bug is with you.

---

| ParaTest version | 7.4.5
| PHPUnit version | 11.1.3
| PHP version | PHP 8.3.8 (cli) (built: Jun  6 2024 16:32:04) (NTS)
| Composer version | Composer version 2.7.6 2024-05-04 23:03:15

`lsb_release -a`:
```
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 12 (bookworm)
Release:        12
Codename:       bookworm
```

### Current behavior

When I run `composer install` or `composer upgrade` I get this error:

```
0/39 [>---------------------------]   0%    Skipped installation of bin bin/paratest.bat for package brianium/paratest: name conflicts with an existing file
```
![image](https://github.com/paratestphp/paratest/assets/1522239/191817a3-6927-46a4-bf30-490aa980e261)

### How to reproduce: command, code and error stack trace

In an empty directory, create composer.json:
```json
{
    "require": {
        "php": "^8.3"
    },
    "require-dev": {
        "brianium/paratest": "^7.1"
    },
    "config": {
        "sort-packages": true,
        "optimize-autoloader": true,
        "preferred-install": "dist"
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}
```

Run `composer install`

### Expected behavior

The error to not be there.

**Comment by mikkolukas** [comment]
The bug **DOES NOT** appear in brianium/paratest `6.5.0`

The bug **DO** appear in brianium/paratest `6.5.1` (@Jean85, [I believe you are most qualified to fix this?](https://github.com/paratestphp/paratest/commit/41fc4cc01422dae2d6bf6a0ce39756f57ac7d8a9))

**Comment by owenvoke** [comment]
I think it probably would make sense to remove `paratest.bat` from the `bin` key as a stub is automatically generated by Composer anyway. 🤷🏻

But not sure if there's something else causing this.

**Comment by Jean85** [comment]
> I think it probably would make sense to remove `paratest.bat` from the `bin` key as a stub is automatically generated by Composer anyway. 🤷🏻

If that's the case, removing the bat reference in the composer.json is the needed fix, but I would advise to write some kind of test for this, like invoking the executable.

**Comment by Slamdunk** [comment]
Windows support has been (silently) dropped in https://github.com/paratestphp/paratest/pull/575/files#diff-d684acc09c646fd347d0ee93598101fb403664cc70e38cb6f671355ab6de1854L102

Unless someone here is willing to actively support it again, I'm going to officialy drop it in both `6.x` and `7.x` in the next month.
