### ISSUE TITLE
Code coverage: Cache for static analysis has not been configured

### ISSUE THREAD

**Issue by oriolvinals** [paratestphp/paratest#859]
| Q | A
| --- | ---
| ParaTest version | 7.4.1
| PHPUnit version | 11.1.3
| PHP version | 8.2.20

#### Summary

I'm trying to use `pcov` for test coverage with `ParaTest`. Actually, with `PHPUnit` works good, but with `ParaTest` I have an error.

#### Current behavior

The actual behavior is this warning/error message `Cache for static analysis has not been configured`

#### How to reproduce: command, code and error stack trace

My command is `php -d pcov.enabled=1 vendor/bin/paratest --passthru-php="'-d' 'pcov.enabled=1'" --coverage-html=.phpunit/coverage`

If i'm trying with `PHPUnit` with this command `php -d pcov.enabled=1 bin/phpunit --coverage-html=.phpunit/coverage` the tests and the coverage 

#### Expected behavior

Run tests with coverage like it used to be with `PHPUnit` with same coverage result

**Comment by oriolvinals** [comment]
Adding flag `--cache-directory=.phpunit` the error changes

```
Warming cache for static analysis ... [00:04.855]
Processes:     8

In Selector.php line 60:
                                                                
  No code coverage driver with path coverage support available  
                                                               
```

**Comment by Slamdunk** [comment]
[`<cacheDirectory>`](https://docs.phpunit.de/en/10.5/configuration.html#the-cachedirectory-attribute) attribute in `phpunit.xml` has to be set for Code Coverage to work properly with ParaTest, have you set it already?

**Comment by oriolvinals** [comment]
Thanks @Slamdunk, now works correctly!
