### ISSUE TITLE
PHPUnit --path-coverage option

### ISSUE THREAD

**Issue by yan-kudriavtsev** [paratestphp/paratest#863]
Hello. Is there any chance to implement support for the --path-coverage option?

PHPUnit added it in version 9.3
https://github.com/sebastianbergmann/phpunit/issues/4260

Since calculating path code coverage is a very "expensive" process, it would be nice to have support for this option in the paratest, as it takes much longer in PHPUnit. Thank you :-)

**Comment by Slamdunk** [comment]
Hi, personally I am not going to invest my time in such feature because I consider normal code coverage plus mutation testing much more effective and useful, but I'll review any well crafted PR on the topic.

**Comment by yan-kudriavtsev** [comment]
Got it. Thank you. I will try to use normal code coverage + mutation testing
