### ISSUE TITLE
Paratest encounter conflict with phar when no test path is provided

### ISSUE THREAD

**Issue by VincentLanglet** [paratestphp/paratest#868]
| Q | A
| --- | ---
| ParaTest version | 7.5
| PHPUnit version | 11.3.0
| PHP version | 8.3

#### Summary

Seems like there is some differences between running
- `vendor/bin/paratest`
- `vendor/bin/paratest tests/`

#### Current behavior

I have 
- `nikic/php-parser` installed at the v5
- `phpstan/phpstan` installed (and the phar is using the v4)
- some tests using phpstan.

When I run
```
vendor/bin/paratest --runner WrapperRunner --processes 4
```

I get the error
```
Fatal error: Declaration of PhpParser\ParserAbstract::parse(string $code, ?  
  PhpParser\ErrorHandler $errorHandler = null) must be compatible with PhpPar  
  ser\Parser::parse(string $code, ?PhpParser\ErrorHandler $errorHandler = nul  
  l): ?array in phar:///var/www/wg-app/vendor/phpstan/phpstan/phpstan.phar/ve  
  ndor/nikic/php-parser/lib/PhpParser/ParserAbstract.php on line 142
```
coming from the file `tests/PHPStan/PhpDoc/TypeNodeResolverExtensionTest.php`

Which is very odd is the fact that
- I don't have the error with phpunit
- I don't have the error with `vendor/bin/paratest --runner WrapperRunner --processes 4 tests/PHPStan/PhpDoc/TypeNodeResolverExtensionTest.php`
- I don't have the error with `vendor/bin/paratest --runner WrapperRunner --processes 4 tests/`

#### How to reproduce: command, code and error stack trace

Since I have a lot of other things installed, I didn't find a small reproducer so far, but I'm trying to create one.

Still, I'd be intersted understanding why adding `tests/` change the behavior.

#### Expected behavior

No error.

**Comment by Jean85** [comment]
Can you share your PHPUnit config? by adding the filter on what to launch, you're probably overriding the test suite selection coming from there,

**Comment by VincentLanglet** [comment]
> Can you share your PHPUnit config? by adding the filter on what to launch, you're probably overriding the test suite selection coming from there,

Sure, I have
```xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- https://phpunit.readthedocs.io/en/latest/configuration.html -->
<phpunit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="vendor/phpunit/phpunit/phpunit.xsd"
         cacheDirectory=".cache/phpunit"
         backupGlobals="false"
         colors="true"
         bootstrap="tests/bootstrap.php"
         displayDetailsOnTestsThatTriggerDeprecations="true"
         displayDetailsOnTestsThatTriggerWarnings="true"
>
    <php>
        <ini name="display_errors" value="1" />
        <ini name="error_reporting" value="-1" />
        <server name="APP_ENV" value="test" force="true" />
        <server name="SHELL_VERBOSITY" value="-1" />
    </php>

    <testsuites>
        <testsuite name="Functional">
            <directory>tests/Functional</directory>
        </testsuite>
        <testsuite name="Unit">
            <directory>tests/Unit</directory>
        </testsuite>
        <testsuite name="PHPStan">
            <directory>tests/PHPStan</directory>
        </testsuite>
    </testsuites>

    <source>
        <include>
            <directory suffix=".php">src</directory>
        </include>
        <exclude>
            <directory>src/Command/Migration</directory>
            <directory>src/Deploy</directory>
        </exclude>
    </source>

    <extensions>
        <bootstrap class="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension" />
    </extensions>
</phpunit>
```
with the following `tests/bootstrap.php` file 
```php
use Symfony\Component\Dotenv\Dotenv;

require dirname(__DIR__).'/vendor/autoload.php';

if (file_exists(dirname(__DIR__).'/config/bootstrap.php')) {
    require dirname(__DIR__).'/config/bootstrap.php';
} else {
    (new Dotenv())->bootEnv(dirname(__DIR__).'/.env');
}

if ($_SERVER['APP_DEBUG']) {
    umask(0);
}
```

Since all my tests are in the tests folder, I have the same amount of test running with `vendor/bin/paratest` and `vendor/bin/paratest tests`...
