### ISSUE TITLE
Support PHP 8.4

### ISSUE THREAD

**Issue by withinboredom** [paratestphp/paratest#871]
| Q | A
| --- | ---
| ParaTest version | 7.x
| PHPUnit version | unknown
| PHP version | 8.4.0-alpha3

#### Summary

Trying to install pest (see https://github.com/pestphp/pest/issues/1199) on php 8.4 results in a composer error.

#### Current behavior

Unable to install Pest on a newer version of PHP and see what is broken.

#### How to reproduce: command, code and error stack trace

`composer install`

#### Expected behavior

To be able to install on php 8.4

**Comment by Slamdunk** [comment]
Blocked by https://github.com/krakjoe/pcov/pull/111

**Comment by withinboredom** [comment]
@Slamdunk you know who krakjoe is right? You know they're probably never going to update that library right?

https://www.reddit.com/r/PHP/comments/1cjlvmd/where_did_krakjoe_dissappear/

**Comment by Slamdunk** [comment]
1. I know, that's why I donated to https://www.gofundme.com/f/a-big-ask-from-a-big-community
2. Remi Collet has already been granted `Collaborator` status on that repo and can publish new releases autonomously

**Comment by Slamdunk** [comment]
PHP 8.4 support released for both PHPUnit 10 and PHPUnit 11
