### ISSUE TITLE
Stop warnings and deprecations failing tests

### ISSUE THREAD

**Issue by DiogoTheCoder** [paratestphp/paratest#877]
I'm currently trying to upgrade from PHPUnit v9 to v10 and I've got many deprecations which don't fail the PHPUnit tests but are failing when I try to run them under Paratest in a CI pipeline - currently when I run the below it will return with the exit code 1, is there anyway to ignore warnings and deprecations, ignoring them or changing the exit code?

```sh
    docker run -t \
        -v $(pwd)/build:/data/www/pam/somic/build \
        -v $(pwd):/data/www/pam/somic/ \
        -v /data/www/pam/somic/vendor/ \
        -e XDEBUG_MODE=coverage \
        --user $(id -u):$(id -g) \
        --network somic-parallel-test-network \
        "${docker_image}" \
        "/data/www/pam/somic/vendor/bin/paratest \
            -p$processes \
            --runner=WrapperRunner \
            --log-junit /data/www/pam/somic/build/junit-phpunit-php-82-pg-14.xml \
            /data/www/pam/somic/tests"
```

**Comment by peterfox** [comment]
I am also suffering from this currently. Running it in PHPUnit directly doesn't show the PHPUnit deprecations but Paratest will

Edit: solved my problem. It works with https://github.com/paratestphp/paratest/pull/894. The only problem is that the version the patch exists in only works with PHPUnit 11 so the only way to resolve it is with a local patch for PHPUnit 10 users.
