### ISSUE TITLE
failOnPhpunitDeprecation missing in WrapperRunner

### ISSUE THREAD

**Issue by arnovbr** [paratestphp/paratest#884]
| Q | A
| --- | ---
| ParaTest version | 7.4.5
| PHPUnit version | 10.3.32
| PHP version | 8.3.7

#### Summary

In PHPUnit 10.3.32 failOnPhpunitDeprecation was introduced (and 11.3.33 where you did a fix here https://github.com/paratestphp/paratest/commit/c490591cc9c2f4830633b905547d30d5eb609c88)

**Comment by arnovbr** [comment]
I only saw this comment now https://github.com/paratestphp/paratest/pull/883#issuecomment-2330971002
I hope you can merge this, but understand if you decide otherwise.

**Comment by Slamdunk** [comment]
Sorry but, for free, we support only the latest version of PHPUnit.

**Comment by Slamdunk** [comment]
@arnovbr I've seen you've been so kind to pledge to sponsor me.

I'll keep PHPUnit 10 support active as long as you and/or other kind people like you will financially help me.

**Comment by arnovbr** [comment]
I just wanted to send you a nice one time gift for the hard work you are doing. Please enjoy it but do not feel obliged to put your energy into maintaining this. I do hope you will consider constraining the phpunit version so a composer update won`t result in issues.

**Comment by Slamdunk** [comment]
Fix released in [`v7.4.6`](https://github.com/paratestphp/paratest/releases/tag/v7.4.6)
