### ISSUE TITLE
PHPUnit `Extension::bootstrap()` called too late

### ISSUE THREAD

**Issue by nikophil** [paratestphp/paratest#916]
| Q | A
| --- | ---
| ParaTest version | 7.6.1
| PHPUnit version | 11.4
| PHP version | 8.4

Since PHPUnit 11.4, [`bootstrap()` method is called before data provider](https://github.com/sebastianbergmann/phpunit/issues/5913), and [data provider events are dispatched synchronously](https://github.com/sebastianbergmann/phpunit/pull/5917) (before this, they were deferred).

Then, I'm wondering if this should not be reflected in paratest: otherwise, subscribers applying on data providers event will work without paratest, but will not have effect in paratest.

WDYT?

You'll find [here](https://github.com/zenstruck/foundry/pull/736) some kind of a reproducer: running test suite of this lib with paratest fails, whereas it passes with regular phpunit run. The failures occur because the extension bootstrap is called too late.

**Comment by Slamdunk** [comment]
> Then, I'm wondering if this should not be reflected in paratest

It surely has to.

The fix is straightforward, but I need a reproducer in ParaTest's test suite, not trivial to code.
If you are able to propose a PR just with the test that would be super helpful

**Comment by nikophil** [comment]
yes, let's do this :)

**Comment by nikophil** [comment]
done, see https://github.com/paratestphp/paratest/issues/917
