### ISSUE TITLE
Support for @dataProvider (parallel dataset execution)

### ISSUE THREAD

**Issue by michael-donat** [paratestphp/paratest#95]
Not sure how possible that would be, but the lack of dataProvider support is really a pain for me.

I'm using paratest to run my 3rd parties integration suite, one of the most important tests it to see whether I can create multitude of bank accounts (depending on country these have different format, and the provider configuration is dynamic per country, so need to keep an eye on it). I'm using data provider to provide hashes for these different formats.

This is the longest running test in our suite and because of the dataProvider it cannot leverage the parallelism. So far I was able to simply split the data provider into many to give it some hint of parallelisation but a full support for dataProviders would be nice.

As said, not sure how convoluted the PHPUnit implantation of providers is.

**Comment by sormy** [comment]
Here is implementation: https://github.com/brianium/paratest/pull/154

**Comment by tuanmh** [comment]
In our project, we're using a lot of dataProvider annotation to generate test data and this feature in paratest absolutely receives our vote. We really really need this feature.

**Comment by sormy** [comment]
tuanmh, could you please my experimental branch (pull request #154) and give your feedback

**Comment by sormy** [comment]
this problem fixed in the master i think

**Comment by andreasschroth** [comment]
I close this now, as this problem seems to be fixed. Please feel free to reopen if necessary.
